//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol BLTBulletinDistributorSystemStateProvider <NSObject>
- (void)hasBulletinWithMatchID:(NSString *)arg1 sectionID:(NSString *)arg2 completion:(void (^)(_Bool))arg3;
- (_Bool)isSectionCoordinated:(NSString *)arg1 subType:(int)arg2;
- (_Bool)isAlertableBulletinInSection:(NSString *)arg1 subType:(int)arg2;
@end

