//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLEcoModeManager, UIWindow;

@interface CarouselShutdown : NSObject
{
    CSLEcoModeManager *_ecoModeClient;
    UIWindow *__ecoModeClockWindow;
    _Bool _poweringDown;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)powerDownForCriticalBattery;
- (void)prepareForPowerDown;
- (void)powerDown;
- (void)_powerDownNow;
- (void)reboot;
- (void)_rebootNow;
- (void)_powerDownForEcoModeWithOptions:(id)arg1;
- (void)_handleShutdownForEcoModeRequest:(id)arg1;
- (id)init;

@end

