//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLObservableScheduleProvider.h"

#import "CSLAppSwitcherItemModelObserver.h"
#import "CSLComplicationMonitorObserver.h"
#import "CSLPrelaunchBlacklistObserver.h"

@class CSLAppPrelauncher, CSLApplicationAction, CSLApplicationActionPolicy, CSLApplicationPrelaunchCounter, NSObject<OS_dispatch_queue>, NSString;

@interface CSLApplicationPrelaunchScheduleProvider : CSLObservableScheduleProvider <CSLAppSwitcherItemModelObserver, CSLComplicationMonitorObserver, CSLPrelaunchBlacklistObserver>
{
    CSLAppPrelauncher *_appPrelauncher;
    CSLApplicationActionPolicy *_policy;
    CSLApplicationAction *_nextAction;
    CSLApplicationAction *_currentAction;
    CSLApplicationPrelaunchCounter *_prelaunchCounter;
    NSObject<OS_dispatch_queue> *_observerQueue;
    struct _opaque_pthread_mutex_t _actionLock;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *observerQueue; // @synthesize observerQueue=_observerQueue;
@property(retain, nonatomic) CSLApplicationPrelaunchCounter *prelaunchCounter; // @synthesize prelaunchCounter=_prelaunchCounter;
@property(nonatomic) struct _opaque_pthread_mutex_t actionLock; // @synthesize actionLock=_actionLock;
@property(retain, nonatomic) CSLApplicationAction *currentAction; // @synthesize currentAction=_currentAction;
@property(retain, nonatomic) CSLApplicationAction *nextAction; // @synthesize nextAction=_nextAction;
@property(retain, nonatomic) CSLApplicationActionPolicy *policy; // @synthesize policy=_policy;
@property(retain, nonatomic) CSLAppPrelauncher *appPrelauncher; // @synthesize appPrelauncher=_appPrelauncher;
- (void).cxx_destruct;
- (void)complicationMonitorComplicationsDidChange:(id)arg1 addedBundleIDs:(id)arg2 removedBundleIDs:(id)arg3;
- (void)appSwitcherItemModelDidChange:(id)arg1 removedItems:(id)arg2 addedItems:(id)arg3;
- (void)_handleNormalMemoryPressure:(id)arg1;
- (_Bool)_hasEnoughFreeMemoryForPrelaunch;
- (id)_bundleIDsToPrelaunch;
- (void)cancelPrelaunch;
- (void)execute;
- (id)nextScheduledDate;
- (id)_retrievePendingAndChangeNextAction:(id)arg1;
- (void)resume;
- (void)dealloc;
- (void)prelaunchBlacklist:(id)arg1 appExited:(id)arg2 isBlacklisted:(_Bool)arg3;
- (id)_init;
- (id)init;
- (void)_loadPreferences;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

