//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplicationSceneHostAgent.h"

@class NSMutableSet;

@interface CSLApplicationSceneHostAgent : UIApplicationSceneHostAgent
{
    NSMutableSet *_sessions;
}

@property(readonly) NSMutableSet *sessions; // @synthesize sessions=_sessions;
- (void).cxx_destruct;
- (void)openActivitySessionForScene:(id)arg1 action:(id)arg2;
- (void)openActivitySessionsForScene:(id)arg1 event:(id)arg2;
- (void)scene:(id)arg1 reviewEvent:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)scene:(id)arg1 didInitializeWithEvent:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)init;

@end

