//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PUICAdditiveValueAnimator, UIView;

@interface CSLAppToComplicationZoomAnimator : NSObject
{
    UIView *_applicationView;
    UIView *_carouselView;
    struct CGPoint _targetPoint;
    _Bool _zoomingDown;
    struct CGPoint _fullSizePoint;
    struct CGPoint _scaledDownPoint;
    CDUnknownBlockType _completionBlock;
    PUICAdditiveValueAnimator *_zoomPercentageAnimator;
    _Bool _completionCalled;
}

- (void).cxx_destruct;
- (void)_completeIfDone;
- (void)_animationApplier;
- (void)_animateToZoomPercentage:(float)arg1;
- (void)_completeAnimation;
- (void)_updateForZoomPercentage:(float)arg1;
- (void)animateWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithApplicationView:(id)arg1 carouselView:(id)arg2 targetRect:(struct CGRect)arg3 zoomingDown:(_Bool)arg4;

@end

