//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLAppSwitcherViewController, PUICAdditiveValueAnimator, UIView;

@interface CSLAppSwitcherZoomAnimator : NSObject
{
    CSLAppSwitcherViewController *_appSwitcherViewController;
    _Bool _isZooming;
    UIView *_pageIndicatorWrapper;
    CDUnknownBlockType _completionBlock;
    PUICAdditiveValueAnimator *_zoomPercentageAnimator;
    _Bool _completionCalled;
}

- (void).cxx_destruct;
- (void)_completeIfDone;
- (void)_animationApplier;
- (void)_animateToZoomPercentage:(float)arg1;
- (void)_completeAnimation;
- (void)_updateForZoomPercentage:(float)arg1;
- (void)animateWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithAppSwitcherViewController:(id)arg1 isZooming:(_Bool)arg2;

@end

