//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLAppSwitcherDisplaySessionConfiguration, CSLAppSwitcherDisplaySessionDismissedState, CSLAppSwitcherDisplaySessionInitialState, CSLAppSwitcherDisplaySessionQuiescentState, CSLAppSwitcherDisplaySessionScrollingState, CSLAppSwitcherDisplaySessionSettledState, CSLAppSwitcherDisplaySessionState;

@interface CSLAppSwitcherDisplaySession : NSObject
{
    CSLAppSwitcherDisplaySessionInitialState *_initialState;
    CSLAppSwitcherDisplaySessionDismissedState *_dismissedState;
    CSLAppSwitcherDisplaySessionScrollingState *_scrollingState;
    CSLAppSwitcherDisplaySessionSettledState *_settledState;
    CSLAppSwitcherDisplaySessionQuiescentState *_quiescentState;
    CSLAppSwitcherDisplaySessionConfiguration *_configuration;
    CSLAppSwitcherDisplaySessionState *_currentState;
}

@property(retain, nonatomic) CSLAppSwitcherDisplaySessionState *currentState; // @synthesize currentState=_currentState;
@property(readonly, nonatomic) CSLAppSwitcherDisplaySessionConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (void)transitionToState:(id)arg1;
- (void)settleFromInitialState;
- (void)switcherDidEndScrolling;
- (void)switcherDidBeginScrolling;
- (void)endSession;
- (void)beginSession;
- (id)initWithConfiguration:(id)arg1;

@end

