//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLApplicationActionPerformer.h"
#import "CSLUIActivatingUIAssertionObserver.h"

@class CSLPrelaunchAssertionStore, CSLSafeMutableDictionary, CSLSafeMutableSet, NSString;

@interface CSLAppPrelauncher : NSObject <CSLUIActivatingUIAssertionObserver, CSLApplicationActionPerformer>
{
    CSLSafeMutableSet *_activeTransactions;
    CSLPrelaunchAssertionStore *_prelaunchAssertions;
    CSLSafeMutableDictionary *_completionHandlersByBundleID;
}

@property(retain, nonatomic) CSLSafeMutableDictionary *completionHandlersByBundleID; // @synthesize completionHandlersByBundleID=_completionHandlersByBundleID;
@property(retain, nonatomic) CSLPrelaunchAssertionStore *prelaunchAssertions; // @synthesize prelaunchAssertions=_prelaunchAssertions;
@property(retain, nonatomic) CSLSafeMutableSet *activeTransactions; // @synthesize activeTransactions=_activeTransactions;
- (void).cxx_destruct;
- (void)allActivateUIAssertonsAssertionsReleasedForBundleID:(id)arg1;
- (void)_callCompletionHandlerForBundleID:(id)arg1 success:(_Bool)arg2 error:(id)arg3;
- (void)_takePrelaunchAssertionForApp:(id)arg1 created:(CDUnknownBlockType)arg2;
- (void)sendSnapshotActionToApp:(id)arg1;
- (void)cancelPrelaunch;
- (void)prelaunchApp:(id)arg1;
- (void)prelaunchAppWithBundleID:(id)arg1 forReason:(unsigned int)arg2;
- (void)prelaunchAppWithBundleID:(id)arg1 forReason:(unsigned int)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)performAction:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

