//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IOSSHLTransaction.h"

#import "CSLNavigationStackTransitionAnimator.h"
#import "UIViewControllerAnimatedTransitioning.h"

@class NSString;

@interface CSLAnimatedTransitioningTransaction : IOSSHLTransaction <UIViewControllerAnimatedTransitioning, CSLNavigationStackTransitionAnimator>
{
    CDUnknownBlockType _beginAppearanceTransitionBlock;
    _Bool _hasStartedAnimation;
    id <UIViewControllerAnimatedTransitioning> _animator;
    id <UIViewControllerContextTransitioning> _transitionContext;
}

@property(nonatomic) _Bool hasStartedAnimation; // @synthesize hasStartedAnimation=_hasStartedAnimation;
@property(retain, nonatomic) id <UIViewControllerContextTransitioning> transitionContext; // @synthesize transitionContext=_transitionContext;
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animator; // @synthesize animator=_animator;
- (void).cxx_destruct;
- (void)_begin;
- (void)_willBegin;
- (void)_beginTransitionIfPossible;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType beginAppearanceTransitionBlock;
- (id)initWithAnimator:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

