//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CSLAddressBookResetHack : NSObject
{
    struct {
        int version;
        void *info;
        CDUnknownFunctionPointerType retain;
        CDUnknownFunctionPointerType release;
        CDUnknownFunctionPointerType copyDescription;
        CDUnknownFunctionPointerType equal;
        CDUnknownFunctionPointerType hash;
        CDUnknownFunctionPointerType schedule;
        CDUnknownFunctionPointerType cancel;
        CDUnknownFunctionPointerType perform;
    } _context;
    struct __CFRunLoopSource *_source;
    struct __CFRunLoop *_runLoop;
}

- (void)signal;
- (void)cancelFromRunLoop:(struct __CFRunLoop *)arg1 mode:(struct __CFString *)arg2;
- (void)scheduleInRunLoop:(struct __CFRunLoop *)arg1 mode:(struct __CFString *)arg2;
- (void)resetSortDataInProcessIfNeeded;
- (void)dealloc;
- (id)init;

@end

