//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IOSSHLBacklightObserver.h"

@class CSLActivityScheduler, IOSSHLBacklight, NSString;

@interface CSLActivityBacklightObserver : NSObject <IOSSHLBacklightObserver>
{
    IOSSHLBacklight *_backlight;
    id <CSLSchedulerContext> _context;
    CSLActivityScheduler *_scheduler;
}

@property __weak CSLActivityScheduler *scheduler; // @synthesize scheduler=_scheduler;
@property(readonly) id <CSLSchedulerContext> context; // @synthesize context=_context;
@property(readonly) IOSSHLBacklight *backlight; // @synthesize backlight=_backlight;
- (void).cxx_destruct;
- (void)backlight:(id)arg1 didTurnOn:(_Bool)arg2 forReason:(unsigned int)arg3;
- (void)backlight:(id)arg1 willBeOn:(_Bool)arg2 forReason:(unsigned int)arg3;
- (id)initWithBacklight:(id)arg1 context:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

