//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLSwitcherViewControllerObserver.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, _DKEventStream, _DKKnowledgeStore;

@interface CSLAppSwitcherDuetObserver : NSObject <CSLSwitcherViewControllerObserver>
{
    _DKEventStream *_eventStream;
    _DKKnowledgeStore *_knowledgeStore;
    NSObject<OS_dispatch_queue> *_saveQueue;
    NSMutableDictionary *_pendingEvents;
}

+ (id)defaultObserver;
- (void).cxx_destruct;
- (_Bool)shouldSendEvent:(id)arg1 disappearDate:(id)arg2;
- (void)sendEvent:(id)arg1 disappearDate:(id)arg2;
- (id)bundleIDForViewControllerIfExists:(id)arg1;
- (void)updatePendingEventsInRange:(struct _NSRange)arg1 forSwitcher:(id)arg2;
- (void)switcherViewControllerDidUpdate:(id)arg1;
- (void)switcherViewControllerDidAppear:(id)arg1;
- (void)switcherViewControllerDidDismiss:(id)arg1;
- (void)switcherViewControllerDidSettle:(id)arg1;
- (void)switcherViewControllerWillEndFastSwitching:(id)arg1;
- (void)switcherViewControllerWillBeginFastSwitching:(id)arg1;
- (void)switcherViewController:(id)arg1 viewController:(id)arg2 atIndex:(unsigned int)arg3 didDisappear:(_Bool)arg4;
- (void)switcherViewController:(id)arg1 viewController:(id)arg2 atIndex:(unsigned int)arg3 willDisappear:(_Bool)arg4;
- (void)switcherViewController:(id)arg1 viewController:(id)arg2 atIndex:(unsigned int)arg3 didAppear:(_Bool)arg4;
- (void)switcherViewController:(id)arg1 viewController:(id)arg2 atIndex:(unsigned int)arg3 willAppear:(_Bool)arg4;
- (id)initWithEventStream:(id)arg1 knowledgeStore:(id)arg2;

@end

