//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLAppSwitcherDisplaySessionState.h"

#import "FBApplicationUpdateScenesTransactionObserver.h"

@class IOSSHLApplicationUpdateScenesTransaction, NSString;

@interface CSLAppSwitcherDisplaySessionSettledState : CSLAppSwitcherDisplaySessionState <FBApplicationUpdateScenesTransactionObserver>
{
    _Bool _disableActivateOnSettle;
    IOSSHLApplicationUpdateScenesTransaction *_transaction;
    NSString *_queuedBundleID;
}

+ (void)load;
@property(nonatomic) _Bool disableActivateOnSettle; // @synthesize disableActivateOnSettle=_disableActivateOnSettle;
@property(copy, nonatomic) NSString *queuedBundleID; // @synthesize queuedBundleID=_queuedBundleID;
@property(retain, nonatomic) IOSSHLApplicationUpdateScenesTransaction *transaction; // @synthesize transaction=_transaction;
- (void).cxx_destruct;
- (void)transactionDidComplete:(id)arg1;
- (void)quiescentTimerDidFire;
- (void)cancelQuiescentTimer;
- (void)startQuiescentTimer;
- (void)activateAppIfNeeded:(id)arg1;
- (id)fullyVisibleBundleID;
- (void)suspendNonFocalAppsExcludingBundleID:(id)arg1;
- (void)didEnterWithPreviousState:(id)arg1;
- (void)willExitWithNextState:(id)arg1;
- (void)dealloc;
- (id)initWithSession:(id)arg1 configuration:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

