//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLAppSwitcherDisplaySessionState.h"

@class NSTimer;

@interface CSLAppSwitcherDisplaySessionInitialState : CSLAppSwitcherDisplaySessionState
{
    NSTimer *_timer;
}

- (void).cxx_destruct;
- (void)timerFired:(id)arg1;
- (void)willExitWithNextState:(id)arg1;
- (void)didEnterWithPreviousState:(id)arg1;

@end

