//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLMRUApplicationsDelegate.h"
#import "CSLUICarouselApplicationStoreListener.h"
#import "IOSSHLApplicationEventsStoreObserver.h"

@class NPSManager, NSArray, NSString;

@interface CSLAppSwitcherItemModelFactory : NSObject <CSLMRUApplicationsDelegate, CSLUICarouselApplicationStoreListener, IOSSHLApplicationEventsStoreObserver>
{
    _Bool _includeAppStats;
    _Bool _appStatsAvailable;
    _Bool _disableAutoNowPlaying;
    _Bool _forceNowPlaying;
    NSArray *_favoriteBundleIDs;
    NPSManager *_npsManager;
    int _switcherSettingsChangedNotifyToken;
    NSString *_nowPlayingCompanionBundleIdentifier;
    NSString *_nowPlayingWatchBundleIdentifier;
    NSString *_mruBundleID;
    int _maximumFavorites;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) int maximumFavorites; // @synthesize maximumFavorites=_maximumFavorites;
@property(copy, nonatomic) NSString *mruBundleID; // @synthesize mruBundleID=_mruBundleID;
- (void).cxx_destruct;
- (void)eventsStoreSettingsChanged:(id)arg1;
- (void)applicationStore:(id)arg1 applicationPlaceholderInstalled:(id)arg2;
- (void)applicationStore:(id)arg1 addedBundleIDs:(id)arg2 removedBundleIDs:(id)arg3 modifiedBundleIDs:(id)arg4;
- (void)_nowPlayingControllerNowPlayingApplicationInfoDidChangeNotification:(id)arg1;
- (_Bool)_checkNowPlayingApplicationChanged;
- (void)mruApplications:(id)arg1 exitedBundleID:(id)arg2;
- (void)_setMRUBundleIDIfValid:(id)arg1;
- (void)mruApplications:(id)arg1 touchedBundleID:(id)arg2;
- (void)_rebuildAppSwitcherItemModel;
- (id)_validBundleIDs:(id)arg1 maximumCount:(int)arg2 passingTest:(CDUnknownBlockType)arg3;
- (void)_syncDefaultSettingsIfNecessary;
- (void)_readPreferences;
- (void)_registerDefaults;
- (void)saveFavoriteBundleIDs:(id)arg1;
- (_Bool)canAddFavorite;
- (void)_checkAppsStatsAvailable;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

