//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLFirstResponderEnabledViewController.h"

#import "CSLAppSwitcherItemModelObserver.h"
#import "CSLNavigableContainerProtocol.h"
#import "CSLPIButtonHandlerProtocol.h"
#import "CSLPageScrollViewDelegate.h"
#import "CSLSwitcherViewControllerProtocol.h"

@class CADisplayLink, CSLAppSwitcherDisplaySession, CSLPageScrollView, CSLSwitcherViewControllersFactory, FBUIApplicationSceneDeactivationAssertion, NSArray, NSMutableDictionary, NSMutableSet, NSOrderedSet, NSString, UIImage, UIImageView, UIViewController, UIViewController<CSLNavigableContainerProtocol>;

@interface CSLAppSwitcherViewController : CSLFirstResponderEnabledViewController <CSLPIButtonHandlerProtocol, CSLAppSwitcherItemModelObserver, CSLSwitcherViewControllerProtocol, CSLPageScrollViewDelegate, CSLNavigableContainerProtocol>
{
    CSLPageScrollView *_scrollView;
    NSOrderedSet *_pageViewControllers;
    NSMutableSet *_observers;
    NSMutableDictionary *_transitioningViewControllerIsAnimated;
    struct _NSRange _visibleRange;
    NSMutableDictionary *_cachedIconViews;
    NSArray *_viewControllersVisibleAcrossTransition;
    UIViewController<CSLNavigableContainerProtocol> *_transitioningViewController;
    CSLSwitcherViewControllersFactory *_viewFactory;
    float _animationTargetScale;
    unsigned int _animationTargetLayout;
    _Bool _animationIsInteractive;
    CDUnknownBlockType _animationCompletion;
    UIImageView *_backgroundImageView;
    NSString *_previousApplicationIdentifier;
    CADisplayLink *_pptPanDisplayLink;
    double _pptPanStartTime;
    float _pptPanStartPageOffset;
    int _pptPanCount;
    int _pptPageViewCount;
    NSString *_pptPanTestName;
    CSLAppSwitcherDisplaySession *_displaySession;
    FBUIApplicationSceneDeactivationAssertion *_sceneAssertion;
    UIImage *_backgroundImage;
}

@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(readonly, nonatomic) CSLPageScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)PPTPanAround:(id)arg1 panCount:(int)arg2;
- (void)updatePPT:(id)arg1;
- (void)appSwitcherItemModelDidChange:(id)arg1 removedItems:(id)arg2 addedItems:(id)arg3;
- (_Bool)containsVisibleViewController:(id)arg1;
- (void)beginDisappearingTransitionToViewController:(id)arg1 animated:(_Bool)arg2;
- (void)beginAppearingTransitionFromViewController:(id)arg1 animated:(_Bool)arg2;
- (_Bool)_pageViewControllerContainedByTransitioningViewController:(id)arg1;
- (float)visiblePercentageForViewControllerAtIndex:(unsigned int)arg1;
- (id)viewControllerAtIndex:(unsigned int)arg1;
@property(readonly, nonatomic) struct _NSRange visibleControllerRange;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)_completeAnimation:(unsigned int)arg1;
- (void)_unzoom:(id)arg1;
- (void)scrollViewDidReachLayout:(unsigned int)arg1;
- (void)scrollViewWasTapped:(id)arg1;
- (void)_wheelChangedWithEvent:(id)arg1;
- (_Bool)handleButton:(unsigned int)arg1 eventType:(unsigned int)arg2;
- (id)switcherItemForViewControllerAtIndex:(unsigned int)arg1;
- (id)pagedViewControllerAtIndex:(unsigned int)arg1;
- (void)updatePagedViewControllersForScrollView:(id)arg1 withRange:(struct _NSRange)arg2 settled:(_Bool)arg3;
- (id)_newFavoritesAddingIdentifier:(id)arg1 atIndex:(unsigned int)arg2 removingIndex:(unsigned int)arg3;
- (void)scrollViewLayoutPercentageChanged:(id)arg1 percentage:(float)arg2;
- (void)scrollViewDidDelete:(id)arg1 index:(unsigned int)arg2;
- (void)scrollViewDidAddToFavorites:(id)arg1 index:(unsigned int)arg2;
- (void)scrollViewDidReorder:(id)arg1 fromIndex:(unsigned int)arg2 toIndex:(unsigned int)arg3;
- (void)scrollViewDidFinishOffsetAnimation:(id)arg1;
- (void)scrollViewDidSettle:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1 scale:(float)arg2;
- (id)iconViewForPageAtIndex:(unsigned int)arg1;
- (id)cachedIconViewForBundleIdentifier:(id)arg1;
- (id)ephemeralTitleForPageAtIndex:(unsigned int)arg1;
- (id)titleForPageAtIndex:(unsigned int)arg1;
- (_Bool)shouldShowEphemeralTitleForPageAtIndex:(unsigned int)arg1;
- (_Bool)ephemeralPageAtIndex:(unsigned int)arg1;
- (_Bool)canAddPageAtIndex:(unsigned int)arg1;
- (_Bool)canReorderPageAtIndex:(unsigned int)arg1;
@property(retain, nonatomic) UIViewController *launcherViewController;
- (id)containerViewControllerForIdentifer:(id)arg1;
- (id)pageViewControllerWithIdentifier:(id)arg1;
- (_Bool)selectPageWithIdentifier:(id)arg1;
- (unsigned int)indexOfExistingPageWithIdentifier:(id)arg1;
- (id)centeredPageIdentifier;
@property(readonly, nonatomic) NSString *selectedIdentifer;
- (id)centeredViewControllerForScrollView:(id)arg1;
- (id)centeredViewController;
@property(readonly, nonatomic) unsigned int pageLayout;
- (void)setPageLayout:(unsigned int)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
@property(nonatomic, getter=isUserInteractionEnabled) _Bool userInteractionEnabled;
- (id)createViewControllers;
- (void)endAppearanceTransitionForViewController:(id)arg1 atIndex:(unsigned int)arg2;
- (void)beginAppearanceTransitionForViewController:(id)arg1 isAppearing:(_Bool)arg2 atIndex:(unsigned int)arg3 animated:(_Bool)arg4;
- (void)_disappearViewController:(id)arg1 animated:(_Bool)arg2 atIndex:(unsigned int)arg3 beginOnly:(_Bool)arg4;
- (void)disappearViewController:(id)arg1 animated:(_Bool)arg2 atIndex:(unsigned int)arg3;
- (void)willDisappearViewController:(id)arg1 animated:(_Bool)arg2 atIndex:(unsigned int)arg3;
- (void)_appearViewController:(id)arg1 animated:(_Bool)arg2 atIndex:(unsigned int)arg3 beginOnly:(_Bool)arg4;
- (void)appearViewController:(id)arg1 animated:(_Bool)arg2 atIndex:(unsigned int)arg3;
- (void)willAppearViewController:(id)arg1 animated:(_Bool)arg2 atIndex:(unsigned int)arg3;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setViewControllers:(id)arg1 selectingIdentifier:(id)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)viewDidLoad;
- (void)scrollToPage:(unsigned int)arg1;
- (void)removePageContentController:(id)arg1;
- (void)addPageContentController:(id)arg1;
- (struct CGRect)pageBounds;
- (unsigned int)numberOfPages;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
@property(readonly, nonatomic) NSArray *pagedViewControllers;
- (void)notifyObserversOfChange;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

