//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLActivityScheduleObserver.h"

@class CSLActivityBudget, CSLSchedulerActivityHistory, NSObject<OS_dispatch_queue>, NSString;

@interface CSLActivityBudgetManager : NSObject <CSLActivityScheduleObserver>
{
    NSObject<OS_dispatch_queue> *_queue;
    id <CSLActivityDateSource> _dateSource;
    CSLActivityBudget *_budget;
    CSLSchedulerActivityHistory *_history;
}

@property(readonly) CSLSchedulerActivityHistory *history; // @synthesize history=_history;
@property(readonly) CSLActivityBudget *budget; // @synthesize budget=_budget;
@property(retain) id <CSLActivityDateSource> dateSource; // @synthesize dateSource=_dateSource;
- (void).cxx_destruct;
- (void)performQuery:(CDUnknownBlockType)arg1;
- (void)activityScheduler:(id)arg1 didStartActivity:(id)arg2;
- (void)activityScheduler:(id)arg1 willRequestStartActivity:(id)arg2;
- (id)initWithBudget:(id)arg1 history:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

