//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSDate, NSString;

@interface CSLApplicationAction : NSObject <NSCopying>
{
    NSString *_bundleID;
    NSDate *_date;
    unsigned int _reason;
}

+ (id)applicationActionForBundleID:(id)arg1 date:(id)arg2;
@property(nonatomic) unsigned int reason; // @synthesize reason=_reason;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
- (void).cxx_destruct;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

