//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface CSLApplicationPrelaunchCounter : NSObject
{
    NSMutableDictionary *_prelaunchCounts;
}

- (void).cxx_destruct;
- (unsigned int)_lowestPrelaunchCount;
- (id)_bundleIDsWithPrelaunchCount:(unsigned int)arg1;
- (void)removeBundleIDsNotInSet:(id)arg1;
- (_Bool)hasPrelaunchCountForBundleID:(id)arg1;
- (void)addPrelaunchForBundleID:(id)arg1;
- (id)orderedBundleIDsForPrelaunch:(id)arg1;
- (id)findUnknownBundleIDsInSet:(id)arg1;
- (id)init;

@end

