//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BSTransactionObserver.h"

@class CSLAnimatedTransitioningTransaction;

@protocol CSLAnimatedTransitioningTransactionObserver <BSTransactionObserver>

@optional
- (void)animatorDidReceiveBeginAnimation:(CSLAnimatedTransitioningTransaction *)arg1;
@end

