//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "_DASActivityScheduler.h"

@class NSArray, NSHashTable, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, NSString;

@interface CSLActivityScheduler : NSObject <_DASActivityScheduler>
{
    NSObject<OS_dispatch_queue> *_queue;
    id <CSLActivityDateSource> _dateSource;
    id <CSLActivityTimerSource> _timerSource;
    NSArray *_policies;
    id <CSLSchedulerContext> _context;
    NSMutableSet *_submittedActivities;
    NSMutableSet *_runningActivities;
    NSMutableDictionary *_activityTimerMap;
    NSHashTable *_observers;
}

+ (id)defaultScheduler;
@property(readonly) NSHashTable *observers; // @synthesize observers=_observers;
@property(readonly, nonatomic) NSMutableDictionary *activityTimerMap; // @synthesize activityTimerMap=_activityTimerMap;
@property(readonly, nonatomic) NSMutableSet *runningActivities; // @synthesize runningActivities=_runningActivities;
@property(readonly, nonatomic) NSMutableSet *submittedActivities; // @synthesize submittedActivities=_submittedActivities;
@property(readonly, nonatomic) id <CSLSchedulerContext> context; // @synthesize context=_context;
@property(readonly, nonatomic) NSArray *policies; // @synthesize policies=_policies;
@property(readonly, nonatomic) id <CSLActivityTimerSource> timerSource; // @synthesize timerSource=_timerSource;
@property(readonly, nonatomic) id <CSLActivityDateSource> dateSource; // @synthesize dateSource=_dateSource;
@property(readonly) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)_queue_performLaunchActivity:(id)arg1;
- (void)_queue_cancelExistingTimersForActivity:(id)arg1;
- (void)_queue_performObserverBlock:(CDUnknownBlockType)arg1;
- (void)_queue_activityStarted:(id)arg1;
- (void)_queue_beginActivities:(id)arg1;
- (id)_queue_eligibleActivitiesAtDate:(id)arg1;
- (id)eligibleActivities;
- (id)policyResponseForActivity:(id)arg1;
- (void)_queue_evaluateActivitiesAtDate:(id)arg1;
- (void)_activityTimerFired:(id)arg1;
- (void)_scheduleTimersForActivity:(id)arg1;
- (void)activityCanceled:(id)arg1;
- (void)activityCompleted:(id)arg1;
- (void)submitActivities:(id)arg1;
- (void)submitActivity:(id)arg1;
- (void)handleEligibleActivities:(CDUnknownBlockType)arg1;
- (void)requestEvaluation;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)initWithConfiguration:(id)arg1;
- (void)activityStarted:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

