//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLActivityPolicyResponse, CSLActivityScheduler, NSDate, _DASActivity;

@protocol CSLActivityScheduleObserver <NSObject>
- (void)activityScheduler:(CSLActivityScheduler *)arg1 didStartActivity:(_DASActivity *)arg2;
- (void)activityScheduler:(CSLActivityScheduler *)arg1 willRequestStartActivity:(_DASActivity *)arg2;

@optional
- (void)activityScheduler:(CSLActivityScheduler *)arg1 didEvaluateActivity:(_DASActivity *)arg2 atDate:(NSDate *)arg3 withResponse:(CSLActivityPolicyResponse *)arg4;
@end

