//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IOSSHLTransaction.h"

#import "CSLIconZoomCoordination.h"

@class CSLIconZoomCoordinationContext, CSLNavigableContainerViewController, CSLUIApplicationIconViewHostViewAnimator, NSString;

@interface CSLAppIconZoomDownCoordinator : IOSSHLTransaction <CSLIconZoomCoordination>
{
    CSLIconZoomCoordinationContext *_context;
    CSLUIApplicationIconViewHostViewAnimator *_iconAnimator;
    CSLNavigableContainerViewController *_containerViewController;
    float _finalZoomLevel;
}

- (void).cxx_destruct;
- (id)bundleIdentifierForIcon;
@property(readonly, nonatomic) NSString *bundleIdentifier;
- (void)endZoomingAtZoomLevel:(float)arg1 withTransaction:(id)arg2 didChangeZoomLevels:(_Bool)arg3;
- (void)zoomLevelDidChange:(float)arg1 transaction:(id)arg2;
- (void)prepareToZoomWithContext:(id)arg1 transaction:(id)arg2;
- (void)_didComplete;
- (void)_begin;
- (void)dealloc;
- (id)initWithViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

