//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableOrderedSet, NSMutableSet, NSObject<OS_dispatch_queue>, NSOrderedSet, NSSet;

@interface CSLAppSwitcherItemModel : NSObject
{
    NSObject<OS_dispatch_queue> *_updateQueue;
    NSMutableOrderedSet *_items;
    NSMutableDictionary *_itemsByIdentifiers;
    NSMutableSet *_observers;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_withWriteLockSync:(CDUnknownBlockType)arg1;
- (void)_withReadLockSync:(CDUnknownBlockType)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (unsigned int)indexOfItem:(id)arg1;
- (id)nextItemToItem:(id)arg1;
- (id)nextItemToIdentifier:(id)arg1;
- (id)previousItemToItem:(id)arg1;
- (id)previousItemToIdentifier:(id)arg1;
- (void)replaceItem:(id)arg1 withUpdatedItem:(id)arg2;
- (id)itemWithIdentifier:(id)arg1;
@property(readonly, nonatomic) NSSet *identifiers;
@property(copy, nonatomic) NSOrderedSet *items;
- (id)init;

@end

