//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CSLAppSwitcherItemModel, NSOrderedSet;

@protocol CSLAppSwitcherItemModelObserver
- (void)appSwitcherItemModelDidChange:(CSLAppSwitcherItemModel *)arg1 removedItems:(NSOrderedSet *)arg2 addedItems:(NSOrderedSet *)arg3;
@end

