//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IOSSHLTransaction.h"

#import "BSTransactionObserver.h"
#import "CSLIconZoomCoordination.h"

@class CSLIconZoomCoordinationContext, CSLNavigableContainerViewController, CSLUIApplicationIconViewHostViewAnimator, CSLUIApplicationViewController, IOSSHLActivateAppTransaction, NSString;

@interface CSLAppIconZoomUpCoordinator : IOSSHLTransaction <BSTransactionObserver, CSLIconZoomCoordination>
{
    _Bool _launchFinished;
    _Bool _animationFinished;
    _Bool _failedToCreateActivationTransaction;
    CSLIconZoomCoordinationContext *_context;
    float _finalZoomLevel;
    CSLUIApplicationIconViewHostViewAnimator *_iconAnimator;
    CSLNavigableContainerViewController *_containerViewController;
    CSLUIApplicationViewController *_applicationViewController;
    IOSSHLActivateAppTransaction *_launchTransaction;
}

- (void).cxx_destruct;
- (void)transactionDidComplete:(id)arg1;
- (id)bundleIdentifierForIcon;
@property(readonly, nonatomic) NSString *bundleIdentifier;
- (void)cleanupAfterTxCompleted;
- (void)activateShellForFailedAppActivation;
- (void)handleAnimationAndLaunchFinishedAtZoomLevel:(float)arg1;
- (void)endZoomingAtZoomLevel:(float)arg1 withTransaction:(id)arg2 didChangeZoomLevels:(_Bool)arg3;
- (void)zoomLevelDidChange:(float)arg1 transaction:(id)arg2;
- (void)prepareToZoomWithContext:(id)arg1 transaction:(id)arg2;
- (void)_didComplete;
- (void)_begin;
- (void)dealloc;
- (id)initWithViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

