//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BLTBBAttachment, UIImage;

@interface CSLBulletinAttachment : NSObject
{
    BLTBBAttachment *_attachment;
    UIImage *_imageAttachment;
}

+ (id)bulletinAttachmentWithImage:(id)arg1;
+ (id)bulletinAttachmentWithData:(id)arg1;
@property(retain, nonatomic) UIImage *imageAttachment; // @synthesize imageAttachment=_imageAttachment;
@property(retain, nonatomic) BLTBBAttachment *attachment; // @synthesize attachment=_attachment;
- (void).cxx_destruct;

@end

