//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLBulletin;

@interface CSLBulletinHolder : NSObject
{
    _Bool _shouldPlayLightsAndSirens;
    CSLBulletin *_bulletin;
}

@property(nonatomic) _Bool shouldPlayLightsAndSirens; // @synthesize shouldPlayLightsAndSirens=_shouldPlayLightsAndSirens;
@property(retain, nonatomic) CSLBulletin *bulletin; // @synthesize bulletin=_bulletin;
- (void).cxx_destruct;
- (id)description;
- (id)initWithBulletin:(id)arg1 playLightsAndSirens:(_Bool)arg2;

@end

