//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class CSLBulletin, NSDate, NSString;

@interface CSLBulletinDeduplicatorItem : NSObject <NSCopying>
{
    _Bool _shouldPlayLightsAndSirens;
    _Bool _hasFiredLocal;
    _Bool _hasFiredMirrored;
    _Bool _hasWithdrawnLocal;
    _Bool _hasWithdrawnMirrored;
    _Bool _OKToFire;
    CSLBulletin *_localBulletin;
    CSLBulletin *_mirroredBulletin;
    NSString *_universalSectionID;
    NSString *_publisherMatchID;
    unsigned int _feed;
    NSDate *_autoFireDate;
    NSDate *_createdDate;
}

@property(nonatomic) _Bool OKToFire; // @synthesize OKToFire=_OKToFire;
@property(readonly, copy, nonatomic) NSDate *createdDate; // @synthesize createdDate=_createdDate;
@property(nonatomic) _Bool hasWithdrawnMirrored; // @synthesize hasWithdrawnMirrored=_hasWithdrawnMirrored;
@property(nonatomic) _Bool hasWithdrawnLocal; // @synthesize hasWithdrawnLocal=_hasWithdrawnLocal;
@property(nonatomic) _Bool hasFiredMirrored; // @synthesize hasFiredMirrored=_hasFiredMirrored;
@property(nonatomic) _Bool hasFiredLocal; // @synthesize hasFiredLocal=_hasFiredLocal;
@property(copy, nonatomic) NSDate *autoFireDate; // @synthesize autoFireDate=_autoFireDate;
@property(readonly, nonatomic) _Bool shouldPlayLightsAndSirens; // @synthesize shouldPlayLightsAndSirens=_shouldPlayLightsAndSirens;
@property(nonatomic) unsigned int feed; // @synthesize feed=_feed;
@property(copy, nonatomic) NSString *publisherMatchID; // @synthesize publisherMatchID=_publisherMatchID;
@property(copy, nonatomic) NSString *universalSectionID; // @synthesize universalSectionID=_universalSectionID;
@property(retain, nonatomic) CSLBulletin *mirroredBulletin; // @synthesize mirroredBulletin=_mirroredBulletin;
@property(retain, nonatomic) CSLBulletin *localBulletin; // @synthesize localBulletin=_localBulletin;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) NSDate *expiryDate;
- (id)init;

@end

