//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLSBackgroundTaskRequestServiceXPC.h"
#import "NSXPCListenerDelegate.h"

@class CSLBackgroundService, CSLClientConnections, NSString, NSXPCListener;

@interface CSLBackgroundTaskRequestServiceEndpoint : NSObject <NSXPCListenerDelegate, CSLSBackgroundTaskRequestServiceXPC>
{
    CSLBackgroundService *_backgroundService;
    NSXPCListener *_listener;
    CSLClientConnections *_clients;
}

+ (id)sharedInstance;
@property(retain, nonatomic) CSLClientConnections *clients; // @synthesize clients=_clients;
@property(retain, nonatomic) NSXPCListener *listener; // @synthesize listener=_listener;
@property(nonatomic) __weak CSLBackgroundService *backgroundService; // @synthesize backgroundService=_backgroundService;
- (void).cxx_destruct;
- (void)connect;
- (void)cancelBackgroundTaskRequestForBundleID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)cancelBackgroundTaskRequestForBundleID:(id)arg1;
- (void)submitBackgroundTaskRequest:(id)arg1 forBundleID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)submitBackgroundTaskRequest:(id)arg1 forBundleID:(id)arg2;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)resume;
- (id)_init;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

