//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLKComplicationWakeSessionObserver.h"
#import "CSLBackgroundActivityControllerDelegate.h"
#import "CSLBackgroundTaskRequestService.h"
#import "CSLDuetBackgroundBudgetControllerDelegate.h"
#import "CSLPrelaunchManagerObserver.h"

@class CSLBackgroundActivityManagerConfiguration, CSLBackgroundService, CSLBackgroundUpdatePolicy, CSLDuetBackgroundBudgetController, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, NSString;

@interface CSLBackgroundActivityManager : NSObject <CSLBackgroundActivityControllerDelegate, CSLDuetBackgroundBudgetControllerDelegate, CSLPrelaunchManagerObserver, CSLBackgroundTaskRequestService, CLKComplicationWakeSessionObserver>
{
    _Bool _prelaunching;
    CSLBackgroundService *_backgroundService;
    CSLBackgroundActivityManagerConfiguration *_configuration;
    NSMutableDictionary *_controllerMap;
    NSMutableSet *_activeComplicationWakeSessions;
}

@property(readonly, nonatomic) _Bool prelaunching; // @synthesize prelaunching=_prelaunching;
@property(retain, nonatomic) NSMutableSet *activeComplicationWakeSessions; // @synthesize activeComplicationWakeSessions=_activeComplicationWakeSessions;
@property(retain, nonatomic) NSMutableDictionary *controllerMap; // @synthesize controllerMap=_controllerMap;
@property(retain, nonatomic) CSLBackgroundActivityManagerConfiguration *configuration; // @synthesize configuration=_configuration;
@property(nonatomic) __weak CSLBackgroundService *backgroundService; // @synthesize backgroundService=_backgroundService;
- (void).cxx_destruct;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)_queue_getRequestsWithCompletion:(CDUnknownBlockType)arg1;
- (void)getRequestsWithCompletion:(CDUnknownBlockType)arg1;
- (void)complicationWillEndWakeSessionForBundleIdentifier:(id)arg1;
- (void)complicationWillBeginWakeSessionForBundleIdentifier:(id)arg1;
- (_Bool)controllerShouldCreatePriorityActivity:(id)arg1;
- (void)priorityBundleIDsAdded:(id)arg1 removed:(id)arg2;
- (void)prelaunchManagerCompletedPrelaunching:(id)arg1;
- (void)prelaunchManagerStartedPrelaunching:(id)arg1;
- (void)_queue_priorityBundleIDsRemoved:(id)arg1;
- (void)_queue_priorityBundleIDsAdded:(id)arg1;
- (void)_queue_endActiveComplicationWakeSessionForBundleID:(id)arg1;
- (void)_queue_beginActiveComplicationWakeSessionForBundleID:(id)arg1;
- (_Bool)_queue_hasActiveComplicationWakeSessionForBundleID:(id)arg1;
- (id)_queue_existingActivityControllerForBundleID:(id)arg1;
- (id)_queue_existingOrNewActivityControllerForBundleID:(id)arg1;
- (id)userStringForBundleID:(id)arg1;
- (void)cancelBackgroundTaskRequestForBundleID:(id)arg1;
- (void)setBackgroundTaskRequest:(id)arg1 forBundleID:(id)arg2;
- (id)prelaunchManager;
@property(readonly, nonatomic) CSLDuetBackgroundBudgetController *budgetController;
@property(readonly, nonatomic) CSLBackgroundUpdatePolicy *backgroundUpdatePolicy;
@property(readonly, nonatomic) id <_DASActivityScheduler> scheduler;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
- (id)initWithConfiguration:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

