//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CSLBulletin, CSLBulletinAlertItem, CSLBulletinQueue, NSArray;

@protocol CSLBulletinQueueDequeueDelegate
- (CSLBulletinAlertItem *)createItemForQueue:(CSLBulletinQueue *)arg1 seedBulletin:(CSLBulletin *)arg2 additionalBulletins:(NSArray *)arg3 playLightsAndSirens:(_Bool)arg4 didCoalesce:(_Bool *)arg5;
- (void)scheduleDequeueFromQueue:(CSLBulletinQueue *)arg1;
@end

