//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLSBulletinServiceServerExportedInterface.h"
#import "NSXPCListenerDelegate.h"

@class NSMutableArray, NSString, NSXPCListener;

@interface CSLBulletinXPCServer : NSObject <NSXPCListenerDelegate, CSLSBulletinServiceServerExportedInterface>
{
    id <CSLBulletinXPCServerDelegate> _delegate;
    NSMutableArray *_clientConnections;
    NSXPCListener *_listener;
}

@property(retain, nonatomic) NSXPCListener *listener; // @synthesize listener=_listener;
@property(retain, nonatomic) NSMutableArray *clientConnections; // @synthesize clientConnections=_clientConnections;
@property(nonatomic) __weak id <CSLBulletinXPCServerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)clearAllBulletinsWithCompletion:(CDUnknownBlockType)arg1;
- (void)clearBulletinWithSectionID:(id)arg1 publisherMatchID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)removeBulletinWithSectionID:(id)arg1 publisherMatchID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)getLockedBulletinsInPipelineStepActorWithClassName:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addBulletinWithTitle:(id)arg1 subtitle:(id)arg2 message:(id)arg3 delayLocal:(unsigned int)arg4 delayMirrored:(unsigned int)arg5 completion:(CDUnknownBlockType)arg6;
- (void)_removeClientConnection:(id)arg1;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

