//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IOSSHLBacklightObserver.h"

@class NSNumber, NSString;

@interface CSLBacklightLogManager : NSObject <IOSSHLBacklightObserver>
{
    double _lastBacklightOnTime;
    NSNumber *_lastBacklightOnReason;
    double _lastBulletinTime;
    _Bool _logBulletin;
    NSString *_lastBulletinSectionID;
}

+ (void)initialize;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)_durationKeyForReason:(id)arg1;
- (id)_countKeyForReason:(id)arg1;
- (void)_logBacklightOnDuration:(double)arg1 reason:(id)arg2;
- (void)_logBacklightOffForReason:(unsigned int)arg1;
- (void)_logBacklightOnForReason:(unsigned int)arg1;
- (void)backlight:(id)arg1 willBeOn:(_Bool)arg2 forReason:(unsigned int)arg3;
- (void)backlight:(id)arg1 didTurnOn:(_Bool)arg2 forReason:(unsigned int)arg3;
- (void)_noteBulletinDidPlaySound:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

