//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLObserverSet, NSObject<OS_dispatch_queue>;

@interface CSLBackgroundUpdatePolicy : NSObject
{
    _Bool _allowsUpdates;
    CSLObserverSet *_observerSet;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)defaultBackgroundUpdatePolicy;
+ (void)initialize;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) CSLObserverSet *observerSet; // @synthesize observerSet=_observerSet;
@property _Bool allowsUpdates; // @synthesize allowsUpdates=_allowsUpdates;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_setAllowsUpdates:(_Bool)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)dealloc;
- (id)init;

@end

