//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLBulletinPipelineStepActorDelegate.h"

@class NSCountedSet, NSDate, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface CSLBulletinPipelineStep : NSObject <CSLBulletinPipelineStepActorDelegate>
{
    NSCountedSet *_lockedBulletins;
    NSMutableDictionary *_observedBulletins;
    NSMutableArray *_pendingActionQueue;
    NSMutableDictionary *_processedActionQueue;
    NSMutableDictionary *_currentActions;
    _Bool _isActorBusy;
    CSLBulletinPipelineStep *_nextStep;
    id <CSLBulletinPipelineStepActor> _actor;
    id <CSLBulletinStateStoreProtocol> _stateStore;
    NSObject<OS_dispatch_queue> *_queue;
}

- (void).cxx_destruct;
- (_Bool)_actorWantsBulletin:(id)arg1 feed:(unsigned int)arg2;
- (void)_removeObservedBulletin:(id)arg1 feed:(unsigned int)arg2;
- (void)_updateBulletinInDictionary:(id)arg1 withBulletin:(id)arg2 feed:(unsigned int)arg3;
- (void)_cancelBulletin:(id)arg1;
- (void)_sendBulletinToNextStep:(id)arg1;
- (void)_endProcessingBulletin:(id)arg1;
- (void)_completeCurrentActionWithBulletin:(id)arg1;
- (void)_isBulletinValid:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_dequeueAndPerformNextAction;
- (void)_enqueueActionWithBulletin:(id)arg1 oldBulletin:(id)arg2 feed:(unsigned int)arg3 actionType:(unsigned int)arg4;
- (void)_unlockBulletin:(id)arg1;
- (void)_lockBulletin:(id)arg1;
- (void)actor:(id)arg1 isBusy:(_Bool)arg2;
- (void)actor:(id)arg1 willManageStateForBulletins:(id)arg2 withBlock:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (void)actor:(id)arg1 willManageStateForBulletin:(id)arg2 withBlock:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (void)actor:(id)arg1 unlockBulletin:(id)arg2;
- (void)actor:(id)arg1 lockBulletin:(id)arg2;
- (void)forgetBulletinsBeforeDate:(id)arg1 includeNonClearable:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)invalidateBulletinIDs:(id)arg1;
- (void)sectionParametersChangedForSectionID:(id)arg1;
- (void)removeBulletin:(id)arg1 feed:(unsigned int)arg2;
- (void)modifyBulletin:(id)arg1 feed:(unsigned int)arg2;
- (void)addBulletin:(id)arg1 replaceBulletin:(id)arg2 feed:(unsigned int)arg3;
- (void)addBulletin:(id)arg1 feed:(unsigned int)arg2;
- (id)lockedBulletinsInPiplineStepActorWithClassName:(id)arg1;
- (id)observedBulletins;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSDate *earliestBulletinDate;
- (id)initWithActor:(id)arg1 nextStep:(id)arg2 queue:(id)arg3 stateStore:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

