//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BBDataProviderConnection, BLTBulletinDistributorClient, CSLBulletinDistributorSystemStateProvider, NSObject<OS_dispatch_queue>;

@interface CSLBulletinBoardServer : NSObject
{
    CSLBulletinDistributorSystemStateProvider *_bulletinDistributorSystemStateProvider;
    BBDataProviderConnection *_bulletinBoardConnection;
    NSObject<OS_dispatch_queue> *_bulletinBoardQueue;
    BLTBulletinDistributorClient *_bulletinDistributorClient;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) BLTBulletinDistributorClient *bulletinDistributorClient; // @synthesize bulletinDistributorClient=_bulletinDistributorClient;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *bulletinBoardQueue; // @synthesize bulletinBoardQueue=_bulletinBoardQueue;
@property(readonly, nonatomic) BBDataProviderConnection *bulletinBoardConnection; // @synthesize bulletinBoardConnection=_bulletinBoardConnection;
- (void).cxx_destruct;
- (void)start;
- (void)prepare;

@end

