//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface CSLBulletinState : NSObject <NSCopying>
{
    _Bool _isCancelled;
    _Bool _isCleared;
    _Bool _isRead;
    _Bool _isWithdrawn;
    _Bool _didAlert;
    _Bool _shouldAlert;
    _Bool _didEnterNotificationList;
    unsigned int _keepAliveCount;
}

@property(nonatomic) unsigned int keepAliveCount; // @synthesize keepAliveCount=_keepAliveCount;
@property(nonatomic) _Bool didEnterNotificationList; // @synthesize didEnterNotificationList=_didEnterNotificationList;
@property(nonatomic) _Bool shouldAlert; // @synthesize shouldAlert=_shouldAlert;
@property(nonatomic) _Bool didAlert; // @synthesize didAlert=_didAlert;
@property(nonatomic) _Bool isWithdrawn; // @synthesize isWithdrawn=_isWithdrawn;
@property(nonatomic) _Bool isRead; // @synthesize isRead=_isRead;
@property(nonatomic) _Bool isCleared; // @synthesize isCleared=_isCleared;
@property(nonatomic) _Bool isCancelled; // @synthesize isCancelled=_isCancelled;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

