//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BBBulletin, BLTBBAttachment, CSLBulletinKey, NSDate, NSSet, NSString, UNNotification;

@interface CSLBulletin : NSObject
{
    BBBulletin *_bulletin;
    UNNotification *_notification;
    CSLBulletinKey *_bulletinKey;
    _Bool _soundEnabled;
    BLTBBAttachment *_attachment;
}

+ (id)bulletinWithBulletin:(id)arg1;
@property(nonatomic) _Bool soundEnabled; // @synthesize soundEnabled=_soundEnabled;
@property(retain, nonatomic) BLTBBAttachment *attachment; // @synthesize attachment=_attachment;
@property(readonly, nonatomic) BBBulletin *bulletin; // @synthesize bulletin=_bulletin;
- (void).cxx_destruct;
- (_Bool)shouldCoalesceWithBulletin:(id)arg1;
@property(readonly, nonatomic) CSLBulletinKey *bulletinKey;
@property(readonly, nonatomic) NSString *mirroredSectionID;
@property(readonly, nonatomic) NSString *gizmoUniversalSectionID;
@property(readonly, nonatomic) NSString *localSectionID;
@property(readonly, nonatomic) UNNotification *notification;
@property(readonly, nonatomic) _Bool turnsOnDisplay;
@property(readonly, nonatomic) NSString *appName;
@property(readonly, nonatomic) NSDate *publishDate;
@property(readonly, nonatomic) NSDate *dateOrRecencyDate;
@property(readonly, nonatomic) NSSet *alertSuppressionContexts;
@property(readonly, nonatomic) _Bool suppressesAlertsWhenAppIsActive;
@property(readonly, nonatomic) _Bool playsSoundForModify;
@property(readonly, nonatomic) _Bool clearable;
- (id)description;
@property(readonly, nonatomic) NSDate *date;
@property(readonly, nonatomic) NSString *subtitle;
@property(readonly, nonatomic) NSString *message;
@property(readonly, nonatomic) NSString *title;
@property(readonly, nonatomic) int sectionSubtype;
@property(readonly, nonatomic) NSString *sectionMatchID;
@property(readonly, nonatomic) NSString *publisherMatchID;
@property(readonly, nonatomic) NSString *recordID;
@property(readonly, nonatomic) NSString *bulletinID;
@property(readonly, nonatomic) NSSet *subsectionIDs;
@property(readonly, nonatomic) NSString *sectionID;
- (id)initWithBulletin:(id)arg1;
- (id)initWithBulletin:(id)arg1 attachment:(id)arg2 soundEnabled:(_Bool)arg3;

@end

