//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IOSSHLButtonKeyStateDelegate.h"

@class IOSSHLButtonKeyState, NSNumber, NSString;

@interface CSLButton : NSObject <IOSSHLButtonKeyStateDelegate>
{
    _Bool _turnsOnBacklight;
    _Bool _shouldPowerlog;
    IOSSHLButtonKeyState *_buttonKeyState;
    unsigned int _buttonMask;
    NSNumber *_backlightReason;
    NSString *_aggdLogName;
    id <CSLButtonDelegate> _delegate;
    CSLButton *_chordedButton;
}

+ (id)buttonWithUsagePage:(long)arg1 usage:(long)arg2 buttonMask:(unsigned int)arg3 backlightReason:(unsigned int)arg4 aggdLogName:(id)arg5 delegate:(id)arg6;
@property(retain, nonatomic) CSLButton *chordedButton; // @synthesize chordedButton=_chordedButton;
@property(nonatomic) id <CSLButtonDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSString *aggdLogName; // @synthesize aggdLogName=_aggdLogName;
@property(readonly, nonatomic) NSNumber *backlightReason; // @synthesize backlightReason=_backlightReason;
@property(readonly, nonatomic) _Bool shouldPowerlog; // @synthesize shouldPowerlog=_shouldPowerlog;
@property(readonly, nonatomic) _Bool turnsOnBacklight; // @synthesize turnsOnBacklight=_turnsOnBacklight;
@property(readonly, nonatomic) unsigned int buttonMask; // @synthesize buttonMask=_buttonMask;
@property(readonly, nonatomic) IOSSHLButtonKeyState *buttonKeyState; // @synthesize buttonKeyState=_buttonKeyState;
- (void).cxx_destruct;
- (void)buttonTapped:(id)arg1;
- (void)buttonHeldAndReleased:(id)arg1;
- (void)buttonHeld:(id)arg1 state:(int)arg2;
- (id)aggdLogMessageForAction:(unsigned int)arg1;
- (id)initWithButtonKeyState:(id)arg1 buttonMask:(unsigned int)arg2 backlightReason:(unsigned int)arg3 aggdLogName:(id)arg4 delegate:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

