//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLBackgroundTaskRequestService.h"

@class CLKComplicationObserver, CSLBackgroundActivityManager, CSLBackgroundServiceConfiguration, CSLBackgroundTaskRequestServiceEndpoint, NSString;

@interface CSLBackgroundService : NSObject <CSLBackgroundTaskRequestService>
{
    CSLBackgroundServiceConfiguration *_configuration;
}

+ (id)sharedInstance;
@property(retain, nonatomic) CSLBackgroundServiceConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (id)userStringForBundleID:(id)arg1;
- (void)cancelBackgroundTaskRequestForBundleID:(id)arg1;
- (void)setBackgroundTaskRequest:(id)arg1 forBundleID:(id)arg2;
@property(readonly, nonatomic) CLKComplicationObserver *complicationObserver;
@property(readonly, nonatomic) CSLBackgroundActivityManager *activityManager;
@property(readonly, nonatomic) CSLBackgroundTaskRequestServiceEndpoint *endpoint;
- (id)initWithConfiguration:(id)arg1;
- (id)init;
- (void)getRequestsWithCallbackQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

