//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLBulletinPipelineStepActor.h"
#import "CSLBulletinPresenterDelegate.h"
#import "CSLBulletinQueueDequeueDelegate.h"
#import "CSLBulletinUIBuilderDelegate.h"
#import "CSLDNDSource.h"
#import "CSLNotificationCenterViewControllerAlertDelegate.h"
#import "CUISAlertProvider.h"

@class BBObserver, CSLAppPrelauncher, CSLBulletinQueue, CUISAlertViewController<CSLBulletinPresenter>, NSDate, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, NSTimer;

@interface CSLBulletinAlertProvider : NSObject <CSLBulletinPresenterDelegate, CSLBulletinQueueDequeueDelegate, CSLDNDSource, CUISAlertProvider, CSLNotificationCenterViewControllerAlertDelegate, CSLBulletinUIBuilderDelegate, CSLBulletinPipelineStepActor>
{
    CUISAlertViewController<CSLBulletinPresenter> *_pendingController;
    NSTimer *_uiUpdateTimer;
    NSMutableDictionary *_realertTimers;
    NSDate *_lastAlertSoundDate;
    CSLAppPrelauncher *_prelauncher;
    NSMutableDictionary *_replacementBulletinsByOldBulletinKey;
    NSMutableDictionary *_replacementBulletinsByReplacementBulletinKey;
    _Bool _enabled;
    id <CUISAlertProviderDelegate> alertProviderDelegate;
    id <CSLBulletinPipelineStepActorDelegate> _pipelineStep;
    NSObject<OS_dispatch_queue> *_pipelineQueue;
    BBObserver *_pipelineObserver;
    CUISAlertViewController<CSLBulletinPresenter> *_activeController;
    CSLBulletinQueue *_queue;
}

+ (void)_playBBSoundForBulletin:(id)arg1;
+ (id)_realertTimerKeyForBulletin:(id)arg1;
+ (id)sharedAlertProvider;
@property(retain, nonatomic) CSLBulletinQueue *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) CUISAlertViewController<CSLBulletinPresenter> *activeController; // @synthesize activeController=_activeController;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) BBObserver *pipelineObserver; // @synthesize pipelineObserver=_pipelineObserver;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *pipelineQueue; // @synthesize pipelineQueue=_pipelineQueue;
@property(nonatomic) __weak id <CSLBulletinPipelineStepActorDelegate> pipelineStep; // @synthesize pipelineStep=_pipelineStep;
@property(nonatomic) __weak id <CUISAlertProviderDelegate> alertProviderDelegate; // @synthesize alertProviderDelegate;
- (void).cxx_destruct;
- (void)_enumerateBulletinsForAlertItem:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)_enumerateBulletinsOrReplacementsForAlertItem:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)_markBulletinsAsClearedForBulletinAlertItem:(id)arg1;
- (void)_markBulletinsAsAlertedForBulletinAlertItem:(id)arg1;
- (void)_unlockAlertItem:(id)arg1 reason:(id)arg2;
- (void)_unlockBulletinOrReplacement:(id)arg1;
- (void)_modifyReplacementForBulletin:(id)arg1;
- (void)_rememberReplacementForBulletin:(id)arg1 oldBulletin:(id)arg2;
- (void)_forgetReplacementForBulletin:(id)arg1;
- (void)addBulletin:(id)arg1 replaceBulletin:(id)arg2 feed:(unsigned int)arg3 completion:(CDUnknownBlockType)arg4;
- (void)addBulletin:(id)arg1 feed:(unsigned int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)invalidateBulletinIDs:(id)arg1;
- (void)modifyBulletin:(id)arg1 feed:(unsigned int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)removeBulletin:(id)arg1 feed:(unsigned int)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) unsigned int observedFeeds;
- (void)_bulletinSoundDidPlay:(id)arg1;
- (_Bool)shouldDNDGestureRecognize;
- (void)notificationCenterViewController:(id)arg1 activateAlertForBulletin:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)createItemForQueue:(id)arg1 seedBulletin:(id)arg2 additionalBulletins:(id)arg3 playLightsAndSirens:(_Bool)arg4 didCoalesce:(_Bool *)arg5;
- (id)_attachmentFromBulletin:(id)arg1;
- (_Bool)_coalesceWithItem:(id)arg1 seedBulletin:(id)arg2 additionalBulletins:(id)arg3 playLightsAndSirens:(_Bool)arg4;
- (void)scheduleDequeueFromQueue:(id)arg1;
- (void)getIconForBulletin:(id)arg1 shape:(unsigned int)arg2 size:(unsigned int)arg3 completion:(CDUnknownBlockType)arg4;
- (void)scheduleSnapshotForBulletinPresenter:(id)arg1;
- (unsigned int)audioFeedbackAllowedForBulletinPresenter:(id)arg1;
- (id)_launchAppForBulletinPresenter:(id)arg1;
- (id)_defaultAppForBulletinPresenter:(id)arg1;
- (void)requestLaunchAppSuspendedWithBulletinPresenter:(id)arg1;
- (_Bool)_launchAppFromBulletin:(id)arg1 andAction:(id)arg2 forBulletinView:(id)arg3;
- (void)bulletinPresenter:(id)arg1 requestLaunchApp:(id)arg2 withURL:(id)arg3 annotation:(id)arg4;
- (void)didPerformActionWithBulletinPresenter:(id)arg1;
- (void)bulletinPresenter:(id)arg1 requestHandleActionType:(int)arg2;
- (void)bulletinPresenter:(id)arg1 requestDismissAnimated:(_Bool)arg2;
- (void)_clearAlertItem:(id)arg1;
- (void)_bulletinPresenter:(id)arg1 requestedSnoozeAction:(id)arg2;
- (void)_bulletinPresenter:(id)arg1 requestedDismissAction:(id)arg2;
- (void)_bulletinPresenter:(id)arg1 requestedDefaultAction:(id)arg2;
- (void)_bulletinPresenter:(id)arg1 requestedAcknowledgeAction:(id)arg2;
- (void)didPresentLongLookWithBulletinPresenter:(id)arg1;
- (void)bulletinPresenter:(id)arg1 didAutoDismissWhenAlertHasDisplayed:(_Bool)arg2;
- (void)didDeactivateBulletinPresenter:(id)arg1;
- (void)_coalesceActiveAlertWithBulletin:(id)arg1;
- (_Bool)_shouldCoalesceWithActiveBulletin:(id)arg1;
- (_Bool)_isBulletinPendingOrActive:(id)arg1;
- (void)_deactivateBulletinAlert:(id)arg1 launchApp:(id)arg2 withURL:(id)arg3 annotation:(id)arg4 animated:(_Bool)arg5;
- (void)_deactivateBulletinAlert:(id)arg1 animated:(_Bool)arg2;
- (void)_deactivateBulletinAlert:(id)arg1 deactivateBlock:(CDUnknownBlockType)arg2;
- (_Bool)_activateBulletinAlertIfPossible:(id)arg1;
- (void)_buildAndTryActivateBulletin:(id)arg1;
- (id)_itemWithUpdatedAttachmentOfItem:(id)arg1;
- (void)_cancelUpdateUITimerAndPurgeQueue;
- (void)_handleBacklightDidTurnOff:(id)arg1;
- (void)_discardPendingControllerWithReason:(id)arg1;
- (void)_alertManagerDidClearPendingAlerts:(id)arg1;
- (id)copyOfItem:(id)arg1 withReplacementBulletin:(id)arg2;
- (_Bool)playSoundIfPossibleForAlertItem:(id)arg1 alertController:(id)arg2;
- (_Bool)shouldPlaySoundForAlertItem:(id)arg1;
- (void)_updateUI;
- (void)_scheduleUIUpdate;
- (void)_scheduleRealerts:(id)arg1;
- (void)_cancelTimersInSet:(id)arg1;
- (void)_cancelRealertingIfNeededWithBulletin:(id)arg1;
- (void)_killRealertsForBulletinIDs:(id)arg1;
- (void)_killRealertsForBulletin:(id)arg1;
- (void)_killAllRealerts;
- (void)_realertTimerFired:(id)arg1;
- (_Bool)_sendToAppOrSuppressAlertIfNeededForBulletin:(id)arg1;
- (_Bool)_sendNotification:(id)arg1 toTopApp:(id)arg2;
- (void)_alertEnabledBySectionInfoForBulletin:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, copy) NSString *description;
- (void)_powerLogPresentationForBulletin:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

