//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLBulletinKey, CSLBulletinState, NSDate, NSString;

@interface CSLBulletinStatePersistentStoreItem : NSObject
{
    _Bool _isClearable;
    CSLBulletinKey *_bulletinKey;
    NSString *_universalSectionID;
    NSString *_publisherMatchID;
    NSDate *_publicationDate;
    CSLBulletinState *_state;
}

+ (id)itemWithBulletin:(id)arg1;
@property(retain, nonatomic) CSLBulletinState *state; // @synthesize state=_state;
@property(nonatomic) _Bool isClearable; // @synthesize isClearable=_isClearable;
@property(copy, nonatomic) NSDate *publicationDate; // @synthesize publicationDate=_publicationDate;
@property(copy, nonatomic) NSString *publisherMatchID; // @synthesize publisherMatchID=_publisherMatchID;
@property(copy, nonatomic) NSString *universalSectionID; // @synthesize universalSectionID=_universalSectionID;
@property(retain, nonatomic) CSLBulletinKey *bulletinKey; // @synthesize bulletinKey=_bulletinKey;
- (void).cxx_destruct;
- (id)init;

@end

