//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BBObserver, CSLBulletinPipelineStep, CSLPITimer, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface CSLBulletinDeduplicator : NSObject
{
    NSMutableDictionary *_bulletinItems;
    NSMutableArray *_autofireQueue;
    CSLPITimer *_autoFireTimer;
    CSLBulletinPipelineStep *_pipeline;
    id <CSLBulletinStateStoreProtocol> _stateStore;
    BBObserver *_observer;
    NSObject<OS_dispatch_queue> *_queue;
    CDUnknownBlockType _fireBulletin;
}

@property(copy, nonatomic) CDUnknownBlockType fireBulletin; // @synthesize fireBulletin=_fireBulletin;
- (void).cxx_destruct;
- (void)_purgeExpiredBulletins;
- (id)_itemForBulletin:(id)arg1 feed:(unsigned int)arg2;
- (void)_invalidateAutoFireTimer;
- (void)_handleAutoFireTimer;
- (void)_startAutoFireTimer;
- (void)_enqueueItemInAutoFireQueue:(id)arg1;
- (_Bool)_isItemInAutoFireQueue:(id)arg1;
- (void)_removeItemFromAutofireQueue:(id)arg1;
- (void)_firePendingItems;
- (void)_handleOnWristStateChanged:(id)arg1;
- (id)_bulletinKeyForBulletin:(id)arg1;
- (id)_existingItemForBulletin:(id)arg1;
- (void)_fireItem:(id)arg1;
- (void)reset;
- (_Bool)hasBulletinWithMatchID:(id)arg1 sectionID:(id)arg2;
- (void)invalidateBulletinIDs:(id)arg1;
- (void)sectionParametersChangedForSectionID:(id)arg1;
- (void)forgetBulletinsBeforeDate:(id)arg1 includeNonClearable:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)removeBulletin:(id)arg1 feed:(unsigned int)arg2;
- (void)modifyBulletin:(id)arg1 feed:(unsigned int)arg2;
- (void)addBulletin:(id)arg1 feed:(unsigned int)arg2;
- (void)_createStateForItem:(id)arg1 triggeredbyBulletin:(id)arg2 keepAliveCount:(unsigned int)arg3 completion:(CDUnknownBlockType)arg4;
- (void)dealloc;
- (id)initWithQueue:(id)arg1 observer:(id)arg2 pipeline:(id)arg3 stateStore:(id)arg4;

@end

