//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBSceneManagerObserver.h"

@class BKSEventFocusDeferralProperties, NSMutableArray, NSString;

@interface CSLCarouselEventFocusManager : NSObject <FBSceneManagerObserver>
{
    BKSEventFocusDeferralProperties *_carouselProperties;
    NSMutableArray *_focusAssertions;
    NSMutableArray *_carouselAssertions;
    NSString *_focusedAppBundleID;
    int _focusedAppPID;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)sceneManager:(id)arg1 didDestroyScene:(id)arg2;
- (void)sceneManager:(id)arg1 willDestroyScene:(id)arg2;
- (void)sceneManager:(id)arg1 didCommitUpdateForScene:(id)arg2 transactionID:(unsigned int)arg3 success:(_Bool)arg4;
- (void)sceneManager:(id)arg1 willCommitUpdateForScene:(id)arg2 transactionID:(unsigned int)arg3;
- (void)sceneManager:(id)arg1 willUpdateScene:(id)arg2 withSettings:(id)arg3 transitionContext:(id)arg4;
- (void)sceneManager:(id)arg1 didCreateScene:(id)arg2 withClient:(id)arg3;
- (void)updateFocus;
- (id)activeScenesWithIdentifiers:(id)arg1;
- (void)removeEventFocusManagerCarouselAssertion:(id)arg1;
- (void)addEventFocusManagerCarouselAssertion:(id)arg1;
- (void)removeEventFocusManagerAssertion:(id)arg1;
- (void)addEventFocusManagerAssertion:(id)arg1;
- (void)clearDeferrals;
- (void)sendEventsToBundleID:(id)arg1 pid:(int)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

