//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "APSConnectionDelegate.h"
#import "IDSServiceDelegate.h"
#import "RadiosPreferencesDelegate.h"

@class APSConnection, CSLSConcurrentObserverStore, IDSService, NSDate, NSObject<OS_dispatch_queue>, NSString, RadiosPreferences, Reachability;

@interface CSLConnectionStatusManager : NSObject <IDSServiceDelegate, APSConnectionDelegate, RadiosPreferencesDelegate>
{
    unsigned int _status;
    NSDate *_lastConnectedDate;
    IDSService *_idsService;
    APSConnection *_apsConnection;
    NSObject<OS_dispatch_queue> *_updateQueue;
    CSLSConcurrentObserverStore *_observers;
    RadiosPreferences *_airplaneModeController;
    Reachability *_reachability;
    int _reachabilityStatus;
}

+ (id)sharedInstance;
@property(nonatomic) int reachabilityStatus; // @synthesize reachabilityStatus=_reachabilityStatus;
@property(retain, nonatomic) Reachability *reachability; // @synthesize reachability=_reachability;
@property(retain, nonatomic) RadiosPreferences *airplaneModeController; // @synthesize airplaneModeController=_airplaneModeController;
@property(retain, nonatomic) CSLSConcurrentObserverStore *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *updateQueue; // @synthesize updateQueue=_updateQueue;
@property(retain, nonatomic) APSConnection *apsConnection; // @synthesize apsConnection=_apsConnection;
@property(retain, nonatomic) IDSService *idsService; // @synthesize idsService=_idsService;
@property(retain) NSDate *lastConnectedDate; // @synthesize lastConnectedDate=_lastConnectedDate;
@property unsigned int status; // @synthesize status=_status;
- (void).cxx_destruct;
- (unsigned int)__updateStatus;
- (void)_notifyChangeInStatus;
- (void)_informObserversOfChangeInStatus;
- (void)_dispatchUpdateStatus;
- (void)_reachabilityUpdated:(id)arg1;
- (void)airplaneModeChanged;
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;
- (void)connection:(id)arg1 didChangeConnectedStatus:(_Bool)arg2;
- (void)service:(id)arg1 connectedDevicesChanged:(id)arg2;
- (void)service:(id)arg1 devicesChanged:(id)arg2;
- (void)service:(id)arg1 activeAccountsChanged:(id)arg2;
- (void)service:(id)arg1 nearbyDevicesChanged:(id)arg2;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (_Bool)_loadPreferences;
- (void)_loadPreferencesAndUpdateIfChanged;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

