//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLUIViewAnimationTransitionTransaction.h"

@interface CSLCrossfadeTransaction : CSLUIViewAnimationTransitionTransaction
{
}

- (id)initWithAnimationOptions:(unsigned int)arg1 duration:(double)arg2 helper:(id)arg3;
- (id)initWithHelper:(id)arg1;

@end

