//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CSLUITileNavigationControllerChildViewController.h"
#import "PUICPageScrollViewControllerDataSource.h"
#import "PUICPageScrollViewControllerDelegate.h"

@class CSLControlCenterUserActivityAssertion, CSLControlCenterUserActivityController, NSArray, NSString, PUICPageIndicatorView;

@interface CSLControlCenterViewController : UIViewController <PUICPageScrollViewControllerDataSource, PUICPageScrollViewControllerDelegate, CSLUITileNavigationControllerChildViewController>
{
    UIViewController *_viewController;
    NSArray *_pages;
    PUICPageIndicatorView *_pageIndicator;
    CSLControlCenterUserActivityController *_userActivityController;
    CSLControlCenterUserActivityAssertion *_appearanceAssertion;
    CSLControlCenterUserActivityAssertion *_alertWindowAssertion;
}

@property(retain, nonatomic) CSLControlCenterUserActivityAssertion *alertWindowAssertion; // @synthesize alertWindowAssertion=_alertWindowAssertion;
@property(retain, nonatomic) CSLControlCenterUserActivityAssertion *appearanceAssertion; // @synthesize appearanceAssertion=_appearanceAssertion;
@property(retain, nonatomic) CSLControlCenterUserActivityController *userActivityController; // @synthesize userActivityController=_userActivityController;
@property(retain, nonatomic) PUICPageIndicatorView *pageIndicator; // @synthesize pageIndicator=_pageIndicator;
@property(retain, nonatomic) NSArray *pages; // @synthesize pages=_pages;
@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
- (void)_handleAlertDidHide:(id)arg1;
- (void)_handleAlertWillShow:(id)arg1;
- (void)_activateUserActivityForPage:(id)arg1;
- (void)_resignCurrentUserActivity;
- (void)_setCurrentUserActivity:(id)arg1 forceRefresh:(_Bool)arg2;
- (void)_resizePageIndictator;
- (void)_updatePageIndicator;
- (void)_loadViewControllersWithCompletion:(CDUnknownBlockType)arg1;
- (void)_loadViewControllers;
- (void)containerScrollViewDidStop:(id)arg1;
- (void)containerScrollViewDidScroll:(id)arg1 withDirection:(unsigned int)arg2;
- (unsigned int)pageScrollViewControllerNumberOfPages:(id)arg1;
- (id)pageScrollViewController:(id)arg1 viewControllerForPageAtIndex:(unsigned int)arg2;
- (void)pageScrollViewController:(id)arg1 didScrollToPageAtIndex:(unsigned int)arg2;
- (void)pageScrollViewController:(id)arg1 pageDidDisappearAtIndex:(unsigned int)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

