//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class PUICStatusView;

@interface CSLClockFaceStatusView : UIView
{
    PUICStatusView *_statusView;
}

@property(nonatomic) __weak PUICStatusView *statusView; // @synthesize statusView=_statusView;
- (void).cxx_destruct;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

