//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLApplicationBundleIDProvider.h"

@class NSArray, NSOrderedSet, NSString;

@interface CSLCombinedBundleIDProvider : NSObject <CSLApplicationBundleIDProvider>
{
    NSArray *_bundleIDProviders;
    NSOrderedSet *_lastComplicationBundleIDs;
}

+ (id)sharedBundleIDProvider;
@property(retain) NSOrderedSet *lastComplicationBundleIDs; // @synthesize lastComplicationBundleIDs=_lastComplicationBundleIDs;
@property(retain, nonatomic) NSArray *bundleIDProviders; // @synthesize bundleIDProviders=_bundleIDProviders;
- (void).cxx_destruct;
- (_Bool)isForComplication:(id)arg1;
- (id)currentApplicationBundleIDs:(unsigned int)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

