//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CSLChangeLanguageSupport : NSObject
{
    _Bool _hasPersistentSnapshot;
    _Bool _relaunchingForBuddyChange;
}

+ (void)preFBSystemAppMain;
+ (id)sharedInstance;
@property(nonatomic, getter=isRelaunchingForBuddyChange) _Bool relaunchingForBuddyChange; // @synthesize relaunchingForBuddyChange=_relaunchingForBuddyChange;
- (void)setupLaunchCompleted;
- (void)mainInterfaceDidAppear;
- (void)applicationDidFinishLaunching;
- (void)localeChanged;
- (void)_localeChanged;
- (void)_showLanguageChangingUI:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_restartForLanguageChange;
- (_Bool)testAndClearRelaunchingForBuddyChange;
- (void)restartNowForBuddy;
@property(nonatomic) _Bool languageRestartWhileLocked;
@property(nonatomic) _Bool languageRestartForBuddy;
@property(nonatomic) _Bool languageRestart;
- (id)init;

@end

