//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLActivityScheduler, NSMutableSet;

@interface CSLDefaultActivitySchedulerManager : NSObject
{
    NSMutableSet *_schedulerHelpers;
    CSLActivityScheduler *_scheduler;
}

+ (id)defaultSchedulerManager;
@property(readonly) CSLActivityScheduler *scheduler; // @synthesize scheduler=_scheduler;
@property(readonly) NSMutableSet *schedulerHelpers; // @synthesize schedulerHelpers=_schedulerHelpers;
- (void).cxx_destruct;
- (id)_createSnapshotThrottlingPolicyWithDateSource:(id)arg1;
- (void)_prepareDefaultScheduler;
- (void)_registerDefaults;
- (id)init;

@end

