//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "NSCopying.h"

@class NSMutableSet, NSString;

@interface CSLDuetActivitySubBudget : NSObject <NSCopying, BSDescriptionProviding>
{
    unsigned int _budgetClass;
    int _credits;
    unsigned int _refreshCredits;
    unsigned int _maxSimultaneousApps;
    NSMutableSet *_eligibleBundleIDs;
}

+ (id)subBudgetWithClass:(unsigned int)arg1 refreshCredits:(unsigned int)arg2 maxSimultaenousApps:(unsigned int)arg3;
@property(readonly, nonatomic) NSMutableSet *eligibleBundleIDs; // @synthesize eligibleBundleIDs=_eligibleBundleIDs;
@property(readonly, nonatomic) unsigned int maxSimultaneousApps; // @synthesize maxSimultaneousApps=_maxSimultaneousApps;
@property(readonly, nonatomic) unsigned int refreshCredits; // @synthesize refreshCredits=_refreshCredits;
@property(nonatomic) int credits; // @synthesize credits=_credits;
@property(readonly, nonatomic) unsigned int budgetClass; // @synthesize budgetClass=_budgetClass;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)deduct;
- (id)budgetDictionaryWithHistory:(id)arg1;
- (void)removeEligibleBundleID:(id)arg1;
- (void)addEligibleBundleID:(id)arg1;
- (void)removeEligibleBundleIDs:(id)arg1;
- (void)addEligibleBundleIDs:(id)arg1;
- (void)refresh;
- (id)initWithClass:(unsigned int)arg1 refreshCredits:(unsigned int)arg2 maxSimultaneousApps:(unsigned int)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

