//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLAppSwitcherItemModelObserver.h"
#import "CSLComplicationMonitorObserver.h"
#import "CSLDuetActivityBudgetDataSourceProtocol.h"

@class CSLAppSwitcherItemModel, CSLComplicationMonitor, NSMutableSet, NSObject<OS_dispatch_queue>, NSString;

@interface CSLDuetActivityBudgetDataSource : NSObject <CSLComplicationMonitorObserver, CSLAppSwitcherItemModelObserver, CSLDuetActivityBudgetDataSourceProtocol>
{
    CSLAppSwitcherItemModel *_switcherModel;
    CSLComplicationMonitor *_complicationMonitor;
    id <CSLDuetActivityBudgetDataSourceDelegateProtocol> _delegate;
    NSObject<OS_dispatch_queue> *_callQueue;
    NSMutableSet *_dockBundleIDs;
    NSMutableSet *_complicationBundleIDs;
    struct _opaque_pthread_mutex_t _lock;
}

@property(retain, nonatomic) NSMutableSet *complicationBundleIDs; // @synthesize complicationBundleIDs=_complicationBundleIDs;
@property(retain, nonatomic) NSMutableSet *dockBundleIDs; // @synthesize dockBundleIDs=_dockBundleIDs;
@property(nonatomic) struct _opaque_pthread_mutex_t lock; // @synthesize lock=_lock;
@property(nonatomic) __weak NSObject<OS_dispatch_queue> *callQueue; // @synthesize callQueue=_callQueue;
@property(nonatomic) __weak id <CSLDuetActivityBudgetDataSourceDelegateProtocol> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak CSLComplicationMonitor *complicationMonitor; // @synthesize complicationMonitor=_complicationMonitor;
@property(nonatomic) __weak CSLAppSwitcherItemModel *switcherModel; // @synthesize switcherModel=_switcherModel;
- (void).cxx_destruct;
- (void)complicationMonitorComplicationsDidChange:(id)arg1 addedBundleIDs:(id)arg2 removedBundleIDs:(id)arg3;
- (void)appSwitcherItemModelDidChange:(id)arg1 removedItems:(id)arg2 addedItems:(id)arg3;
- (id)budgetClassesFor:(id)arg1;
- (void)_callDelegateAdded:(id)arg1 removed:(id)arg2;
- (void)_withLock:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (void)setDelegate:(id)arg1 callQueue:(id)arg2;
- (id)eligibleBundleIDsForClass:(unsigned int)arg1;
- (id)initWithSwitcherModel:(id)arg1 complicationMonitor:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

