//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLAppSwitcherViewController, PUICAdditiveValueAnimator;

@interface CSLDeleteModePresentationFractionAnimator : NSObject
{
    CSLAppSwitcherViewController *_appSwitcherViewController;
    float _targetDeleteModePresentationFraction;
    CDUnknownBlockType _completionBlock;
    PUICAdditiveValueAnimator *_deleteModePresentationFractionAnimator;
    _Bool _completionCalled;
}

- (void).cxx_destruct;
- (void)_completeIfDone;
- (void)_animationApplier;
- (void)_animateToDeleteModePresentationFraction:(float)arg1;
- (void)_completeAnimation;
- (void)_updateForDeleteModePresentationFraction:(float)arg1;
- (void)animateWithCompletion:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithAppSwitcherViewController:(id)arg1 targetDeleteModePresentationFraction:(float)arg2;

@end

