//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CSLDuetApplicationProcessState : NSObject
{
    _Bool _foreground;
    int _pid;
    int _secondaryPid;
}

@property(readonly, nonatomic, getter=isForeground) _Bool foreground; // @synthesize foreground=_foreground;
@property(readonly, nonatomic) int secondaryPid; // @synthesize secondaryPid=_secondaryPid;
@property(readonly, nonatomic) int pid; // @synthesize pid=_pid;
- (_Bool)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (id)initWithPid:(int)arg1 secondaryPid:(int)arg2 foreground:(_Bool)arg3;

@end

