//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface CSLDiagnosticsObserver : NSObject
{
    NSMutableArray *_handlers;
    _Bool _comboHandlersEnabled;
    _Bool _isInternalInstall;
}

+ (void)registerDefaultDiagnosticEventHandlers;
+ (id)sharedObserver;
- (void).cxx_destruct;
- (void)_usr1SignalNotification;
- (void)_executeHandlers;
- (void)_stackshotComboTaken;
- (void)registerHandler:(id)arg1;
- (id)init;

@end

