//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDAttribute, NSObject<OS_dispatch_queue>;

@interface CSLDuetMeteringManagerConfiguration : NSObject
{
    id <CSLDuetApplicationProcessStateProvider> _provider;
    NSObject<OS_dispatch_queue> *_queue;
    CDAttribute *_attribute;
}

@property(retain, nonatomic) CDAttribute *attribute; // @synthesize attribute=_attribute;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) id <CSLDuetApplicationProcessStateProvider> provider; // @synthesize provider=_provider;
- (void).cxx_destruct;

@end

