//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "CSLDuetApplicationProcessStateObserver.h"

@class CSLDuetMeteringManagerConfiguration, NSMutableDictionary, NSString;

@interface CSLDuetMeteringManager : NSObject <CSLDuetApplicationProcessStateObserver, BSDescriptionProviding>
{
    NSMutableDictionary *_groupsByBundleID;
    CSLDuetMeteringManagerConfiguration *_configuration;
}

+ (id)defaultAttribute;
+ (id)defaultMeteringManager;
@property(readonly) CSLDuetMeteringManagerConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) NSMutableDictionary *groupsByBundleID; // @synthesize groupsByBundleID=_groupsByBundleID;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (void)applicationProcessStateProvider:(id)arg1 didUpdateBundleID:(id)arg2 fromState:(id)arg3 toState:(id)arg4;
- (void)taskGroupDidComplete:(id)arg1;
- (id)existingMeteringGroupsForBundleID:(id)arg1;
- (id)meteringGroupsForBundleID:(id)arg1;
- (id)createMeteringTaskForRequest:(id)arg1;
- (id)processStateProvider;
- (id)queue;
@property(readonly, copy) NSString *description;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

