//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "CSLDuetApplicationProcessStateProvider.h"
#import "CSLWatchKitProcessMonitorObserver.h"
#import "FBProcessManagerObserver.h"
#import "FBProcessObserver.h"

@class FBProcessManager, IOSSHLApplicationsManager, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface CSLDuetFBApplicationProcessStateProvider : NSObject <FBProcessManagerObserver, FBProcessObserver, CSLWatchKitProcessMonitorObserver, CSLDuetApplicationProcessStateProvider, BSDescriptionProviding>
{
    FBProcessManager *_processManager;
    IOSSHLApplicationsManager *_applicationsManager;
    id <CSLDuetApplicationProcessStateObserver> _observer;
    NSMutableDictionary *_fbProcessStateMap;
    NSMutableDictionary *_extensionStateMap;
    NSMutableDictionary *_processStateMap;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(readonly) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly) NSMutableDictionary *processStateMap; // @synthesize processStateMap=_processStateMap;
@property(readonly) NSMutableDictionary *extensionStateMap; // @synthesize extensionStateMap=_extensionStateMap;
@property(readonly) NSMutableDictionary *fbProcessStateMap; // @synthesize fbProcessStateMap=_fbProcessStateMap;
@property(nonatomic) __weak id <CSLDuetApplicationProcessStateObserver> observer; // @synthesize observer=_observer;
@property(readonly, nonatomic) IOSSHLApplicationsManager *applicationsManager; // @synthesize applicationsManager=_applicationsManager;
@property(readonly, nonatomic) FBProcessManager *processManager; // @synthesize processManager=_processManager;
- (void).cxx_destruct;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (void)_queue_updateWatchKitApplicationStateInfo:(id)arg1 error:(id)arg2;
- (void)_queue_updateBundleID:(id)arg1 withFBProcessState:(id)arg2 extensionState:(id)arg3;
- (void)_queue_updateBundleID:(id)arg1 withExtensionState:(id)arg2;
- (void)_queue_updateBundleID:(id)arg1 withFBProcessState:(id)arg2;
- (void)process:(id)arg1 stateDidChangeFromState:(id)arg2 toState:(id)arg3;
- (void)processDidExit:(id)arg1;
- (void)processMonitor:(id)arg1 receivedApplicationStateInfo:(id)arg2 error:(id)arg3;
- (void)processManager:(id)arg1 didRemoveProcess:(id)arg2;
- (void)processManager:(id)arg1 didAddProcess:(id)arg2;
- (_Bool)isApplicationForeground:(id)arg1;
- (id)processStateForBundleID:(id)arg1;
- (_Bool)isWatchKitApplication:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)initWithProcessManager:(id)arg1 applicationsManager:(id)arg2 queue:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

