//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLDuetBudgetController.h"

@class NSSet;

@interface CSLDuetBackgroundBudgetController : CSLDuetBudgetController
{
    id <CSLDuetBackgroundBudgetControllerDelegate> _delegate;
    NSSet *_lastComplications;
}

+ (id)defaultConfiguration;
@property(retain) NSSet *lastComplications; // @synthesize lastComplications=_lastComplications;
@property(nonatomic) __weak id <CSLDuetBackgroundBudgetControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)priorityBundleIDs;
- (id)initWithModel:(id)arg1 complicationMonitor:(id)arg2 context:(id)arg3 configuration:(id)arg4;

@end

