//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLSDockStatusServiceXPC.h"
#import "NSXPCListenerDelegate.h"

@class CSLClientConnections, NSString, NSXPCListener;

@interface CSLDockStatusServiceEndpoint : NSObject <NSXPCListenerDelegate, CSLSDockStatusServiceXPC>
{
    NSXPCListener *_listener;
    CSLClientConnections *_clients;
}

+ (id)sharedInstance;
@property(retain, nonatomic) CSLClientConnections *clients; // @synthesize clients=_clients;
@property(retain, nonatomic) NSXPCListener *listener; // @synthesize listener=_listener;
- (void).cxx_destruct;
- (void)connect;
- (void)retrieveDockStatusForBundleID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)resume;
- (id)_init;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

