//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol CSLDuetBudgetControllerConfiguration <NSObject>
@property(readonly, nonatomic) NSString *budgetControllerName;
@property(readonly, nonatomic) NSString *budgetContextKeyPath;
@property(readonly, nonatomic) NSArray *budgets;
@property(readonly, nonatomic) double budgetPeriodDefault;
@property(readonly, nonatomic) NSString *name;
@end

