//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLDuetApplicationProcessState, NSString;

@protocol CSLDuetApplicationProcessStateProvider <NSObject>
@property(nonatomic) __weak id <CSLDuetApplicationProcessStateObserver> observer;
- (_Bool)isWatchKitApplication:(NSString *)arg1;
- (CSLDuetApplicationProcessState *)processStateForBundleID:(NSString *)arg1;
- (_Bool)isApplicationForeground:(NSString *)arg1;
@end

