//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class NSCountedSet, NSDate, NSMutableDictionary, NSString;

@interface CSLDuetActivityBudget : NSObject <BSDescriptionProviding>
{
    NSString *_name;
    NSMutableDictionary *_subBudgetsByClass;
    id <CSLDuetActivityBudgetDataSourceProtocol> _dataSource;
    NSCountedSet *_history;
    NSDate *_lastRefresh;
}

@property(retain, nonatomic) NSDate *lastRefresh; // @synthesize lastRefresh=_lastRefresh;
@property(readonly, nonatomic) NSCountedSet *history; // @synthesize history=_history;
@property(nonatomic) __weak id <CSLDuetActivityBudgetDataSourceProtocol> dataSource; // @synthesize dataSource=_dataSource;
@property(copy, nonatomic) NSMutableDictionary *subBudgetsByClass; // @synthesize subBudgetsByClass=_subBudgetsByClass;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (id)budgetDictionary;
- (void)refreshBudget;
- (void)eligibleBundleIDsAdded:(id)arg1 removed:(id)arg2;
- (void)activityStartedForBundleID:(id)arg1 deduct:(_Bool)arg2;
- (id)_bestSubBudgetForBundleID:(id)arg1;
- (id)initWithName:(id)arg1 dataSource:(id)arg2 subBudgets:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

