//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLDuetBudgetControllerConfiguration.h"

@class NSArray, NSString;

@interface CSLDuetBackgroundBudgetControllerConfiguration : NSObject <CSLDuetBudgetControllerConfiguration>
{
}

+ (id)defaultConfiguration;
+ (void)initialize;
- (int)_budgetPeriodComplicationsCreditDefault;
- (int)_budgetPeriodDockAppsCreditDefault;
@property(readonly, nonatomic) NSString *budgetControllerName;
@property(readonly, nonatomic) NSString *budgetContextKeyPath;
@property(readonly, nonatomic) NSArray *budgets;
@property(readonly, nonatomic) double budgetPeriodDefault;
@property(readonly, nonatomic) NSString *name;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

