//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLReorderingAnimation.h"

@class PUICAdditiveValueAnimator, UIView;

@interface CSLFadeAnimation : CSLReorderingAnimation
{
    _Bool _addMode;
    int _index;
    float _fadeMultiplier;
    UIView *_snapshotView;
    PUICAdditiveValueAnimator *_additiveValueAnimator;
}

+ (id)animationAtIndex:(int)arg1;
@property(retain, nonatomic) PUICAdditiveValueAnimator *additiveValueAnimator; // @synthesize additiveValueAnimator=_additiveValueAnimator;
@property(retain, nonatomic) UIView *snapshotView; // @synthesize snapshotView=_snapshotView;
@property(nonatomic, getter=isAddMode) _Bool addMode; // @synthesize addMode=_addMode;
@property(nonatomic) float fadeMultiplier; // @synthesize fadeMultiplier=_fadeMultiplier;
@property(nonatomic) int index; // @synthesize index=_index;
- (void).cxx_destruct;
- (void)startAnimating;
- (void)animator:(id)arg1 setFadeMultiplier:(float)arg2;
- (void)buildAnimator;

@end

