//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLAppSwitcherItemModelObserver.h"
#import "CSLComplicationMonitorObserver.h"
#import "CSLDuetApplicationProcessStateObserver.h"

@class CSLDuetFBApplicationProcessStateProvider, NSMutableOrderedSet, NSObject<OS_dispatch_queue>, NSString;

@interface CSLJetsamBandElevator : NSObject <CSLAppSwitcherItemModelObserver, CSLComplicationMonitorObserver, CSLDuetApplicationProcessStateObserver>
{
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableOrderedSet *_elevatedBundleIDs;
    unsigned int _maximumMemoryUsageInMegabytes;
    unsigned int _maximumMemoryUsageRangeInMegabytes;
    CSLDuetFBApplicationProcessStateProvider *_processStateProvider;
}

+ (id)sharedJetsamBandElevator;
- (void).cxx_destruct;
- (_Bool)_trimElevatedJetsamBandToMemorySize:(unsigned int)arg1;
- (_Bool)_willProcessFitIntoElevatedJetsamBand:(unsigned int)arg1 currentMemoryUsage:(unsigned int)arg2 maximumMemoryUsage:(unsigned int)arg3;
- (_Bool)_isBundleIDElevated:(id)arg1;
- (_Bool)_isBundleIDEligibleForElevation:(id)arg1;
- (unsigned int)_minimumFreeMemoryRequiredForElevation;
- (unsigned int)_maximumMemoryUsage;
- (id)_currentElevatedMemoryUsageByBundleID;
- (unsigned int)_currentElevatedMemoryUsage;
- (unsigned int)_memoryUsageForBundleID:(id)arg1;
- (unsigned int)_memoryUsageForProcessState:(id)arg1;
- (void)_raiseJetsamBandIfNecessaryForBundleID:(id)arg1 state:(id)arg2;
- (void)_raiseJetsamBandIfNecessaryForBundleID:(id)arg1;
- (void)_lowerJetsamBandForBundleID:(id)arg1 state:(id)arg2;
- (void)_lowerJetsamBandForBundleID:(id)arg1;
- (_Bool)_raiseJetsamBandForBundleID:(id)arg1 state:(id)arg2;
- (_Bool)_raiseJetsamBandForBundleID:(id)arg1;
- (void)_forgetBundleID:(id)arg1;
- (void)_loadPreferences;
- (void)complicationMonitorComplicationsDidChange:(id)arg1 addedBundleIDs:(id)arg2 removedBundleIDs:(id)arg3;
- (void)appSwitcherItemModelDidChange:(id)arg1 removedItems:(id)arg2 addedItems:(id)arg3;
- (void)applicationProcessStateProvider:(id)arg1 didUpdateBundleID:(id)arg2 fromState:(id)arg3 toState:(id)arg4;
- (_Bool)isElevatedBandFull;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

