//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLCrossfadeTransaction.h"

@class CSLLauncherViewController, CSLLauncherZoomOptions;

@interface CSLLauncherCrossfadeTransaction : CSLCrossfadeTransaction
{
    CSLLauncherViewController *_launcherViewController;
    CSLLauncherZoomOptions *_options;
}

- (void).cxx_destruct;
- (void)_begin;
- (id)initWithHelper:(id)arg1 options:(id)arg2;

@end

