//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLMRUStringArrayNode, NSMutableDictionary;

@interface CSLMRUStringArray : NSObject
{
    NSMutableDictionary *_nodes;
    CSLMRUStringArrayNode *_head;
    CSLMRUStringArrayNode *_tail;
    struct _opaque_pthread_mutex_t _mutex;
}

- (void).cxx_destruct;
- (id)array;
- (void)_removeNodeFromList:(id)arg1;
- (_Bool)remove:(id)arg1;
- (void)touch:(id)arg1;
- (void)dealloc;
- (id)_appendItem:(id)arg1 tail:(id)arg2;
- (_Bool)append:(id)arg1;
- (id)initWithArray:(id)arg1;
- (id)description;
- (id)init;

@end

