//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CSLMRUApplications, NSString;

@protocol CSLMRUApplicationsDelegate
- (void)mruApplications:(CSLMRUApplications *)arg1 exitedBundleID:(NSString *)arg2;
- (void)mruApplications:(CSLMRUApplications *)arg1 touchedBundleID:(NSString *)arg2;
@end

