//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class CSLMainUIState, NSString;

@interface CSLMainUITransitionContext : NSObject <BSDescriptionProviding>
{
    _Bool _interactive;
    CSLMainUIState *_initialState;
    CSLMainUIState *_expectedEndState;
}

+ (void)removeEntitiesFromEndOfArray:(id)arg1 usingStopPredicate:(CDUnknownBlockType)arg2;
+ (void)removeNonClockOrLauncherEntitiesFromEndOfArray:(id)arg1;
+ (void)removeNonClockOrLauncherOrSwitcherEntitiesFromEndOfArray:(id)arg1;
+ (id)transitionContextWithInitialState:(id)arg1 updateAction:(id)arg2;
@property(retain, nonatomic) CSLMainUIState *expectedEndState; // @synthesize expectedEndState=_expectedEndState;
@property(retain, nonatomic) CSLMainUIState *initialState; // @synthesize initialState=_initialState;
@property(nonatomic, getter=isInteractive) _Bool interactive; // @synthesize interactive=_interactive;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic, getter=isChangingForegroundApplication) _Bool changingForegroundApplication;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

