//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

@interface CSLMidnightTimer : NSObject
{
    NSTimer *_internalTimer;
}

@property(retain, nonatomic) NSTimer *internalTimer; // @synthesize internalTimer=_internalTimer;
- (void).cxx_destruct;
- (void)createTimerWithFireDate:(id)arg1;
- (void)scheduleMidnightTimer;
- (_Bool)timerIsPastMidnightFireDate;
- (void)workspaceDidWakeFromSleep:(id)arg1;
- (void)midnightPassed;
- (id)midnightTimerFireDate;
- (void)significantTimeChange;
- (void)dealloc;
- (id)init;

@end

