//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLUICarouselApplicationStoreListener.h"

@class CSLMRUStringArray, NSArray, NSString;

@interface CSLMRUApplications : NSObject <CSLUICarouselApplicationStoreListener>
{
    CSLMRUStringArray *_mruActiveArray;
    CSLMRUStringArray *_mruAllArray;
    id <CSLMRUApplicationsDelegate> _delegate;
}

+ (id)sharedInstance;
@property(nonatomic) __weak id <CSLMRUApplicationsDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)applicationStore:(id)arg1 applicationPlaceholderInstalled:(id)arg2;
- (void)applicationStore:(id)arg1 addedBundleIDs:(id)arg2 removedBundleIDs:(id)arg3 modifiedBundleIDs:(id)arg4;
- (void)_saveMRUToPreferences;
- (void)_saveMRUAfter5Seconds;
- (void)exitedBundleID:(id)arg1;
- (void)touchBundleID:(id)arg1;
- (void)_setMRUAllBundleIDs:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *mruActiveBundleIDs;
@property(readonly, copy, nonatomic) NSArray *mruBundleIDs;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

