//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CSLMRUStringArrayNode : NSObject
{
    CSLMRUStringArrayNode *_next;
    CSLMRUStringArrayNode *_previous;
    NSString *_string;
}

@property(copy, nonatomic) NSString *string; // @synthesize string=_string;
@property(retain, nonatomic) CSLMRUStringArrayNode *previous; // @synthesize previous=_previous;
@property(retain, nonatomic) CSLMRUStringArrayNode *next; // @synthesize next=_next;
- (void).cxx_destruct;
- (id)init;
- (id)initWithString:(id)arg1;

@end

