//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IOSSHLTransaction.h"

@class CSLNavigationStackController, CSLNavigationTransactionAnimatorHelper, NSArray;

@interface CSLMainUIInitialSetupTransaction : IOSSHLTransaction
{
    NSArray *_viewControllers;
    CSLNavigationStackController *_navigationController;
    CSLNavigationTransactionAnimatorHelper *_helper;
}

@property(retain, nonatomic) CSLNavigationTransactionAnimatorHelper *helper; // @synthesize helper=_helper;
@property(retain, nonatomic) CSLNavigationStackController *navigationController; // @synthesize navigationController=_navigationController;
@property(retain, nonatomic) NSArray *viewControllers; // @synthesize viewControllers=_viewControllers;
- (void).cxx_destruct;
- (_Bool)shouldWatchdog:(id *)arg1;
- (void)_begin;

@end

