//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CSLMemoryUtilities : NSObject
{
}

+ (id)memoryUsageDictionaryForBundleIDs:(id)arg1;
+ (unsigned int)memoryUsageForBundleIDs:(id)arg1;
+ (unsigned int)memoryUsageForBundleID:(id)arg1;
+ (unsigned int)memoryUsageForApplication:(id)arg1;
+ (unsigned int)memoryUsageForPid:(int)arg1;

@end

