//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_source>;

@interface CSLMemoryPressure : NSObject
{
    NSObject<OS_dispatch_source> *_memoryPressureSource;
    unsigned int _memoryPressureStatus;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool underMemoryPressure;
- (id)init;

@end

