//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController, UIViewController<CSLNavigableContainerProtocol>;

@protocol CSLNavigableContainerProtocol <NSObject>
- (_Bool)containsVisibleViewController:(UIViewController *)arg1;
- (void)beginDisappearingTransitionToViewController:(UIViewController<CSLNavigableContainerProtocol> *)arg1 animated:(_Bool)arg2;
- (void)beginAppearingTransitionFromViewController:(UIViewController<CSLNavigableContainerProtocol> *)arg1 animated:(_Bool)arg2;
@end

