//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IOSSHLTransaction.h"

#import "CSLNavigationTransactionAnimator.h"

@class CSLNavigationTransactionAnimatorHelper, NSString;

@interface CSLNullNavigationTransactionAnimator : IOSSHLTransaction <CSLNavigationTransactionAnimator>
{
    id <CSLNavigationTransactionAnimatorDelegate> navigationTransactionAnimatorDelegate;
    CDUnknownBlockType _beginAppearanceTransitionBlock;
    CSLNavigationTransactionAnimatorHelper *_helper;
}

@property(readonly, nonatomic) CSLNavigationTransactionAnimatorHelper *helper; // @synthesize helper=_helper;
@property(copy, nonatomic) CDUnknownBlockType beginAppearanceTransitionBlock; // @synthesize beginAppearanceTransitionBlock=_beginAppearanceTransitionBlock;
@property(nonatomic) __weak id <CSLNavigationTransactionAnimatorDelegate> navigationTransactionAnimatorDelegate; // @synthesize navigationTransactionAnimatorDelegate;
- (void).cxx_destruct;
- (void)_begin;
- (id)initWithHelper:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

