//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLNavigableViewController.h"

#import "CSLNavigableContainerProtocol.h"
#import "CSLPIButtonHandlerProtocol.h"

@class CSLMainUIEntity, NSString, UIViewController;

@interface CSLNavigableContainerViewController : CSLNavigableViewController <CSLPIButtonHandlerProtocol, CSLNavigableContainerProtocol>
{
    _Bool _containeeVisibleOnBothSidesOfTransition;
    CSLMainUIEntity *_entity;
    UIViewController *_containeeViewController;
}

@property(readonly, nonatomic) UIViewController *containeeViewController; // @synthesize containeeViewController=_containeeViewController;
@property(readonly, nonatomic) CSLMainUIEntity *entity; // @synthesize entity=_entity;
- (void).cxx_destruct;
- (_Bool)containsVisibleViewController:(id)arg1;
- (void)beginDisappearingTransitionToViewController:(id)arg1 animated:(_Bool)arg2;
- (void)beginAppearingTransitionFromViewController:(id)arg1 animated:(_Bool)arg2;
- (_Bool)handleButton:(unsigned int)arg1 eventType:(unsigned int)arg2;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)claimContainee;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(readonly, copy) NSString *description;
- (id)initWithEntity:(id)arg1 containeeViewController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

