//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CSLNavigationLogEntry : NSObject
{
    NSString *_location;
}

+ (id)entryWithLocation:(id)arg1;
@property(readonly, nonatomic) NSString *location; // @synthesize location=_location;
- (void).cxx_destruct;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)initWithLocation:(id)arg1;

@end

