//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLNavigationStackController, UIViewController;

@protocol CSLNavigationStackControllerAnimationProvider <NSObject>
- (id <UIViewControllerAnimatedTransitioning>)navigationController:(CSLNavigationStackController *)arg1 animationControllerForOperation:(int)arg2 fromViewController:(UIViewController *)arg3 toViewController:(UIViewController *)arg4;

@optional
- (id <UIViewControllerAnimatedTransitioning>)navigationController:(CSLNavigationStackController *)arg1 animationControllerForNonAnimatedOperation:(int)arg2 fromViewController:(UIViewController *)arg3 toViewController:(UIViewController *)arg4;
@end

