//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLSNavigationServerExportedInterface.h"
#import "NSXPCListenerDelegate.h"

@class NSMutableArray, NSString, NSXPCListener;

@interface CSLNavigationServer : NSObject <NSXPCListenerDelegate, CSLSNavigationServerExportedInterface>
{
    NSMutableArray *_clientConnections;
    NSXPCListener *_listener;
}

+ (id)sharedNavigationServer;
@property(retain, nonatomic) NSXPCListener *listener; // @synthesize listener=_listener;
@property(retain, nonatomic) NSMutableArray *clientConnections; // @synthesize clientConnections=_clientConnections;
- (void).cxx_destruct;
- (void)navigateToLocation:(unsigned int)arg1 dockBundleID:(id)arg2 activateDockApp:(_Bool)arg3 withCompletion:(CDUnknownBlockType)arg4;
- (void)_removeClientConnection:(id)arg1;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

