//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CSLBulletinPipelineStepActor.h"
#import "CSLNotificationCenterCellFactoryManagerDelegate.h"
#import "CSLUITileNavigationControllerChildViewController.h"
#import "PUICActionControllerDelegate.h"
#import "PUICTableViewDataSource.h"
#import "PUICTableViewDelegate.h"

@class BBObserver, CSLNotificationCenterBulletin, CSLNotificationCenterCellFactoryManager, CSLScreenEdgeChevronView, NSCountedSet, NSMutableArray, NSObject<OS_dispatch_queue>, NSString, PUICContentUnavailableView, PUICTableView, UIApplication, UIScrollView, UIView;

@interface CSLNotificationCenterViewController : UIViewController <PUICTableViewDataSource, PUICTableViewDelegate, PUICActionControllerDelegate, CSLBulletinPipelineStepActor, CSLNotificationCenterCellFactoryManagerDelegate, CSLUITileNavigationControllerChildViewController>
{
    _Bool _isFullyPresented;
    CSLNotificationCenterCellFactoryManager *_cellFactoryManager;
    _Bool _shouldScrollToBottomOnAppear;
    CSLNotificationCenterBulletin *_editingItem;
    UIView *_tableFooter;
    UIView *_chevronContainerView;
    CSLScreenEdgeChevronView *_chevronView;
    PUICContentUnavailableView *_contentUnavailableView;
    NSCountedSet *_sectionIDs;
    NSMutableArray *_bulletins;
    UIApplication *_pptScrollTestApplication;
    _Bool _pptScrollTestStarted;
    NSString *_pptScrollTestName;
    int _pptScrollTestCount;
    UIScrollView *_pptScrollView;
    id <CSLBulletinPipelineStepActorDelegate> _pipelineStep;
    id <CSLNotificationCenterViewControllerAlertDelegate> _alertDelegate;
    id <CSLNotificationCenterViewControllerDelegate> _delegate;
    PUICTableView *_tableView;
    NSObject<OS_dispatch_queue> *_queue;
    BBObserver *_observer;
}

+ (id)sharedNotificationCenterViewController;
@property(retain, nonatomic) BBObserver *observer; // @synthesize observer=_observer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) PUICTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <CSLNotificationCenterViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <CSLNotificationCenterViewControllerAlertDelegate> alertDelegate; // @synthesize alertDelegate=_alertDelegate;
@property(nonatomic) __weak id <CSLBulletinPipelineStepActorDelegate> pipelineStep; // @synthesize pipelineStep=_pipelineStep;
- (void).cxx_destruct;
- (void)_aggdLogPurgedNotificationCount:(unsigned int)arg1 totalBeforePurge:(unsigned int)arg2;
- (void)_pptScrollAnimationComplete:(id)arg1;
- (void)_pptDoNotificationCenterScrollTestName:(id)arg1 withApplication:(id)arg2;
- (void)_isBulletinEligibleToAdd:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateStateForAddedBulletin:(id)arg1 feed:(unsigned int)arg2;
- (void)_markBulletinsRead;
- (void)_setNeedsScrollPositionReset;
- (void)_handleSizeCategoryChange:(id)arg1;
- (void)_resetCellHeights;
- (int)_animationTypeForCurrentState;
- (void)_scrollToBottom;
- (void)_postClearedNotification;
- (id)_contentUnavailableText;
- (void)_addContentUnavailableViewIfNecessary;
- (void)_removeContentUnavailableViewIfNecessary;
- (void)_clearAllBulletins:(id)arg1;
- (void)_unlockClearedBulletins:(id)arg1;
- (void)_clearBulletinsFromObserver:(id)arg1;
- (void)_markBulletinsAsCleared:(id)arg1;
- (id)_clearableBulletinsBySectionID;
- (unsigned int)_indexOfBulletin:(id)arg1;
- (id)_indexesOfBulletinsWithSectionID:(id)arg1;
- (void)_removeBulletin:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (_Bool)_containsClearableBulletin;
- (id)_bulletinWithKey:(id)arg1;
- (_Bool)_containsBulletinWithKey:(id)arg1;
- (void)_removeBulletinsFromTableView:(id)arg1;
- (float)_heightForBulletin:(id)arg1;
- (id)_indexPathForInsertingBulletin:(id)arg1;
- (id)_sortDateForBulletin:(id)arg1;
- (void)_replaceBulletin:(id)arg1 withBulletin:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)_clearImage;
- (void)_getNotificationCenterIconForBulletin:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_createChevron;
- (void)_updateChevronPositionAnimated:(_Bool)arg1;
- (void)_createTableFooter;
- (void)containerScrollViewDidStop:(id)arg1;
- (void)containerScrollViewDidScroll:(id)arg1 withDirection:(unsigned int)arg2;
- (void)cellFactoryManager:(id)arg1 requestReloadCellsForFactory:(id)arg2 bulletins:(CDUnknownBlockType)arg3;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 editActionsForRowAtIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)actionControllerDidDisappear:(id)arg1;
- (void)actionControllerDidAppear:(id)arg1;
- (void)actionControllerDidCancel:(id)arg1;
- (void)actionController:(id)arg1 willSelectActionItem:(id)arg2;
- (_Bool)canProvideActionController;
- (id)actionController;
- (void)forgetBulletins:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)sectionParametersChangedForSectionID:(id)arg1;
- (void)removeBulletin:(id)arg1 feed:(unsigned int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)modifyBulletin:(id)arg1 feed:(unsigned int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)addBulletin:(id)arg1 replaceBulletin:(id)arg2 feed:(unsigned int)arg3 completion:(CDUnknownBlockType)arg4;
- (void)addBulletin:(id)arg1 feed:(unsigned int)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) unsigned int observedFeeds;
- (_Bool)becomeFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

