//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface CSLNotificationIconGrabber : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
}

- (void).cxx_destruct;
- (void)_sectionInfoFromSectionID:(id)arg1 withObserver:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)_imageFromLocalIcon:(id)arg1 lsIconVariant:(int)arg2;
- (id)_imageFromSectionIcon:(id)arg1 forIconVariant:(int)arg2;
- (void)getIconForBulletin:(id)arg1 withObserver:(id)arg2 shape:(unsigned int)arg3 size:(unsigned int)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (_Bool)isAppInstalled:(id)arg1;
- (int)iconVariantForIconSize:(unsigned int)arg1 isRoundIcon:(_Bool)arg2 isCompactDevice:(_Bool)arg3;
- (int)sectionIconFormatForIconVariant:(int)arg1;
- (id)init;

@end

