//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLReorderingAnimation.h"

@class PUICAdditiveValueAnimator;

@interface CSLOffsetAnimation : CSLReorderingAnimation
{
    float _currentOffset;
    PUICAdditiveValueAnimator *_additiveValueAnimator;
    float _fromOffset;
    float _targetOffset;
}

+ (id)offsetAnimationWithOffset:(float)arg1;
@property(nonatomic) float targetOffset; // @synthesize targetOffset=_targetOffset;
@property(nonatomic) float fromOffset; // @synthesize fromOffset=_fromOffset;
@property(retain, nonatomic) PUICAdditiveValueAnimator *additiveValueAnimator; // @synthesize additiveValueAnimator=_additiveValueAnimator;
@property(nonatomic) float currentOffset; // @synthesize currentOffset=_currentOffset;
- (void).cxx_destruct;
- (void)subsumeOffsetAnimation:(id)arg1;
- (void)startAnimatingWithDuration:(float)arg1;
- (void)startAnimating;
- (void)animator:(id)arg1 setOffset:(float)arg2;
- (void)buildAnimatorWithOffset:(float)arg1;

@end

