//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLPowerTesterDelegate.h"
#import "CSLSPowerTester.h"
#import "NSXPCListenerDelegate.h"

@class CSLClientConnections, NSMutableArray, NSObject<OS_dispatch_queue>, NSString, NSXPCListener;

@interface CSLPowerTestServer : NSObject <NSXPCListenerDelegate, CSLSPowerTester, CSLPowerTesterDelegate>
{
    CSLClientConnections *_clients;
    NSXPCListener *_listener;
    NSObject<OS_dispatch_queue> *_testQueue;
    NSMutableArray *_testers;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *testers; // @synthesize testers=_testers;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *testQueue; // @synthesize testQueue=_testQueue;
@property(retain, nonatomic) NSXPCListener *listener; // @synthesize listener=_listener;
@property(retain, nonatomic) CSLClientConnections *clients; // @synthesize clients=_clients;
- (void).cxx_destruct;
- (void)tester:(id)arg1 cancelled:(id)arg2;
- (void)tester:(id)arg1 completed:(id)arg2;
- (void)startTest:(id)arg1;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

