//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLPrelaunchBlacklist, NSString;

@protocol CSLPrelaunchBlacklistObserver <NSObject>
- (void)prelaunchBlacklist:(CSLPrelaunchBlacklist *)arg1 appExited:(NSString *)arg2 isBlacklisted:(_Bool)arg3;
@end

