//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLPPTTest.h"

@class NSString;

@interface CSLPPTUnlockTest : CSLPPTTest
{
    NSString *_testName;
}

+ (id)testPrefix;
@property(retain, nonatomic) NSString *testName; // @synthesize testName=_testName;
- (void).cxx_destruct;
- (void)lock;
- (void)unlock;
- (void)runTest:(id)arg1;

@end

