//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface CSLPrelaunchBlacklistObserverEntry : NSObject
{
    id <CSLPrelaunchBlacklistObserver> _observer;
    id _unsafeObserver;
    NSObject<OS_dispatch_queue> *_callbackQueue;
}

+ (id)entryForObserver:(id)arg1 callbackQueue:(id)arg2;
@property(nonatomic) __weak NSObject<OS_dispatch_queue> *callbackQueue; // @synthesize callbackQueue=_callbackQueue;
@property(nonatomic) id unsafeObserver; // @synthesize unsafeObserver=_unsafeObserver;
@property(nonatomic) __weak id <CSLPrelaunchBlacklistObserver> observer; // @synthesize observer=_observer;
- (void).cxx_destruct;
- (void)callObserverFor:(id)arg1 appExited:(id)arg2 isBlacklisted:(_Bool)arg3;

@end

