//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLPPTTest.h"

@class CSLPageOffsetAnimator, IOSSHLApplication, NSString;

@interface CSLPPTLocationBasedTest : CSLPPTTest
{
    CSLPageOffsetAnimator *_offsetAnimator;
    NSString *_testName;
    NSString *_launchLocation;
    NSString *_bundleIdentifier;
    IOSSHLApplication *_application;
}

@property(retain, nonatomic) IOSSHLApplication *application; // @synthesize application=_application;
@property(retain, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(retain, nonatomic) NSString *launchLocation; // @synthesize launchLocation=_launchLocation;
@property(retain, nonatomic) NSString *testName; // @synthesize testName=_testName;
- (void).cxx_destruct;
- (void)touchApplicationForMRU;
- (void)flagNextActivationForTesting;
- (void)performActivationWithInitialDelay:(CDUnknownBlockType)arg1 afterNavigationDelay:(CDUnknownBlockType)arg2;
- (void)navigateToLaunchLocationWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)runTest:(id)arg1;
- (id)init;

@end

