//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CSLPageViewCenteringPolicy : NSObject
{
    int _fromCenter;
    int _matchingOffset;
}

+ (id)policyWithOffsetFromCenter:(int)arg1 matchingOffset:(int)arg2;
@property(nonatomic) int matchingOffset; // @synthesize matchingOffset=_matchingOffset;
@property(nonatomic) int fromCenter; // @synthesize fromCenter=_fromCenter;

@end

