//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLPPTTest.h"

@interface CSLPPTCreateComplicationsOnFaceTest : CSLPPTTest
{
    _Bool _synchronously;
}

+ (id)testPrefix;
@property(nonatomic) _Bool synchronously; // @synthesize synchronously=_synchronously;
- (void)runTest:(id)arg1;
- (id)init;

@end

