//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAMediaTimingFunction, NSMutableArray;

@interface CSLPageDotsView : UIView
{
    NSMutableArray *_dotLayers;
    float _normalizedSelectedIndexFraction;
    float _totalDotDistance;
    float _availableDistance;
    CAMediaTimingFunction *_pageDotsColorTimingFunction;
    CAMediaTimingFunction *_pageDotsDiameterTimingFunction;
    unsigned int _numberOfDots;
    float _selectedIndexFraction;
}

@property(readonly, nonatomic) float selectedIndexFraction; // @synthesize selectedIndexFraction=_selectedIndexFraction;
@property(readonly, nonatomic) unsigned int numberOfDots; // @synthesize numberOfDots=_numberOfDots;
- (void).cxx_destruct;
- (void)createDotLayersAnimated:(_Bool)arg1;
- (void)layoutSubviews;
- (void)updateNormalizedSelectedIndexFraction;
- (void)setDotAtIndex:(unsigned int)arg1 hallow:(_Bool)arg2 animated:(_Bool)arg3;
- (void)setNumberOfDots:(unsigned int)arg1 animated:(_Bool)arg2;
- (void)setSelectedIndexFraction:(float)arg1 animated:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

