//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLPageScrollView, NSString, UIView;

@protocol CSLPageScrollViewDelegate <NSObject>
- (void)scrollViewLayoutPercentageChanged:(CSLPageScrollView *)arg1 percentage:(float)arg2;
- (void)scrollViewDidDelete:(CSLPageScrollView *)arg1 index:(unsigned int)arg2;
- (void)scrollViewDidAddToFavorites:(CSLPageScrollView *)arg1 index:(unsigned int)arg2;
- (void)scrollViewDidReorder:(CSLPageScrollView *)arg1 fromIndex:(unsigned int)arg2 toIndex:(unsigned int)arg3;
- (void)scrollViewWasTapped:(CSLPageScrollView *)arg1;
- (void)scrollViewDidFinishOffsetAnimation:(CSLPageScrollView *)arg1;
- (void)scrollViewDidSettle:(CSLPageScrollView *)arg1;
- (void)scrollViewDidScroll:(CSLPageScrollView *)arg1 scale:(float)arg2;
- (void)scrollViewDidReachLayout:(unsigned int)arg1;
- (UIView *)iconViewForPageAtIndex:(unsigned int)arg1;
- (NSString *)ephemeralTitleForPageAtIndex:(unsigned int)arg1;
- (_Bool)shouldShowEphemeralTitleForPageAtIndex:(unsigned int)arg1;
- (NSString *)titleForPageAtIndex:(unsigned int)arg1;
- (_Bool)ephemeralPageAtIndex:(unsigned int)arg1;
- (_Bool)canAddPageAtIndex:(unsigned int)arg1;
- (_Bool)canReorderPageAtIndex:(unsigned int)arg1;
@end

