//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLPPTTest.h"

@class NSString;

@interface CSLPPTMessagesReplyTest : CSLPPTTest
{
    NSString *_testName;
    _Bool _presentedNotification;
}

+ (id)testPrefix;
- (void).cxx_destruct;
- (void)failTestWithReason:(id)arg1;
- (void)runTest:(id)arg1;

@end

