//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSString, UIImage, UIImageView, UILabel, UIView;

@interface CSLPageRemoveButton : UIButton
{
    NSString *_text;
    UIImage *_image;
    UILabel *_labelView;
    UIImageView *_iconView;
    UIView *_containerView;
}

@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UILabel *labelView; // @synthesize labelView=_labelView;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (void)_updateForImageChange;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void)_updateForTextChange;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

