//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface CSLPrelaunchBlackListLaunchEntry : NSObject
{
    NSDate *_lastLaunch;
    unsigned int _consecutiveFailedLaunches;
}

@property(nonatomic) unsigned int consecutiveFailedLaunches; // @synthesize consecutiveFailedLaunches=_consecutiveFailedLaunches;
@property(retain, nonatomic) NSDate *lastLaunch; // @synthesize lastLaunch=_lastLaunch;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

