//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLPPTTest.h"

@interface CSLPPTScrubTimeTravelOnFaceTest : CSLPPTTest
{
}

+ (id)testPrefix;
- (void)_clockTimeTravelScrubToDate:(id)arg1 interval:(double)arg2 iterations:(unsigned int)arg3 testName:(id)arg4;
- (void)runTest:(id)arg1;

@end

