//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSRecursiveLock;

@interface CSLPrelaunchAssertionStore : NSObject
{
    NSRecursiveLock *_lock;
    NSMutableDictionary *_assertions;
}

@property(retain, nonatomic) NSMutableDictionary *assertions; // @synthesize assertions=_assertions;
@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
- (void).cxx_destruct;
- (void)invalidateAll;
- (void)removeAssertion:(id)arg1;
- (void)removeAssertionForBundleID:(id)arg1;
- (id)assertionForBundleID:(id)arg1;
- (_Bool)assertionExistsForBundleID:(id)arg1;
- (void)addAssertion:(id)arg1 forBundleID:(id)arg2;
- (void)_withLock:(CDUnknownBlockType)arg1;
- (id)init;

@end

