//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CSLReorderingAnimationEngineDelegate.h"
#import "PUICCrownInputSequencerDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class CSLPIDispatchTimer, CSLPageDotsView, CSLPageRemoveButton, CSLPageSeparatorView, CSLPageTitleView, CSLPageViewCentering, CSLPillTitleView, CSLReorderingAnimationEngine, CSLZeroDelayPanGestureRecognizer, NSArray, NSString, NSTimer, PUICContentUnavailableView, PUICCrownInputSequencer, UIButton, UILongPressGestureRecognizer, UITapGestureRecognizer;

@interface CSLPageScrollView : UIView <PUICCrownInputSequencerDelegate, UIGestureRecognizerDelegate, CSLReorderingAnimationEngineDelegate>
{
    float _lastHorizontalPanTranslation;
    double _lastHorizontalPanInteractionTimestamp;
    float _horizontalPanVelocity;
    float _initialHorizontalPanPageOffset;
    struct CGPoint _initialHorizontalPanTouchLocation;
    float _lastVerticalPanTranslation;
    double _lastVerticalPanInteractionTimestamp;
    float _verticalPanVelocity;
    struct CGPoint _initialScrubLocation;
    _Bool _hasReachedMinimumMovementThresholdForScrubbing;
    unsigned int _initialReorderingIndex;
    unsigned int _reorderingIndex;
    struct CGPoint _normalizedReorderingItemTouchLocation;
    struct CGPoint _normalizedReorderingItemTouchOffset;
    _Bool _hasScheduledFirstTimerSinceLongPress;
    _Bool _isAnimatingReordering;
    double _lastRearrangeInteractionTimestamp;
    float _lastRearrangeTranslation;
    float _rearrangeTranslationVelocity;
    NSTimer *_rearrangeTimer;
    struct _NSRange _rearrangeablePagesRange;
    CSLPageSeparatorView *_reorderCursorSeparator;
    float _addModePresentationFraction;
    CSLPIDispatchTimer *_addModeTimer;
    PUICCrownInputSequencer *_crownInputSequencer;
    struct InertialDynamicValue<float> _itemOffsetAnimator;
    struct InertialDynamicValue<float> _deleteModePresentationFractionAnimator;
    struct AdditiveDynamicValue<float __attribute__((ext_vector_type(2)))> _pageLayoutParametersAnimator;
    struct AdditiveDynamicValue<float> _addModePresentationFractionAnimator;
    int _scrollViewSettingsChangedToken;
    _Bool _trackingHorizontalPan;
    _Bool _deleteModePresentationFractionHold;
    _Bool _onScreen;
    float _pageOffset;
    float _deleteModePresentationFraction;
    unsigned int _pageLayout;
    NSArray *_pageViews;
    id <CSLPageScrollViewDelegate> _delegate;
    CSLZeroDelayPanGestureRecognizer *_horizontalPanGestureRecognizer;
    CSLZeroDelayPanGestureRecognizer *_verticalPanGestureRecognizer;
    CSLZeroDelayPanGestureRecognizer *_scrubPanGestureRecognizer;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    UITapGestureRecognizer *_tapGestureRecognizer;
    float _pageLayoutScale;
    float _pageLayoutTargetScale;
    float _pageLayoutMinY;
    float _pageLayoutTargetMinY;
    unsigned int _numberOfPages;
    CSLPageDotsView *_pageDotsView;
    CSLPageRemoveButton *_removeButton;
    UIButton *_deleteCancelButton;
    UIButton *_actionAddButton;
    CSLPageTitleView *_titleView;
    CSLPageTitleView *_addModeTitleView;
    CSLPillTitleView *_pillTitleView;
    PUICContentUnavailableView *_contentUnavailableView;
    CSLPageViewCentering *_centering;
    CSLReorderingAnimationEngine *_reorderingAnimationEngine;
}

+ (void)initialize;
@property(retain, nonatomic) CSLReorderingAnimationEngine *reorderingAnimationEngine; // @synthesize reorderingAnimationEngine=_reorderingAnimationEngine;
@property(retain, nonatomic) CSLPageViewCentering *centering; // @synthesize centering=_centering;
@property(retain, nonatomic) PUICContentUnavailableView *contentUnavailableView; // @synthesize contentUnavailableView=_contentUnavailableView;
@property(retain, nonatomic) CSLPillTitleView *pillTitleView; // @synthesize pillTitleView=_pillTitleView;
@property(retain, nonatomic) CSLPageTitleView *addModeTitleView; // @synthesize addModeTitleView=_addModeTitleView;
@property(retain, nonatomic) CSLPageTitleView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) UIButton *actionAddButton; // @synthesize actionAddButton=_actionAddButton;
@property(retain, nonatomic) UIButton *deleteCancelButton; // @synthesize deleteCancelButton=_deleteCancelButton;
@property(retain, nonatomic) CSLPageRemoveButton *removeButton; // @synthesize removeButton=_removeButton;
@property(retain, nonatomic) CSLPageDotsView *pageDotsView; // @synthesize pageDotsView=_pageDotsView;
@property(readonly, nonatomic, getter=isOnScreen) _Bool onScreen; // @synthesize onScreen=_onScreen;
@property(nonatomic) unsigned int numberOfPages; // @synthesize numberOfPages=_numberOfPages;
@property(nonatomic) _Bool deleteModePresentationFractionHold; // @synthesize deleteModePresentationFractionHold=_deleteModePresentationFractionHold;
@property(nonatomic) float pageLayoutTargetMinY; // @synthesize pageLayoutTargetMinY=_pageLayoutTargetMinY;
@property(nonatomic) float pageLayoutMinY; // @synthesize pageLayoutMinY=_pageLayoutMinY;
@property(nonatomic) float pageLayoutTargetScale; // @synthesize pageLayoutTargetScale=_pageLayoutTargetScale;
@property(nonatomic) float pageLayoutScale; // @synthesize pageLayoutScale=_pageLayoutScale;
@property(readonly, nonatomic, getter=isTrackingHorizontalPan) _Bool trackingHorizontalPan; // @synthesize trackingHorizontalPan=_trackingHorizontalPan;
@property(readonly, nonatomic) PUICCrownInputSequencer *crownInputSequencer; // @synthesize crownInputSequencer=_crownInputSequencer;
@property(readonly, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(readonly, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(readonly, nonatomic) CSLZeroDelayPanGestureRecognizer *scrubPanGestureRecognizer; // @synthesize scrubPanGestureRecognizer=_scrubPanGestureRecognizer;
@property(readonly, nonatomic) CSLZeroDelayPanGestureRecognizer *verticalPanGestureRecognizer; // @synthesize verticalPanGestureRecognizer=_verticalPanGestureRecognizer;
@property(readonly, nonatomic) CSLZeroDelayPanGestureRecognizer *horizontalPanGestureRecognizer; // @synthesize horizontalPanGestureRecognizer=_horizontalPanGestureRecognizer;
@property(nonatomic) __weak id <CSLPageScrollViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSArray *pageViews; // @synthesize pageViews=_pageViews;
@property(nonatomic) unsigned int pageLayout; // @synthesize pageLayout=_pageLayout;
@property(nonatomic) float deleteModePresentationFraction; // @synthesize deleteModePresentationFraction=_deleteModePresentationFraction;
@property(nonatomic) float pageOffset; // @synthesize pageOffset=_pageOffset;
- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned int)_canReorderLastPage;
- (void)_recalculateRearrangeablePageRange;
- (void)_performAnimatedLayout;
- (void)_handleRearrangeTimer:(id)arg1;
- (void)_teardownRearrangeTimer;
- (void)_scheduleRearrangeTimerIfNecessary;
- (float)_currentRearrangeSpeed;
- (void)_animateOutReorderCursor;
- (void)_animateInReorderCursor;
- (void)_animateOutPillTitleView;
- (void)_animateInPillTitleView;
- (void)_animateInTitleView;
- (void)_animateOutTitleView;
- (void)_handleLongPressGestureRecognizer:(id)arg1;
- (void)_handleScrubPanGestureRecognizer:(id)arg1;
- (void)_handleVerticalPanGestureRecognizer:(id)arg1;
- (void)_handleHorizontalPanGestureRecognizer:(id)arg1;
- (void)handleTapGesture:(id)arg1;
- (void)_handleDeleteCancelTap:(id)arg1;
- (void)_handleRemoveButtonTap:(id)arg1;
- (void)blacklistAnimationsForRemovedPage:(id)arg1;
- (void)_clearBlacklist;
- (void)_handleActionAddButtonTap:(id)arg1;
- (_Bool)handleCrownEvent;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)reorderingAnimationEngine:(id)arg1 finishedAnimation:(id)arg2;
- (void)crownInputSequencerOffsetDidChange:(id)arg1;
- (void)layoutSubviews;
- (struct CGRect)buildReorderCursorFrameFromRect:(struct CGRect)arg1;
- (struct CGRect)frameForReorderingPageAtIndex:(unsigned int)arg1 size:(struct CGSize)arg2 offset:(float)arg3 origin:(struct CGPoint)arg4;
- (struct _NSRange)visiblePageRangeForOffset:(float)arg1 andNumberOfPages:(unsigned int)arg2;
- (struct _NSRange)visiblePageRange;
@property(readonly, nonatomic) int centeredPageIndex;
- (void)buildAnimationsFromRange:(struct _NSRange)arg1 inPageViews:(id)arg2 toRange:(struct _NSRange)arg3 inPageViews:(id)arg4 oldCenter:(int)arg5 newCenter:(int)arg6;
- (void)setPageViews:(id)arg1 animated:(_Bool)arg2;
- (void)_addModeTimerFired;
- (void)_scheduleAddModeTimerIfNecessary;
- (void)_cancelAddModeTimerIfNecessary;
- (void)_cancelAddModeTimer;
- (float)_addModePositionFraction;
- (void)setAddModePresentationFraction:(float)arg1;
- (void)_setAddModePresentationFractionImmediately:(float)arg1;
- (void)updateDeleteModePresentationFraction:(float)arg1;
- (void)_setDeleteModePresentationFractionImmediately:(float)arg1;
- (void)stopDeceleratingAndSetPageOffset:(float)arg1;
- (void)_setItemOffsetAnimatorAnimating:(_Bool)arg1;
- (void)setPageLayout:(unsigned int)arg1 animated:(_Bool)arg2;
- (void)_updateGesturesForPageLayout;
-     // Error parsing type: 12@0:4I8, name: _layoutParametersForPageLayout:
- (void)handleDidDisappear;
- (void)handleWillDisappear;
- (void)handleDidAppear;
- (void)_readDefaults;
- (void)_registerDefaults;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

