//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLUICarouselApplicationStoreListener.h"
#import "FBApplicationProcessObserver.h"
#import "FBProcessManagerObserver.h"

@class CSLSafeMutableSet, NSMutableDictionary, NSMutableSet, NSString;

@interface CSLPrelaunchBlacklist : NSObject <FBProcessManagerObserver, FBApplicationProcessObserver, CSLUICarouselApplicationStoreListener>
{
    NSMutableSet *_blacklist;
    NSMutableDictionary *_launchlist;
    CSLSafeMutableSet *_observers;
    double _maximumBackoffTime;
    double _backoffTime;
    struct _opaque_pthread_mutex_t _blacklistLock;
}

+ (id)sharedInstance;
@property(nonatomic) struct _opaque_pthread_mutex_t blacklistLock; // @synthesize blacklistLock=_blacklistLock;
@property double backoffTime; // @synthesize backoffTime=_backoffTime;
@property double maximumBackoffTime; // @synthesize maximumBackoffTime=_maximumBackoffTime;
@property(retain, nonatomic) CSLSafeMutableSet *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) NSMutableDictionary *launchlist; // @synthesize launchlist=_launchlist;
@property(retain, nonatomic) NSMutableSet *blacklist; // @synthesize blacklist=_blacklist;
- (void).cxx_destruct;
- (void)applicationStore:(id)arg1 addedBundleIDs:(id)arg2 removedBundleIDs:(id)arg3 modifiedBundleIDs:(id)arg4;
- (void)applicationProcessDidExit:(id)arg1 withContext:(id)arg2;
- (void)applicationProcessDidLaunch:(id)arg1;
- (void)applicationProcessDidFailToLaunch:(id)arg1;
- (void)processManager:(id)arg1 didRemoveProcess:(id)arg2;
- (void)processManager:(id)arg1 didAddProcess:(id)arg2;
- (id)_nextPermittedLaunchDateForLaunchEntry:(id)arg1;
- (_Bool)_isTemporarilyBlacklisted:(id)arg1;
- (void)_resetLaunch:(id)arg1;
- (id)_recordExit:(id)arg1 reason:(unsigned int)arg2;
- (id)_recordLaunch:(id)arg1;
- (void)_addToBlacklist:(id)arg1;
- (void)_withLock:(CDUnknownBlockType)arg1;
- (void)_loadPreferences;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1 callbackQueue:(id)arg2;
- (void)removeFromBlacklist:(id)arg1;
- (_Bool)contains:(id)arg1;
- (void)dealloc;
- (id)_init;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

