//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CADisplayLink;

@interface CSLQuiescingDisplayLink : NSObject
{
    CADisplayLink *_displayLink;
    CDUnknownBlockType _callback;
    CDUnknownBlockType _canQueiescePredicate;
    _Bool _needsForcedUpdate;
    CDUnknownBlockType _quiescentDidChangeHandler;
}

@property(copy, nonatomic) CDUnknownBlockType quiescentDidChangeHandler; // @synthesize quiescentDidChangeHandler=_quiescentDidChangeHandler;
- (void).cxx_destruct;
- (void)_updateDisplayLink;
- (void)_displayLinkFired:(id)arg1;
@property(nonatomic) int frameInterval;
@property(nonatomic) _Bool paused;
- (void)setCanQueiescePredicate:(CDUnknownBlockType)arg1;
- (void)tick:(double)arg1;
- (void)setNeedsUpdate:(_Bool)arg1;
- (void)invalidate;
- (id)initWithCallback:(CDUnknownBlockType)arg1 canQueiescePredicate:(CDUnknownBlockType)arg2;

@end

