//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLReorderingAnimationDelegate.h"

@class NSMapTable, NSMutableArray, NSString;

@interface CSLReorderingAnimationEngine : NSObject <CSLReorderingAnimationDelegate>
{
    id <CSLReorderingAnimationEngineDelegate> _delegate;
    NSMutableArray *_offsetAnimations;
    NSMapTable *_offsetAnimationMapTable;
    NSMutableArray *_scaleAnimations;
    NSMapTable *_scaleAnimationMapTable;
    NSMutableArray *_fadeAnimations;
    NSMutableArray *_blacklistedViews;
    NSMutableArray *_addingViews;
}

+ (id)reorderingAnimationEngineWithDelegate:(id)arg1;
@property(retain, nonatomic) NSMutableArray *addingViews; // @synthesize addingViews=_addingViews;
@property(retain, nonatomic) NSMutableArray *blacklistedViews; // @synthesize blacklistedViews=_blacklistedViews;
@property(retain, nonatomic) NSMutableArray *fadeAnimations; // @synthesize fadeAnimations=_fadeAnimations;
@property(retain, nonatomic) NSMapTable *scaleAnimationMapTable; // @synthesize scaleAnimationMapTable=_scaleAnimationMapTable;
@property(retain, nonatomic) NSMutableArray *scaleAnimations; // @synthesize scaleAnimations=_scaleAnimations;
@property(retain, nonatomic) NSMapTable *offsetAnimationMapTable; // @synthesize offsetAnimationMapTable=_offsetAnimationMapTable;
@property(retain, nonatomic) NSMutableArray *offsetAnimations; // @synthesize offsetAnimations=_offsetAnimations;
@property(nonatomic) __weak id <CSLReorderingAnimationEngineDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setNeedsLayout;
- (void)scaleAnimationDidFinish:(id)arg1;
- (void)fadeAnimationDidFinish:(id)arg1;
- (void)offsetAnimationDidFinish:(id)arg1;
- (void)animationDidFinish:(id)arg1;
- (void)addScaleAnimation:(id)arg1 toView:(id)arg2;
- (void)addAddAnimation:(id)arg1 toView:(id)arg2;
- (void)addFadeAnimation:(id)arg1 toView:(id)arg2;
- (void)addOffsetAnimation:(id)arg1 toView:(id)arg2;
- (void)addAnimation:(id)arg1 toView:(id)arg2;
- (void)clearBlacklist;
- (void)addBlacklistedView:(id)arg1;
- (void)clearAddAnimationsWithBlock:(CDUnknownBlockType)arg1;
- (_Bool)hasAddAnimationForView:(id)arg1;
- (void)scaleAnimationForView:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)enumerateFadeAnimationsWithBlock:(CDUnknownBlockType)arg1;
- (float)offsetForView:(id)arg1;
- (_Bool)hasAnimationForView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

