//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CSLRearrangeTimerInfo : NSObject
{
    float _rearrangeSpeed;
    double _timerDuration;
}

+ (id)timerInfoWithRearrangeSpeed:(float)arg1 timerDuration:(double)arg2;
@property(nonatomic) double timerDuration; // @synthesize timerDuration=_timerDuration;
@property(nonatomic) float rearrangeSpeed; // @synthesize rearrangeSpeed=_rearrangeSpeed;
- (id)initWithRearrangeSpeed:(float)arg1 timerDuration:(double)arg2;

@end

