//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLSnapshotActivityControllerState.h"

@class CSLSnapshotActivityController, NSString, _DASActivity;

@interface CSLSnapshotActivityControllerSuspendedState : NSObject <CSLSnapshotActivityControllerState>
{
    _Bool _needsScheduleEvaluation;
    _Bool _didExhaustSchedule;
    CSLSnapshotActivityController *_activityController;
    _DASActivity *_pendingActivity;
}

@property(nonatomic) _Bool didExhaustSchedule; // @synthesize didExhaustSchedule=_didExhaustSchedule;
@property(nonatomic) _Bool needsScheduleEvaluation; // @synthesize needsScheduleEvaluation=_needsScheduleEvaluation;
@property(retain, nonatomic) _DASActivity *pendingActivity; // @synthesize pendingActivity=_pendingActivity;
@property(nonatomic) __weak CSLSnapshotActivityController *activityController; // @synthesize activityController=_activityController;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (void)suspendFromState:(id)arg1;
- (void)snapshotScheduleExhausted;
- (void)didApplySnapshotSchedule:(id)arg1;
- (void)didCompleteSnapshotForSchedule:(id)arg1;
- (void)activityStarted:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

