//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLStatusOverlayAssertion, NSString;

@protocol CSLStatusOverlayAssertionDelegate <NSObject>
- (void)assertionDidActivate:(CSLStatusOverlayAssertion *)arg1;
- (void)assertion:(CSLStatusOverlayAssertion *)arg1 didUpdateStatusString:(NSString *)arg2;
- (void)assertionDidInvalidate:(CSLStatusOverlayAssertion *)arg1;
@end

