//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLReorderingAnimation.h"

@class PUICAdditiveValueAnimator;

@interface CSLScaleAnimation : CSLReorderingAnimation
{
    float _fromScale;
    float _toScale;
    float _fraction;
    PUICAdditiveValueAnimator *_additiveValueAnimator;
    float _duration;
}

+ (id)scaleAnimationFromScale:(float)arg1 toScale:(float)arg2 duration:(float)arg3;
@property(nonatomic) float duration; // @synthesize duration=_duration;
@property(retain, nonatomic) PUICAdditiveValueAnimator *additiveValueAnimator; // @synthesize additiveValueAnimator=_additiveValueAnimator;
@property(nonatomic) float fraction; // @synthesize fraction=_fraction;
@property(nonatomic) float toScale; // @synthesize toScale=_toScale;
@property(nonatomic) float fromScale; // @synthesize fromScale=_fromScale;
- (void).cxx_destruct;
- (void)startAnimating;
- (void)animator:(id)arg1 setFraction:(float)arg2;
- (void)buildAnimator;

@end

