//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLSSnapshotRequest, CSLSSnapshotScheduleItem, FBSSceneSnapshotContext, FBScene, IOSSHLApplication, NSString;

@protocol CSLSnapshotServiceSystemProtocol <NSObject>
- (void)performSnapshotForApp:(IOSSHLApplication *)arg1 scene:(FBScene *)arg2 reason:(unsigned int)arg3 context:(FBSSceneSnapshotContext *)arg4 completion:(void (^)(int))arg5;
- (void)initiateSnapshot:(NSString *)arg1 request:(CSLSSnapshotRequest *)arg2 item:(CSLSSnapshotScheduleItem *)arg3 launchIfNeeded:(_Bool)arg4 completion:(void (^)(NSString *, NSError *))arg5;
- (void)initiateSnapshot:(NSString *)arg1 launchIfNeeded:(_Bool)arg2 completion:(void (^)(NSString *, NSError *))arg3;
- (void)scheduleSystemSnapshot:(NSString *)arg1;
@end

