//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLStatusBarStateAggregatorPosting.h"
#import "UIStatusBarStateProvider.h"

@class CSLStatusBarStateAggregator, NSHashTable, NSString;

@interface CSLStatusBarStateProvider : NSObject <CSLStatusBarStateAggregatorPosting, UIStatusBarStateProvider>
{
    CSLStatusBarStateAggregator *_stateAggregator;
    NSHashTable *_stateObservers;
    CDStruct_5e10f1a5 _aggregatorData;
    int _aggregatorActions;
    CDStruct_5e10f1a5 _lastPost;
    unsigned int _coalescentBlockDepth;
    _Bool _itemNeedsPost[32];
    _Bool _anyItemNeedsPost;
    _Bool _posting;
}

- (void).cxx_destruct;
- (void)statusBarStateAggregatorDidFinishPost:(id)arg1 withData:(const CDStruct_5e10f1a5 *)arg2 actions:(int)arg3;
- (void)statusBarStateAggregator:(id)arg1 didVisitItem:(int)arg2 withUpdates:(_Bool)arg3 toData:(const CDStruct_5e10f1a5 *)arg4;
- (void)statusBarStateAggregatorDidStartPost:(id)arg1;
- (void)_composePostActionsFromAggregatorActions:(int *)arg1;
- (void)_composePostDataFromAggregatorData:(CDStruct_5e10f1a5 *)arg1;
- (_Bool)_shouldPostForVisitedItem:(int)arg1 withUpdates:(_Bool)arg2 toAggregatorData:(const CDStruct_5e10f1a5 *)arg3;
- (void)updateStatusBarItem:(int)arg1;
- (void)endCoalescentBlock;
- (void)beginCoalescentBlock;
- (void)getStatusBarData:(CDStruct_5e10f1a5 *)arg1;
- (void)removeStatusBarStateObserver:(id)arg1;
- (void)addStatusBarStateObserver:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

