//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol CSLScreenEdgeCoordinatingDelegate <NSObject>
- (void)coordinatedControllerDidDismiss:(id <CSLScreenEdgeCoordinating>)arg1;
- (void)coordinatedControllerWillDismiss:(id <CSLScreenEdgeCoordinating>)arg1;
- (void)coordinatedControllerDidPresent:(id <CSLScreenEdgeCoordinating>)arg1;
- (void)coordinatedControllerWillPresent:(id <CSLScreenEdgeCoordinating>)arg1;
@end

