//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLIconPositionsStore, CSLModalAppManager, NSString;

@interface CSLStoreDemoSupport : NSObject
{
    int _fProgramNumber;
    _Bool _isDemoDevice;
    _Bool _hasDemoMovie;
    _Bool _shouldRunNanoDemo;
    _Bool _shouldActivateDemoApp;
    CSLIconPositionsStore *_iconPositionsStore;
    NSString *_demoBundleIdentifier;
    CSLModalAppManager *_demoAppManager;
}

+ (id)sharedInstance;
@property(retain, nonatomic) CSLModalAppManager *demoAppManager; // @synthesize demoAppManager=_demoAppManager;
@property(readonly, nonatomic) NSString *demoBundleIdentifier; // @synthesize demoBundleIdentifier=_demoBundleIdentifier;
@property(nonatomic) _Bool shouldActivateDemoApp; // @synthesize shouldActivateDemoApp=_shouldActivateDemoApp;
@property(nonatomic) __weak CSLIconPositionsStore *iconPositionsStore; // @synthesize iconPositionsStore=_iconPositionsStore;
- (void).cxx_destruct;
- (_Bool)isOrShouldBeRunning;
- (void)_activateDemoApp;
- (void)resetIconLayout;
- (void)_handleStartPlayingDemoMovie;
- (void)demoAppExited;
- (void)demoAppActivated;
- (void)applicationDidFinishLaunching;
@property(readonly, nonatomic, getter=isMovieDemo) _Bool movieDemo;
@property(readonly, nonatomic, getter=isStandAloneDemo) _Bool standAloneDemo;
@property(readonly, nonatomic, getter=isTetheredDemo) _Bool tetheredDemo;
@property(readonly, nonatomic, getter=isDemoDevice) _Bool demoDevice;
- (id)init;

@end

