//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLSnapshotActivityManagerDelegate.h"
#import "CSLSnapshotServiceAppProtocol.h"
#import "CSLSnapshotServiceInternalProtocol.h"
#import "CSLSnapshotServiceSystemProtocol.h"

@class CSLAppPrelauncher, CSLSafeMutableDictionary, CSLSnapshotActivityManager, CSLSnapshotComplicationPolicy, CSLSnapshotContextManager, CSLSnapshotServiceEndpoint, NSMutableSet, NSString;

@interface CSLSnapshotService : NSObject <CSLSnapshotActivityManagerDelegate, CSLSnapshotServiceAppProtocol, CSLSnapshotServiceSystemProtocol, CSLSnapshotServiceInternalProtocol>
{
    CSLSafeMutableDictionary *_snapshotCompletionBlocks;
    CSLSnapshotActivityManager *_snapshotActivityManager;
    CSLSnapshotServiceEndpoint *_endpoint;
    NSMutableSet *_snapshotsInProgress;
    CSLSnapshotComplicationPolicy *_complicationPolicy;
    CSLSnapshotContextManager *_snapshotContextManager;
    CSLAppPrelauncher *_prelauncher;
    double _returnToPrimaryUIInterval;
    double _returnToPrimaryUILeeway;
}

+ (id)sharedInstance;
+ (_Bool)_useDelay:(unsigned int)arg1;
+ (void)triggerWithDelay:(unsigned int)arg1 tag:(id)arg2;
+ (unsigned int)getTriggerDelay;
+ (void)setTriggerDelay:(unsigned int)arg1;
+ (void)_withDelayLock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) CSLAppPrelauncher *prelauncher; // @synthesize prelauncher=_prelauncher;
@property(retain, nonatomic) CSLSnapshotContextManager *snapshotContextManager; // @synthesize snapshotContextManager=_snapshotContextManager;
@property(retain, nonatomic) CSLSnapshotComplicationPolicy *complicationPolicy; // @synthesize complicationPolicy=_complicationPolicy;
@property(nonatomic) double returnToPrimaryUILeeway; // @synthesize returnToPrimaryUILeeway=_returnToPrimaryUILeeway;
@property(nonatomic) double returnToPrimaryUIInterval; // @synthesize returnToPrimaryUIInterval=_returnToPrimaryUIInterval;
@property(retain, nonatomic) NSMutableSet *snapshotsInProgress; // @synthesize snapshotsInProgress=_snapshotsInProgress;
@property(retain, nonatomic) CSLSnapshotServiceEndpoint *endpoint; // @synthesize endpoint=_endpoint;
@property(retain, nonatomic) CSLSnapshotActivityManager *snapshotActivityManager; // @synthesize snapshotActivityManager=_snapshotActivityManager;
@property(retain, nonatomic) CSLSafeMutableDictionary *snapshotCompletionBlocks; // @synthesize snapshotCompletionBlocks=_snapshotCompletionBlocks;
- (void).cxx_destruct;
- (void)_recordSnapshotRequestedForBundleID:(id)arg1 reason:(unsigned int)arg2;
- (void)_recordSnapshotInitiatedForBundleID:(id)arg1 error:(id)arg2;
- (void)getScheduleWithCallbackQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)snapshotActivityManager:(id)arg1 shouldBeginActivity:(id)arg2;
- (void)scheduleSystemSnapshot:(id)arg1;
- (void)processSnapshotRequest:(id)arg1 reason:(unsigned int)arg2 forBundleID:(id)arg3;
- (void)scheduleAppSnapshot:(id)arg1 date:(id)arg2 userInfo:(id)arg3;
- (void)invalidateSnapshotForBundleID:(id)arg1;
- (void)performSnapshotForApp:(id)arg1 scene:(id)arg2 reason:(unsigned int)arg3 context:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)_sendSnapshotActionToApp:(id)arg1 withSettings:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)initiateSnapshot:(id)arg1 request:(id)arg2 item:(id)arg3 launchIfNeeded:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (void)initiateSnapshot:(id)arg1 launchIfNeeded:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)shouldSnapshot:(id)arg1;
- (id)init;
- (id)initWithConfiguration:(id)arg1;
- (void)_loadPreferences;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

