//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLKComplicationObserver.h"

@class CLKComplicationObserver, CSLSnapshotService, NSString;

@interface CSLSnapshotComplicationPolicy : NSObject <CLKComplicationObserver>
{
    CLKComplicationObserver *_complicationObserver;
    CSLSnapshotService *_snapshotService;
}

@property(nonatomic) __weak CSLSnapshotService *snapshotService; // @synthesize snapshotService=_snapshotService;
@property(nonatomic) __weak CLKComplicationObserver *complicationObserver; // @synthesize complicationObserver=_complicationObserver;
- (void).cxx_destruct;
- (void)complicationDidReloadOrExtendForBundleIdentifier:(id)arg1;
- (void)dealloc;
- (id)initWithComplicationObserver:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

