//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BSDescriptionProviding.h"
#import "NSObject.h"

@class CSLSnapshotActivitySchedule, _DASActivity;

@protocol CSLSnapshotActivityControllerState <NSObject, BSDescriptionProviding>
- (void)snapshotScheduleExhausted;
- (void)didApplySnapshotSchedule:(CSLSnapshotActivitySchedule *)arg1;
- (void)didCompleteSnapshotForSchedule:(CSLSnapshotActivitySchedule *)arg1;
- (void)activityStarted:(_DASActivity *)arg1;
@end

