//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CSLPageScrollViewPage.h"

@class NSString, UIImageView;

@interface CSLSwitcherViewControllerView : UIView <CSLPageScrollViewPage>
{
    NSString *_identifier;
    UIView *_containerView;
    UIImageView *_platterKeylineImageView;
    UIView *_contentContainerView;
    UIView *_touchOcclusionView;
}

@property(nonatomic) __weak UIView *touchOcclusionView; // @synthesize touchOcclusionView=_touchOcclusionView;
@property(nonatomic) __weak UIView *contentContainerView; // @synthesize contentContainerView=_contentContainerView;
@property(nonatomic) __weak UIImageView *platterKeylineImageView; // @synthesize platterKeylineImageView=_platterKeylineImageView;
@property(nonatomic) __weak UIView *containerView; // @synthesize containerView=_containerView;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)insertSubview:(id)arg1 aboveSubview:(id)arg2;
- (void)insertSubview:(id)arg1 belowSubview:(id)arg2;
- (void)exchangeSubviewAtIndex:(int)arg1 withSubviewAtIndex:(int)arg2;
- (void)insertSubview:(id)arg1 atIndex:(int)arg2;
- (void)addSubview:(id)arg1;
- (struct CGAffineTransform)addButtonTransform:(_Bool)arg1;
- (void)layoutSubviews;
- (void)setClipsToBounds:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

