//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class CSLSSnapshotRequest, NSDate, NSString;

@interface CSLSnapshotActivitySchedule : NSObject <BSDescriptionProviding>
{
    CSLSSnapshotRequest *_snapshotRequest;
    NSString *_bundleID;
    NSDate *_lastScheduledDate;
}

@property(copy, nonatomic) NSDate *lastScheduledDate; // @synthesize lastScheduledDate=_lastScheduledDate;
@property(copy, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(retain, nonatomic) CSLSSnapshotRequest *snapshotRequest; // @synthesize snapshotRequest=_snapshotRequest;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (unsigned int)indexOfBestScheduleItemForDate:(id)arg1 laterThanDate:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

