//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, UIViewController;

@interface CSLSwitcherViewControllersFactory : NSObject
{
    NSMutableDictionary *_viewControllersByIdentifier;
    UIViewController *_launcherViewController;
    UIViewController *_clockViewController;
}

@property(retain, nonatomic) UIViewController *clockViewController; // @synthesize clockViewController=_clockViewController;
@property(retain, nonatomic) UIViewController *launcherViewController; // @synthesize launcherViewController=_launcherViewController;
- (void).cxx_destruct;
- (id)_createContainerPageViewControllerForItem:(id)arg1 withContainee:(id)arg2;
- (id)_createViewControllerForItem:(id)arg1;
- (void)purgeInvalidItems:(id)arg1;
- (id)viewControllerForItem:(id)arg1;
- (id)init;

@end

