//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIGestureRecognizerDelegate.h"

@class CSLScreenEdgePanGestureRecognizer;

@protocol CSLScreenEdgeCoordinating <UIGestureRecognizerDelegate>
@property(readonly, nonatomic) _Bool isPresented;
@property(readonly, nonatomic) unsigned int edge;
@property(retain, nonatomic) CSLScreenEdgePanGestureRecognizer *hideGestureRecognizer;
@property(retain, nonatomic) CSLScreenEdgePanGestureRecognizer *showGestureRecognizer;
@property(nonatomic) __weak id <CSLScreenEdgeCoordinatingDelegate> presentationCoordinator;
- (void)dismissAnimated:(_Bool)arg1;
- (void)presentAnimated:(_Bool)arg1;
- (void)handleScreenEdgePanGestureRecognizer:(CSLScreenEdgePanGestureRecognizer *)arg1;
@end

