//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BSTransaction, NSString, NSURL;

@interface CSLStuckTransactionContext : NSObject
{
    _Bool _shouldBlueScreenOnInternalInstalls;
    _Bool _shouldStackshotTwice;
    _Bool _engineeringRequestsLiveDebugging;
    unsigned int _categorization;
    NSString *_categorizationString;
    BSTransaction *_transaction;
    NSString *_radarNumber;
    NSURL *_logFileURL;
}

@property(retain, nonatomic) NSURL *logFileURL; // @synthesize logFileURL=_logFileURL;
@property(readonly, nonatomic) _Bool engineeringRequestsLiveDebugging; // @synthesize engineeringRequestsLiveDebugging=_engineeringRequestsLiveDebugging;
@property(readonly, nonatomic) _Bool shouldStackshotTwice; // @synthesize shouldStackshotTwice=_shouldStackshotTwice;
@property(nonatomic) _Bool shouldBlueScreenOnInternalInstalls; // @synthesize shouldBlueScreenOnInternalInstalls=_shouldBlueScreenOnInternalInstalls;
@property(readonly, nonatomic) NSString *radarNumber; // @synthesize radarNumber=_radarNumber;
@property(retain, nonatomic) BSTransaction *transaction; // @synthesize transaction=_transaction;
@property(retain, nonatomic) NSString *categorizationString; // @synthesize categorizationString=_categorizationString;
@property(nonatomic) unsigned int categorization; // @synthesize categorization=_categorization;
- (void).cxx_destruct;
- (id)init;
- (id)initWithStuckTransaction:(id)arg1;

@end

