//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BSBaseXPCServer.h"

@class NSLock, NSMutableArray;

@interface CSLSuspendSystemGestureAssertionsXPCServer : BSBaseXPCServer
{
    id <CSLSSuspendSystemGestureAssertionProvider> _provider;
    NSMutableArray *_assertions;
    NSLock *_lock;
}

- (void).cxx_destruct;
- (void)_handleReleaseAssertionMessage:(id)arg1 forClient:(id)arg2;
- (void)_handleTakeAssertionMessage:(id)arg1 forClient:(id)arg2;
- (void)queue_handleMessage:(id)arg1 client:(id)arg2;
- (void)queue_clientRemoved:(id)arg1;
- (void)queue_clientAdded:(id)arg1;
- (Class)queue_classForNewClientConnection:(id)arg1;
- (id)initWithProvider:(id)arg1;

@end

