//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class BKSApplicationStateMonitor, NSMutableDictionary, NSString;

@interface CSLSnapshotApplicationStateMonitor : NSObject <BSDescriptionProviding>
{
    struct _opaque_pthread_mutex_t _dictionaryLock;
    NSMutableDictionary *_stateByBundleID;
    BKSApplicationStateMonitor *_bksApplicationStateMonitor;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
- (id)_getSnapshotState:(id)arg1;
- (void)_withLock:(CDUnknownBlockType)arg1;
- (_Bool)isForeground:(id)arg1;
- (void)snapshotted:(id)arg1 primaryUI:(_Bool)arg2 movedToBackground:(_Bool)arg3;
- (void)cancelPriorityScheduling:(id)arg1;
- (id)returnToPrimaryUIDate:(id)arg1 returnInterval:(double)arg2;
- (void)didSendReturnToPrimaryUI:(id)arg1;
- (_Bool)needsReturnToPrimaryUI:(id)arg1;
- (_Bool)doPriorityScheduleNextSnaphot:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

