//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CUISAlertViewController.h"

#import "CSLShutdownContainerViewControllerDelegate.h"

@class CSLObliterationConfirmationViewController, CSLObliterationViewController, CSLShutdownSliderBasedAlertViewController;

@interface CSLShutdownContainerViewController : CUISAlertViewController <CSLShutdownContainerViewControllerDelegate>
{
    id <CSLShutdownAlertProviderDelegate> _alertProviderDelegate;
    CSLShutdownSliderBasedAlertViewController *_powerdownViewController;
    CSLObliterationViewController *_obliterationController;
    CSLObliterationConfirmationViewController *_obliterationConfirmationController;
}

- (void).cxx_destruct;
- (void)presentObliterationConfirmationController;
- (void)presentObliterationController;
- (void)endAppearanceAnimations;
- (void)viewDidLoad;
- (id)initWithPriority:(unsigned int)arg1 alertProviderDelegate:(id)arg2;

@end

