//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class NSDate, NSString;

@interface CSLSnapshotApplicationState : NSObject <BSDescriptionProviding>
{
    struct _opaque_pthread_mutex_t _stateLock;
    unsigned int _priorityState;
    unsigned int _uiState;
    unsigned int _lastBKSApplicationState;
    NSDate *_leftForegroundDate;
    NSString *_bundleID;
}

@property(readonly, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
- (void)priorityScheduleCancelled;
- (id)returnToPrimaryUIDate:(double)arg1;
- (void)didSendReturnToPrimaryUI;
- (_Bool)needsReturnToPrimaryUI;
- (_Bool)priorityScheduleNextSnaphot;
- (void)snapshotted:(_Bool)arg1 movedToBackground:(_Bool)arg2;
- (unsigned int)bksApplicationState;
- (void)applicationStateChanged:(unsigned int)arg1;
- (void)_withLock:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithBundleID:(id)arg1;

// Remaining properties
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

