//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol CSLScreenEdgePresenter <NSObject>
- (_Bool)isPresented;
- (void)dismissAnimated:(_Bool)arg1 completion:(void (^)(void))arg2;
- (void)dismissAnimated:(_Bool)arg1;
- (void)presentAnimated:(_Bool)arg1 completion:(void (^)(void))arg2;
- (void)presentAnimated:(_Bool)arg1;
@end

