//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class UIViewController<CSLPageViewController>;

@protocol CSLSwitcherViewControllerProtocol
@property(readonly, nonatomic) struct _NSRange visibleControllerRange;
- (void)removeObserver:(id <CSLSwitcherViewControllerObserver>)arg1;
- (void)addObserver:(id <CSLSwitcherViewControllerObserver>)arg1;
- (float)visiblePercentageForViewControllerAtIndex:(unsigned int)arg1;
- (UIViewController<CSLPageViewController> *)viewControllerAtIndex:(unsigned int)arg1;
- (UIViewController<CSLPageViewController> *)centeredViewController;
@end

