//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface CSLSQLiteDatabase : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    struct sqlite3 *_db;
    unsigned int _state;
    NSString *_path;
}

@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (_Bool)_createDatabaseWithSQL:(id)arg1 atPath:(id)arg2 withFilename:(id)arg3;
- (double)databaseValueForDate:(id)arg1;
- (_Bool)addColumnIfNecessaryWithName:(id)arg1 andType:(id)arg2 toTable:(id)arg3;
- (_Bool)prepareStatement:(struct sqlite3_stmt **)arg1 withSQL:(id)arg2;
- (_Bool)table:(id)arg1 containsColumn:(id)arg2;
- (void)performQuery:(CDUnknownBlockType)arg1;
- (void)upgradeDatabase;
- (void)finalizeStatements;
- (_Bool)prepareStatements;
- (void)dealloc;
- (id)initWithSQL:(id)arg1 atPath:(id)arg2 withFilename:(id)arg3;

@end

