//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLKComplicationObserver, CSLSnapshotActivityManager, CSLSnapshotComplicationPolicy, CSLSnapshotServiceEndpoint;

@interface CSLSnapshotServiceConfiguration : NSObject
{
    CSLSnapshotActivityManager *_activityManager;
    CSLSnapshotServiceEndpoint *_endpoint;
    CLKComplicationObserver *_complicationObserver;
    CSLSnapshotComplicationPolicy *_complicationPolicy;
}

+ (id)defaultActivityManagerConfiguration;
+ (id)defaultConfiguration;
@property(retain, nonatomic) CSLSnapshotComplicationPolicy *complicationPolicy; // @synthesize complicationPolicy=_complicationPolicy;
@property(retain, nonatomic) CLKComplicationObserver *complicationObserver; // @synthesize complicationObserver=_complicationObserver;
@property(retain, nonatomic) CSLSnapshotServiceEndpoint *endpoint; // @synthesize endpoint=_endpoint;
@property(retain, nonatomic) CSLSnapshotActivityManager *activityManager; // @synthesize activityManager=_activityManager;
- (void).cxx_destruct;

@end

