//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLSBacklightObserver.h"

@class BKSApplicationStateMonitor, NSString, NSTimer;

@interface CSLStandAloneDemoModeManager : NSObject <CSLSBacklightObserver>
{
    BKSApplicationStateMonitor *_appStateMonitor;
    unsigned int _previousAppState;
    _Bool _isStandaloneSecured;
    int _backLightStatus;
    _Bool _isObservingBacklight;
    NSTimer *_demoResetTimer;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)backlightDidChange:(id)arg1 from:(int)arg2 to:(int)arg3;
- (void)_cancelStandaloneSecuredResetTimer;
- (void)_demoResetTimerFired;
- (void)_startStandaloneSecuredResetTimer;
- (void)_updateIsStandaloneSecured;
- (void)navigateToDemoApplication;
- (void)cleanupNotificaitonCenter;
- (void)reloadData;
- (void)batteryStateChangedHandler:(_Bool)arg1;
- (void)batteryStateChanged:(id)arg1;
- (_Bool)isCharging;
- (void)startDemoMode;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

