//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScreenEdgePanGestureRecognizer.h"

@interface CSLScreenEdgePanGestureRecognizer : UIScreenEdgePanGestureRecognizer
{
    _Bool _shouldUseGrapeFlags;
}

@property(nonatomic) _Bool shouldUseGrapeFlags; // @synthesize shouldUseGrapeFlags=_shouldUseGrapeFlags;
- (_Bool)_shouldUseGrapeFlags;
- (int)_touchInterfaceOrientation;
- (struct CGPoint)_locationForTouch:(id)arg1;
- (void)_handleFailTimer:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2 type:(int)arg3;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;
- (void)csl_commonInitScreenEdgePanGestureRecognizer;

@end

