//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CSLUIApplicationIconDownloadProgressView, CUISActivateUIApplicationView, UIView<FBSceneHostView>;

@interface CSLSceneContainerView : UIView
{
    _Bool _displaysDebugFrames;
    UIView<FBSceneHostView> *_contextHostView;
    CUISActivateUIApplicationView *_activationView;
    CSLUIApplicationIconDownloadProgressView *_downloadProgressView;
    unsigned int _displayMode;
}

@property(nonatomic) _Bool displaysDebugFrames; // @synthesize displaysDebugFrames=_displaysDebugFrames;
@property(nonatomic) unsigned int displayMode; // @synthesize displayMode=_displayMode;
@property(retain, nonatomic) CSLUIApplicationIconDownloadProgressView *downloadProgressView; // @synthesize downloadProgressView=_downloadProgressView;
@property(retain, nonatomic) CUISActivateUIApplicationView *activationView; // @synthesize activationView=_activationView;
@property(retain, nonatomic) UIView<FBSceneHostView> *contextHostView; // @synthesize contextHostView=_contextHostView;
- (void).cxx_destruct;
- (id)debugColorForDisplayMode:(unsigned int)arg1;
- (void)updateDebugFramesWithDisplayMode:(unsigned int)arg1;
- (void)_updateContextHostVisibilityForDisplayMode:(unsigned int)arg1;
- (void)_updateDownloadProgressVisibilityForDisplayMode:(unsigned int)arg1;
- (void)_updateActivationVisibilityForDisplayMode:(unsigned int)arg1;
- (id)_fromViewForAnimationInDisplayMode:(unsigned int)arg1;
- (void)_updateViewVisibilityForDisplayMode:(unsigned int)arg1;
- (void)_crossDissolveTransitionToView:(id)arg1 duration:(double)arg2 oldDisplayMode:(unsigned int)arg3 newDisplayMode:(unsigned int)arg4 completion:(CDUnknownBlockType)arg5;
- (void)setDisplayMode:(unsigned int)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

