//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IOSSHLApplication, NSObject<OS_dispatch_queue>, NSString;

@interface CSLSetupAssistant : NSObject
{
    _Bool _initializedMode;
    _Bool _setupNeedsToRun;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (_Bool)isOrShouldBeRunning;
- (void)applicationDidFinishLaunching;
- (_Bool)_queue_isInSetup_uncached;
- (_Bool)isInSetup_uncached;
@property(readonly, nonatomic, getter=isInSetup) _Bool inSetup;
- (void)setupCompleted;
@property(readonly, nonatomic) NSString *bundleIdentifier;
@property(readonly, nonatomic) IOSSHLApplication *setupApplication;
- (id)init;

@end

