//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLSSuspendSystemGestureAssertionProvider.h"

@class CSLSuspendSystemGestureAssertionsXPCServer, FBSDisplay, NSMutableDictionary, NSMutableSet, NSString;

@interface CSLSystemGestureManager : NSObject <CSLSSuspendSystemGestureAssertionProvider>
{
    FBSDisplay *_display;
    NSMutableSet *_gestures;
    NSMutableSet *_enabledGestures;
    NSMutableSet *_recognizingGestures;
    CSLSuspendSystemGestureAssertionsXPCServer *_suspendAssertionsServer;
    NSMutableDictionary *_suspendAssertions;
    _Bool _isDisabled;
    _Bool _systemGesturesDisabledForAccessibility;
    _Bool _enabled;
}

+ (id)mainDisplayManager;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic, getter=areSystemGesturesDisabledForAccessibility) _Bool systemGesturesDisabledForAccessibility; // @synthesize systemGesturesDisabledForAccessibility=_systemGesturesDisabledForAccessibility;
- (void).cxx_destruct;
- (void)_systemGestureChanged:(id)arg1;
- (void)_disableSystemGesture:(id)arg1;
- (void)_enableSystemGesture:(id)arg1;
- (_Bool)_shouldEnableSystemGesture;
- (void)releaseSuspendSystemGestureAssertion:(id)arg1 pid:(int)arg2;
- (void)takeSuspendSystemGestureAssertion:(id)arg1 pid:(int)arg2;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (_Bool)areSystemGesturesDisabledForSuspendAssertions;
- (_Bool)isGestureAllowed;
@property(readonly, nonatomic, getter=isAnyGestureRunning) _Bool anyGestureRunning;
@property(readonly, nonatomic) FBSDisplay *display;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
- (void)updateUserPreferences;
- (void)removeGestureRecognizer:(id)arg1;
- (void)addGestureRecognizer:(id)arg1;
- (void)dealloc;
- (id)initWithDisplay:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

