//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLSSnapshotRequest, NSDate, NSDictionary, NSString;

@protocol CSLSnapshotServiceAppProtocol <NSObject>
- (void)invalidateSnapshotForBundleID:(NSString *)arg1;
- (void)scheduleAppSnapshot:(NSString *)arg1 date:(NSDate *)arg2 userInfo:(NSDictionary *)arg3;
- (void)processSnapshotRequest:(CSLSSnapshotRequest *)arg1 reason:(unsigned int)arg2 forBundleID:(NSString *)arg3;
@end

