//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class CSLSnapshotActivityControllerResumedState, CSLSnapshotActivityControllerSuspendedState, CSLSnapshotActivityManagerConfiguration, CSLSnapshotActivitySchedule, CSLSnapshotService, NSString, _DASActivity;

@interface CSLSnapshotActivityController : NSObject <BSDescriptionProviding>
{
    int _suspendCount;
    _Bool _hasSuspendedSnapshotRequest;
    id <CSLSnapshotActivityControllerDelegate> _delegate;
    NSString *_bundleID;
    CSLSnapshotActivitySchedule *_schedule;
    CSLSnapshotService *_snapshotService;
    _DASActivity *_pendingActivity;
    _DASActivity *_submittedActivity;
    CSLSnapshotActivityControllerResumedState *_resumedState;
    CSLSnapshotActivityControllerSuspendedState *_suspendedState;
    id <CSLSnapshotActivityControllerState> _currentState;
    CSLSnapshotActivityManagerConfiguration *_configuration;
}

@property(readonly) CSLSnapshotActivityManagerConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) id <CSLSnapshotActivityControllerState> currentState; // @synthesize currentState=_currentState;
@property(retain, nonatomic) CSLSnapshotActivityControllerSuspendedState *suspendedState; // @synthesize suspendedState=_suspendedState;
@property(retain, nonatomic) CSLSnapshotActivityControllerResumedState *resumedState; // @synthesize resumedState=_resumedState;
@property(nonatomic) _Bool hasSuspendedSnapshotRequest; // @synthesize hasSuspendedSnapshotRequest=_hasSuspendedSnapshotRequest;
@property(retain, nonatomic) _DASActivity *submittedActivity; // @synthesize submittedActivity=_submittedActivity;
@property(retain, nonatomic) _DASActivity *pendingActivity; // @synthesize pendingActivity=_pendingActivity;
@property(nonatomic) __weak CSLSnapshotService *snapshotService; // @synthesize snapshotService=_snapshotService;
@property(retain, nonatomic) CSLSnapshotActivitySchedule *schedule; // @synthesize schedule=_schedule;
@property(readonly, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(nonatomic) __weak id <CSLSnapshotActivityControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (void)_queue_informDelegateOfExhaustedSchedule;
- (void)_queue_didCompleteSnapshotForSchedule:(id)arg1;
- (void)_queue_beginActivity:(id)arg1;
- (void)_queue_activityStarted:(id)arg1;
- (id)snapshotActivityAfterDate:(id)arg1 startBeforeDate:(id)arg2 prioritize:(_Bool)arg3;
- (id)startBeforeDateForItem:(id)arg1 atIndex:(unsigned int)arg2 inSchedule:(id)arg3;
- (void)_queue_submitNextActivityForSchedule:(id)arg1;
- (void)addSnapshotScheduleItem:(id)arg1;
- (void)applySnapshotRequest:(id)arg1;
@property(readonly, getter=isSuspended) _Bool suspended;
- (void)cancel;
- (void)suspend;
- (void)resume;
- (id)budgetController;
- (id)scheduler;
- (id)queue;
- (id)initWithBundleID:(id)arg1 configuration:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

