//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLScreenEdgeCoordinatingDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class CSLScreenEdgePanGestureRecognizer, NSString;

@interface CSLScreenEdgeCoordinator : NSObject <UIGestureRecognizerDelegate, CSLScreenEdgeCoordinatingDelegate>
{
    id <CSLScreenEdgeCoordinating> _topCoordinatedController;
    id <CSLScreenEdgeCoordinating> _bottomCoordinatedController;
    id <CSLScreenEdgeCoordinating> _activeController;
    CSLScreenEdgePanGestureRecognizer *_topGestureRecognizer;
    CSLScreenEdgePanGestureRecognizer *_bottomGestureRecognizer;
}

+ (id)sharedCoordinator;
- (void).cxx_destruct;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)_createGestureRecognizersIfNecessary;
- (void)coordinatedControllerDidPresent:(id)arg1;
- (void)coordinatedControllerWillPresent:(id)arg1;
- (void)coordinatedControllerDidDismiss:(id)arg1;
- (void)coordinatedControllerWillDismiss:(id)arg1;
- (void)setBottomCoordinatedController:(id)arg1;
- (void)setTopCoordinatedController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

