//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CSLSnapshotContextManager : NSObject
{
    id <CSLSnapshotServiceAppProtocol> _snapshotService;
}

@property(nonatomic) __weak id <CSLSnapshotServiceAppProtocol> snapshotService; // @synthesize snapshotService=_snapshotService;
- (void).cxx_destruct;
- (void)removeSnapshotContextForBundleID:(id)arg1;
- (void)snapshotContextForBundleID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setSnapshotContext:(id)arg1 forBundleID:(id)arg2;
- (id)initWithSnapshotService:(id)arg1;
- (id)init;

@end

