//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLBackgroundUpdatePolicy, CSLDuetMeteringManager, CSLDuetSnapshotBudgetController, CSLPrelaunchManager, NSObject<OS_dispatch_queue>;

@interface CSLSnapshotActivityManagerConfiguration : NSObject
{
    id <_DASActivityScheduler> _scheduler;
    CSLDuetMeteringManager *_meteringManager;
    CSLDuetSnapshotBudgetController *_budgetController;
    CSLBackgroundUpdatePolicy *_backgroundUpdatePolicy;
    CSLPrelaunchManager *_prelaunchManager;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) CSLPrelaunchManager *prelaunchManager; // @synthesize prelaunchManager=_prelaunchManager;
@property(retain, nonatomic) CSLBackgroundUpdatePolicy *backgroundUpdatePolicy; // @synthesize backgroundUpdatePolicy=_backgroundUpdatePolicy;
@property(retain, nonatomic) CSLDuetSnapshotBudgetController *budgetController; // @synthesize budgetController=_budgetController;
@property(retain, nonatomic) CSLDuetMeteringManager *meteringManager; // @synthesize meteringManager=_meteringManager;
@property(retain, nonatomic) id <_DASActivityScheduler> scheduler; // @synthesize scheduler=_scheduler;
- (void).cxx_destruct;

@end

