//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BSEventQueueEvent.h"

@interface CSLTransactionQueueEvent : BSEventQueueEvent
{
    _Bool _cancelled;
}

+ (id)eventWithName:(id)arg1 handler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic, getter=isCancelled) _Bool cancelled; // @synthesize cancelled=_cancelled;
- (id)description;
- (void)cancel;

@end

