//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BSBaseXPCServer.h"

@interface CSLToolXPCServer : BSBaseXPCServer
{
}

- (void)_handle_setTimerWithDate:(id)arg1 useWallClockTime:(_Bool)arg2;
- (void)_handle_forceStuckTransactionShouldBluescreen:(_Bool)arg1 shouldStackshotTwice:(_Bool)arg2;
- (void)queue_handleMessage:(id)arg1 client:(id)arg2;
- (id)init;

@end

