//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBBundleInfo, UIImage;

@interface CSLUICarouselApplication : NSObject
{
    FBBundleInfo *_appInfo;
    UIImage *_icon;
}

@property(retain) UIImage *icon; // @synthesize icon=_icon;
@property(readonly) FBBundleInfo *appInfo; // @synthesize appInfo=_appInfo;
- (void).cxx_destruct;
- (id)description;
- (id)initWithPlatformApplication:(id)arg1 icon:(id)arg2;

@end

