//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "APSConnectionDelegate.h"
#import "CBCentralManagerDelegate.h"
#import "CBCentralManagerPrivateDelegate.h"
#import "CBPeripheralManagerDelegate.h"
#import "IDSServiceDelegate.h"

@class APSConnection, CBCentralManager, CBPairingAgent, CBPeripheralManager, IDSService, NSObject<OS_dispatch_queue>, NSString, UIView, UIWindow;

@interface CSLUICompanionLinkStatusViewController : NSObject <IDSServiceDelegate, CBCentralManagerDelegate, CBCentralManagerPrivateDelegate, CBPeripheralManagerDelegate, APSConnectionDelegate>
{
    _Bool _magnetConnected;
    _Bool _idsConnected;
    _Bool _apsConnected;
    UIWindow *_window;
    UIView *_statusIndicatorView;
    IDSService *_service;
    CBCentralManager *_cbCentralManager;
    CBPeripheralManager *_cbPeripheralManager;
    CBPairingAgent *_cbPairingAgent;
    APSConnection *_apsConnection;
    NSObject<OS_dispatch_queue> *_cbQueue;
}

+ (void)_loadPref;
+ (void)startMonitoring;
@property(nonatomic) _Bool apsConnected; // @synthesize apsConnected=_apsConnected;
@property(nonatomic) _Bool idsConnected; // @synthesize idsConnected=_idsConnected;
@property(nonatomic) _Bool magnetConnected; // @synthesize magnetConnected=_magnetConnected;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *cbQueue; // @synthesize cbQueue=_cbQueue;
@property(retain, nonatomic) APSConnection *apsConnection; // @synthesize apsConnection=_apsConnection;
@property(retain, nonatomic) CBPairingAgent *cbPairingAgent; // @synthesize cbPairingAgent=_cbPairingAgent;
@property(retain, nonatomic) CBPeripheralManager *cbPeripheralManager; // @synthesize cbPeripheralManager=_cbPeripheralManager;
@property(retain, nonatomic) CBCentralManager *cbCentralManager; // @synthesize cbCentralManager=_cbCentralManager;
@property(retain, nonatomic) IDSService *service; // @synthesize service=_service;
@property(retain, nonatomic) UIView *statusIndicatorView; // @synthesize statusIndicatorView=_statusIndicatorView;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)_updateMagnetStatus;
- (void)peripheralManagerDidUpdateState:(id)arg1;
- (void)centralManager:(id)arg1 didUpdatePeripheralConnectionState:(id)arg2;
- (void)centralManagerDidUpdateState:(id)arg1;
- (void)_updateForAccounts:(id)arg1 andDevices:(id)arg2;
- (void)service:(id)arg1 devicesChanged:(id)arg2;
- (void)service:(id)arg1 activeAccountsChanged:(id)arg2;
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;
- (void)connection:(id)arg1 didChangeConnectedStatus:(_Bool)arg2;
- (void)dealloc;
- (void)invalidate;
- (void)_updateIDSStatus;
- (void)_updateAPSStatus;
- (void)_updateIndicators;
- (void)_setIndicatorColor;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

