//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class CSLUIApplicationViewController, NSString;

@interface CSLUIApplicationViewControllerTransitionCoordinator : NSObject <BSDescriptionProviding>
{
    _Bool _interactive;
    _Bool _animated;
    _Bool _started;
    _Bool _finished;
    _Bool _transitionWasCancelled;
    CSLUIApplicationViewController *_viewController;
    unsigned int _sourceEnvironment;
    unsigned int _targetEnvironment;
    float _percentComplete;
}

@property(readonly, nonatomic) _Bool transitionWasCancelled; // @synthesize transitionWasCancelled=_transitionWasCancelled;
@property(readonly, nonatomic, getter=isFinished) _Bool finished; // @synthesize finished=_finished;
@property(readonly, nonatomic, getter=isStarted) _Bool started; // @synthesize started=_started;
@property(readonly, nonatomic) float percentComplete; // @synthesize percentComplete=_percentComplete;
@property(readonly, nonatomic, getter=isAnimated) _Bool animated; // @synthesize animated=_animated;
@property(readonly, nonatomic, getter=isInteractive) _Bool interactive; // @synthesize interactive=_interactive;
@property(readonly, nonatomic) unsigned int targetEnvironment; // @synthesize targetEnvironment=_targetEnvironment;
@property(readonly, nonatomic) unsigned int sourceEnvironment; // @synthesize sourceEnvironment=_sourceEnvironment;
@property(readonly, nonatomic) CSLUIApplicationViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
- (void)updateInteractiveTransition:(float)arg1;
- (void)completeTransition:(_Bool)arg1;
- (void)beginTransition:(_Bool)arg1 interactive:(_Bool)arg2;
- (id)initWithViewController:(id)arg1 sourceEnvironment:(unsigned int)arg2 targetEnvironment:(unsigned int)arg3;

// Remaining properties
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

