//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IOSSHLTransaction.h"

#import "CSLAnimatedTransitioningTransactionObserver.h"
#import "CSLNavigationStackControllerAnimationProvider.h"

@class CSLAnimatedTransitioningTransaction, CSLNavigationStackController, CSLNavigationStackRequest, NSString;

@interface CSLUpdateNavigationStackTransaction : IOSSHLTransaction <CSLNavigationStackControllerAnimationProvider, CSLAnimatedTransitioningTransactionObserver>
{
    CSLNavigationStackController *_navigationController;
    CSLNavigationStackRequest *_request;
    IOSSHLTransaction *_animationParentTransaction;
    CSLNavigationStackRequest *_originalRequest;
    CSLAnimatedTransitioningTransaction *_animationTransaction;
}

@property(retain, nonatomic) CSLAnimatedTransitioningTransaction *animationTransaction; // @synthesize animationTransaction=_animationTransaction;
@property(retain, nonatomic) CSLNavigationStackRequest *originalRequest; // @synthesize originalRequest=_originalRequest;
@property(readonly, nonatomic) IOSSHLTransaction *animationParentTransaction; // @synthesize animationParentTransaction=_animationParentTransaction;
@property(readonly, nonatomic) CSLNavigationStackRequest *request; // @synthesize request=_request;
@property(readonly, nonatomic) CSLNavigationStackController *navigationController; // @synthesize navigationController=_navigationController;
- (void).cxx_destruct;
- (void)animatorDidReceiveBeginAnimation:(id)arg1;
- (id)navigationController:(id)arg1 animationControllerForNonAnimatedOperation:(int)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)navigationController:(id)arg1 animationControllerForOperation:(int)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)navigationController:(id)arg1 animationControllerForOperation:(int)arg2 animated:(_Bool)arg3 fromViewController:(id)arg4 toViewController:(id)arg5;
- (void)animationDependenciesCompleted;
- (void)_didSatisfyMilestone:(id)arg1;
- (void)handleNavigationResponse:(id)arg1;
- (id)proxyRequestForRequest:(id)arg1;
- (void)_didComplete;
- (void)_begin;
- (id)initWithNavigationController:(id)arg1 request:(id)arg2 animationParentTransaction:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

