//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CSLUIUsageMeteringLocation : NSObject
{
    unsigned int _state;
    NSString *_bundleID;
    NSString *_sectionID;
    unsigned int _transitionReason;
}

@property(nonatomic) unsigned int transitionReason; // @synthesize transitionReason=_transitionReason;
@property(retain, nonatomic) NSString *sectionID; // @synthesize sectionID=_sectionID;
@property(retain, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(nonatomic) unsigned int state; // @synthesize state=_state;
- (void).cxx_destruct;
- (id)description;
- (id)transitionReasonString;
- (id)stateString;
- (id)initWithState:(unsigned int)arg1 andTransitionReason:(unsigned int)arg2;

@end

