//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLPILogoHandleVendor.h"
#import "CSLUILogoHandlerDelegate.h"

@class NSString, PUIProgressWindow;

@interface CSLUILogoManager : NSObject <CSLUILogoHandlerDelegate, CSLPILogoHandleVendor>
{
    int _logoHandlerCount;
    unsigned int _level;
    PUIProgressWindow *_logo;
    id <CSLUILogoManagerDelegate> _delegate;
}

+ (id)sharedInstance;
@property(nonatomic) __weak id <CSLUILogoManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showLogo;
- (void)setLevel:(unsigned int)arg1;
- (void)hideLogo;
- (id)newLogoHandle:(id)arg1;
- (void)logoHandleDidDecrementRefCount:(id)arg1;
- (void)logoHandleDidIncrementRefCount:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

