//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLFirstResponderEnabledViewController.h"

#import "BSDescriptionProviding.h"
#import "CSLButtonTapAssertionHandler.h"
#import "CSLPIButtonHandlerProtocol.h"
#import "CSLSceneMonitorDelegate.h"
#import "CSLUIActivatingUIAssertionObserver.h"
#import "CSLUICarouselApplicationStoreListener.h"

@class CSLCarouselEventFocusManagerAssertion, CSLSceneMonitor, CSLUIActivateApplicationViewManager, CSLUIApplicationViewControllerTransitionCoordinator, FBScene, FBSceneHostManager, NSString;

@interface CSLUIApplicationViewController : CSLFirstResponderEnabledViewController <CSLUIActivatingUIAssertionObserver, CSLPIButtonHandlerProtocol, CSLButtonTapAssertionHandler, CSLSceneMonitorDelegate, CSLUICarouselApplicationStoreListener, BSDescriptionProviding>
{
    CSLSceneMonitor *_sceneMonitor;
    _Bool _buttonTapAssertionActive;
    unsigned int _buttonTapAssertionButtons;
    FBScene *_scene;
    FBSceneHostManager *_contextHostManager;
    CSLCarouselEventFocusManagerAssertion *_eventFocusAssertion;
    CSLUIActivateApplicationViewManager *_activeApplicationViewManager;
    unsigned int _currentDisplayMode;
    _Bool _isInApplicationSwitcherMode;
    CSLUIApplicationViewControllerTransitionCoordinator *_displayEnvironmentTransitionCoordinator;
    unsigned int _displayEnvironment;
    _Bool _activationViewIsDirty;
    _Bool _isCalendar;
    NSString *_bundleIdentifier;
}

+ (id)_applicationButtonHandler;
+ (void)initializeButtonHandler;
+ (void)initialize;
@property(readonly, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
- (void)scrollViewLayoutPercentageChanged:(float)arg1;
- (void)_activationViewInvalidated:(id)arg1;
- (void)_snapshotChanged:(id)arg1;
- (_Bool)_isAppInstalling;
- (_Bool)_hasAssertionForActivateUI;
- (_Bool)_appHasActivated;
- (id)application;
- (unsigned int)_activeViewDisplayMode;
- (id)view;
- (void)_snapshotHostedView;
- (void)_setupActivationViewIfNeeded;
- (void)_setupInstallingViewIfNeeded;
- (void)_updateViewVisibility:(int)arg1;
- (id)stringForViewControllerEvent:(int)arg1;
- (id)stringForViewControllerMode:(_Bool)arg1;
- (id)stringForSceneDisplayMode:(unsigned int)arg1;
- (id)stringForViewControllerAppearState:(int)arg1;
- (void)_updateLayerHosting;
- (void)_configureWithScene:(id)arg1;
- (void)applicationStore:(id)arg1 addedBundleIDs:(id)arg2 removedBundleIDs:(id)arg3 modifiedBundleIDs:(id)arg4;
- (void)applicationStore:(id)arg1 applicationPlaceholderInstalled:(id)arg2;
- (void)applicationStore:(id)arg1 progressChangedForBundleID:(id)arg2 progress:(double)arg3;
- (void)sceneMonitor:(id)arg1 sceneWasDestroyed:(id)arg2;
- (void)sceneMonitor:(id)arg1 sceneWillEnterBackground:(id)arg2;
- (void)sceneMonitor:(id)arg1 sceneWasCreated:(id)arg2;
- (void)allActivateUIAssertonsAssertionsReleasedForBundleID:(id)arg1;
- (void)activateUIAssertionTakenForBundleID:(id)arg1;
- (void)_applicationStateDidChange:(id)arg1;
- (void)_activationStateDidChange:(id)arg1;
- (void)takeCrownFocusAssertion;
- (void)releaseCrownFocusAssertion;
- (void)_updateDownloadProgress:(double)arg1;
- (void)updateContainerMode:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)applicationViewControllerFinishedAnimatingIn;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)deactivateButtonTapAssertion;
- (void)activateButtonTapAssertionWithButtons:(unsigned int)arg1;
- (_Bool)handleButton:(unsigned int)arg1 eventType:(unsigned int)arg2 firstDownTime:(unsigned long long)arg3 lastUpTime:(unsigned long long)arg4;
- (void)dealloc;
- (id)initWithBundleIdentifier:(id)arg1;
- (void)transitionCoordinatorDidCompleteTransition:(id)arg1;
- (void)transitionCoordinatorDidUpdateTransitionPercentage:(id)arg1;
- (void)transitionCoordinatorDidBeginTransition:(id)arg1;
- (id)transitionCoordinatorToTargetEnvironment:(unsigned int)arg1;

// Remaining properties
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

