//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSLSwitcherViewControllerObserver.h"

@class CSLUIUsageMeteringLocation, NSObject<OS_dispatch_queue>;

@interface CSLUIUsageMeteringManager : NSObject <CSLSwitcherViewControllerObserver>
{
    _Bool _screenOn;
    CSLUIUsageMeteringLocation *_currentBaseLocation;
    CSLUIUsageMeteringLocation *_currentAlertLocation;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    double _lastUIChangeTime;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
@property(nonatomic) double lastUIChangeTime; // @synthesize lastUIChangeTime=_lastUIChangeTime;
@property(nonatomic) _Bool screenOn; // @synthesize screenOn=_screenOn;
@property(retain, nonatomic) CSLUIUsageMeteringLocation *currentAlertLocation; // @synthesize currentAlertLocation=_currentAlertLocation;
@property(retain, nonatomic) CSLUIUsageMeteringLocation *currentBaseLocation; // @synthesize currentBaseLocation=_currentBaseLocation;
- (void).cxx_destruct;
- (void)switcherViewControllerDidUpdate:(id)arg1;
- (void)switcherViewControllerDidDismiss:(id)arg1;
- (void)switcherViewControllerWillEndFastSwitching:(id)arg1;
- (void)switcherViewControllerWillBeginFastSwitching:(id)arg1;
- (void)switcherViewController:(id)arg1 viewController:(id)arg2 atIndex:(unsigned int)arg3 didDisappear:(_Bool)arg4;
- (void)switcherViewController:(id)arg1 viewController:(id)arg2 atIndex:(unsigned int)arg3 willDisappear:(_Bool)arg4;
- (void)switcherViewController:(id)arg1 viewController:(id)arg2 atIndex:(unsigned int)arg3 didAppear:(_Bool)arg4;
- (void)switcherViewController:(id)arg1 viewController:(id)arg2 atIndex:(unsigned int)arg3 willAppear:(_Bool)arg4;
- (void)_logCurrentLocationWithLeaveTime:(double)arg1;
- (id)_getCurrentLocationTransitionReason;
- (id)_getCurrentLocationDescription;
- (id)_currentLocation;
- (void)logSwitcherViewController:(id)arg1;
- (void)switcherViewControllerDidSettle:(id)arg1;
- (void)switcherViewControllerDidAppear:(id)arg1;
- (void)_backlightDidTurnOff:(id)arg1;
- (void)_backlightDidTurnOn:(id)arg1;
- (void)didMoveToLocation:(id)arg1;
- (id)init;

@end

