//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSLNavigableViewController.h"

#import "CSLIconZoomCoordinatorProvider.h"
#import "CSLNotificationCenterViewControllerDelegate.h"
#import "CSLPIButtonHandlerProtocol.h"
#import "CSLSTileNavigationServiceServerExportedInterface.h"
#import "CSLWorkspaceRequestHandling.h"
#import "NCClockContainerViewController.h"
#import "NSXPCListenerDelegate.h"
#import "UIScrollViewDelegate.h"

@class CADisplayLink, CSLClockAssertion, CSLClockSlowModeAssertion, CSLControlCenterViewController, CSLNotificationCenterViewController, CSLVerticalScrollView, CUISAlertBackground, CUISAlertBackgroundView, NCClockViewController, NSMutableArray, NSString, NSXPCListener, UIViewController;

@interface CSLUITileNavigationController : CSLNavigableViewController <UIScrollViewDelegate, NSXPCListenerDelegate, CSLSTileNavigationServiceServerExportedInterface, CSLPIButtonHandlerProtocol, CSLNotificationCenterViewControllerDelegate, NCClockContainerViewController, CSLIconZoomCoordinatorProvider, CSLWorkspaceRequestHandling>
{
    NCClockViewController *_clockViewController;
    CSLControlCenterViewController *_controlCenterViewController;
    CSLVerticalScrollView *_verticalScrollView;
    struct CGPoint _verticalScrollViewContentOffset;
    NSXPCListener *_listener;
    NSMutableArray *_clientConnections;
    CUISAlertBackgroundView *_blurredBackgroundView;
    CUISAlertBackground *_blurredBackground;
    UIViewController *_currentViewController;
    _Bool _isMonitoringAlertPresentations;
    _Bool _clockIsEditing;
    NSString *_clockFaceName;
    id <CSLUITileNavigationControllerPPTDelegate> _PPTDelegate;
    CSLClockAssertion *_appearanceStateAssertion;
    CSLClockAssertion *_scrollPreventResumeAssertion;
    CSLClockAssertion *_clockParentAssertion;
    CSLClockAssertion *_clockVisibilityAssertion;
    CSLClockAssertion *_notAnimatingScrollViewAssertion;
    CSLClockSlowModeAssertion *_slowModeAssertion;
    CADisplayLink *_pptScrollDisplayLink;
    double _pptStartTime;
    double _pptAnimationDuration;
    struct CGPoint _pptStartContentOffset;
    struct CGPoint _pptEndContentOffset;
    CDUnknownBlockType _pptCompletion;
    CSLNotificationCenterViewController *_notificationCenterViewController;
}

@property(retain, nonatomic) CSLNotificationCenterViewController *notificationCenterViewController; // @synthesize notificationCenterViewController=_notificationCenterViewController;
- (void).cxx_destruct;
- (void)navigateToClockAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)handleWorkspaceRequest:(id)arg1 withTransitionCoordinator:(id)arg2;
- (void)_removeClientConnection:(id)arg1;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)zoomCoordinatorForZooming:(_Bool)arg1;
- (void)notificationCenterWasCleared:(id)arg1;
- (void)_wheelChangedWithEvent:(id)arg1;
- (void)restoreClock:(id)arg1;
- (id)detachClock;
- (id)PPTDelegate;
- (void)setPPTDelegate:(id)arg1;
- (void)_pptTellDelegateDidScrollToClock;
- (void)_pptSwipeToControlCenterWithCompletion:(CDUnknownBlockType)arg1;
- (void)_pptSwipeToClockWithCompletion:(CDUnknownBlockType)arg1;
- (void)_pptSwipeToNotificationCenterWithCompletion:(CDUnknownBlockType)arg1;
- (void)_pptScrollTestWithCompletion:(CDUnknownBlockType)arg1;
- (void)updatePPT:(id)arg1;
- (_Bool)handleButton:(unsigned int)arg1 eventType:(unsigned int)arg2 firstDownTime:(unsigned long long)arg3 lastUpTime:(unsigned long long)arg4;
- (id)getClockFaceName;
- (void)_handleClockEndEditing;
- (void)_handleClockBeginEditing;
- (void)_updateNotificationCenterVisibilityIfNeeded;
- (void)_updateClockVisibilityIfNeeded;
- (void)_updateControlCenterVisibilityIfNeeded;
- (void)_updateBlurVisibility;
- (void)_updateStoreDemoState;
- (void)_usageMetering;
- (void)_scrollViewDidStop;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_notifyChildrenOfScroll;
- (void)_refreshBlur;
- (void)_ensureClockStateAfterUnborrowing;
- (void)_disableSlowClock;
- (void)_enableSlowClock;
- (_Bool)_canChangeClockState;
- (void)_handleBacklightStateDidChange;
- (void)_handleBacklightDidTurnOff:(id)arg1;
- (void)_handleBacklightDidTurnOn:(id)arg1;
- (void)setVisibleViewController:(id)arg1;
- (id)visibleViewController;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)scrollToContentOffset:(struct CGPoint)arg1 animated:(_Bool)arg2;
- (void)scrollToControlCenterAnimated:(_Bool)arg1;
- (void)scrollToNotificationCenterAnimated:(_Bool)arg1;
- (void)scrollToClockAnimated:(_Bool)arg1;
- (_Bool)_isClockPartiallyVisible;
- (_Bool)isNotificationCenterVisible;
- (_Bool)isClockVisible;
- (_Bool)isControlCenterVisible;
- (void)viewDidLoad;
- (struct CGPoint)_centerForPageAtIndex:(unsigned int)arg1;
- (struct CGSize)_scrollViewPageSize;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

