//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IDSService, NPSDomainAccessor;

@interface CSLUIScreenShotter : NSObject
{
    IDSService *_idsService;
    NPSDomainAccessor *_domainAccessor;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (_Bool)screenShotEnabledPreference;
- (void)saveWatchFaceSnapshot;
- (void)saveScreenshot:(_Bool)arg1;
- (void)_sendImage:(id)arg1 forType:(unsigned int)arg2;
- (id)init;

@end

