//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IOSSHLTransaction.h"

#import "CSLNavigationTransactionAnimator.h"

@class CSLNavigationTransactionAnimatorHelper, NSString;

@interface CSLUIViewAnimationTransitionTransaction : IOSSHLTransaction <CSLNavigationTransactionAnimator>
{
    unsigned int _options;
    double _duration;
    _Bool _isAnimating;
    CDUnknownBlockType _beginAppearanceTransitionBlock;
    CSLNavigationTransactionAnimatorHelper *_helper;
    id <CSLNavigationTransactionAnimatorDelegate> _navigationTransactionAnimatorDelegate;
}

@property(nonatomic) __weak id <CSLNavigationTransactionAnimatorDelegate> navigationTransactionAnimatorDelegate; // @synthesize navigationTransactionAnimatorDelegate=_navigationTransactionAnimatorDelegate;
@property(readonly, nonatomic) CSLNavigationTransactionAnimatorHelper *helper; // @synthesize helper=_helper;
@property(copy, nonatomic) CDUnknownBlockType beginAppearanceTransitionBlock; // @synthesize beginAppearanceTransitionBlock=_beginAppearanceTransitionBlock;
- (void).cxx_destruct;
- (id)_customizedDescriptionProperties;
- (_Bool)_shouldComplete;
- (void)_begin;
- (id)initWithAnimationOptions:(unsigned int)arg1 duration:(double)arg2 helper:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

