//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CSLNavigationStackControllerDelegate.h"
#import "CSLPIButtonHandlerProtocol.h"
#import "CSLSUIProvider.h"
#import "CSLUIStateProviding.h"
#import "CSLUITileNavigationControllerPPTDelegate.h"
#import "CSLViewOnWakeListener.h"
#import "CSLWakeGestureObserver.h"
#import "CSLWorkspaceRequestHandling.h"
#import "IOSSHLBacklightObserver.h"

@class CSLAppSwitcherViewController, CSLClockAssertion, CSLLauncherViewController, CSLNavigableContainerViewController, CSLNavigationStackController, CSLPITimer, CSLUILogoHandle, CSLUITileNavigationController, CSLUIWorkspaceHelper, NSString;

@interface CSLUIMainViewController : UIViewController <CSLUITileNavigationControllerPPTDelegate, CSLNavigationStackControllerDelegate, CSLSUIProvider, CSLPIButtonHandlerProtocol, CSLViewOnWakeListener, IOSSHLBacklightObserver, CSLWakeGestureObserver, CSLUIStateProviding, CSLWorkspaceRequestHandling>
{
    CSLNavigationStackController *_navController;
    CSLLauncherViewController *_launcherController;
    CSLNavigableContainerViewController *_launcherContainer;
    CSLUITileNavigationController *_tileNavigationController;
    CSLAppSwitcherViewController *_appSwitcherController;
    CSLUIWorkspaceHelper *_workspaceHelper;
    CSLPITimer *_onWakeTimer;
    int _navigationStackUpdateCount;
    CSLUILogoHandle *_logo;
    CSLClockAssertion *_backlightClockAssertion;
}

@property(readonly, nonatomic) CSLAppSwitcherViewController *appSwitcherController; // @synthesize appSwitcherController=_appSwitcherController;
@property(readonly, nonatomic) CSLUITileNavigationController *tileNavigationController; // @synthesize tileNavigationController=_tileNavigationController;
- (void).cxx_destruct;
- (_Bool)isApplicationController:(id)arg1;
- (id)targetViewControllersForUpdateAction:(id)arg1;
- (void)_HACK_temporaryPerformWorkspaceActionsIfNeededForTransitionRequest:(id)arg1 transaction:(id)arg2 navigationStackResponse:(id)arg3 action:(id)arg4;
- (void)handleWorkspaceRequest:(id)arg1 withTransitionCoordinator:(id)arg2 forStackUpdateAction:(id)arg3;
- (void)handleWorkspaceRequest:(id)arg1 withTransitionCoordinator:(id)arg2 forMainUIUpdateAction:(id)arg3;
- (void)handleWorkspaceRequest:(id)arg1 withTransitionCoordinator:(id)arg2;
- (id)entitiesForViewControllers:(id)arg1;
- (void)populateUIState:(id)arg1;
@property(readonly, nonatomic) CSLLauncherViewController *launcherViewController;
- (void)PPTZoomToLauncher;
- (void)tileNavigationControllerPPTDidScrollToClock:(id)arg1;
- (void)pptDidCompletePPTZoom;
- (void)_pptDoNotificationCenterScrollTestName:(id)arg1 withApplication:(id)arg2;
- (void)_pptLaunchAppSwitcherWithCompletion:(CDUnknownBlockType)arg1;
- (void)_pptLaunchClockWithCompletion:(CDUnknownBlockType)arg1;
- (void)_pptZoomOutWithCompletion:(CDUnknownBlockType)arg1;
- (id)PPTAppSwitcherViewController;
- (id)PPTAppLauncherViewController;
- (void)PPTOffsetClock;
- (id)topmostCarouselViewControllerInNavigationStack;
- (void)_didCompleteNavigationRequestWithResponse:(id)arg1;
- (void)backlight:(id)arg1 didTurnOn:(_Bool)arg2 forReason:(unsigned int)arg3;
- (_Bool)_isClockActiveInCarousel;
- (void)backlight:(id)arg1 willBeOn:(_Bool)arg2 forReason:(unsigned int)arg3;
- (void)_handleAlertWillShow:(id)arg1;
- (void)handleLockStateDidChangeNotification:(id)arg1;
- (void)handleSleepGesture;
- (void)handleWakeGesture;
- (void)handleApplicationLaunchSuppressionReleasedNotification:(id)arg1;
- (void)stickyViewsChanged;
- (void)_updateOnWakeTimer;
- (void)_navigateToClockWithoutResume;
- (id)_stickiestAppBundleIdentifier;
- (void)navigateToStickyAppOrClock;
- (void)_navigateToStickyAppOrClockAfterTimeout:(double)arg1;
- (void)_navigateToStickyAppWithBundleIdentifier:(id)arg1;
- (void)_onWakeTimerFiredAfterTimeout:(double)arg1;
- (void)_stopOnWakeTimer;
- (void)_startOnWakeTimer;
- (_Bool)isTopAppSticky;
- (_Bool)isAppShowing;
@property(readonly, nonatomic) NSString *fullscreenAppBundleID;
- (id)_createTimerWithInterval:(double)arg1 extendedFromTimeout:(double)arg2;
- (id)_createDefaultOnWakeTimer;
- (void)handleNotificationButtonNotification:(id)arg1;
- (id)topApplicationViewControllerIfExists;
- (void)_updateDemoStoreStateWhenReturningToLocation:(id)arg1;
- (void)returnToApplication;
- (_Bool)handleButton:(unsigned int)arg1 eventType:(unsigned int)arg2;
- (id)navigationController:(id)arg1 animationControllerForOperation:(int)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (_Bool)resignFirstResponder;
- (_Bool)becomeFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)requestUITriggerWithRegistration:(id)arg1 UITriggerName:(id)arg2 withDictionary:(id)arg3 withReason:(int)arg4 withCompletion:(CDUnknownBlockType)arg5;
- (void)addChildCarouselController:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

