//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSLViewOnWakeManagerServer;

@interface CSLViewOnWakeManager : NSObject
{
    CSLViewOnWakeManagerServer *_server;
    _Bool _disableOnWakePreference;
    int _onWakeTimeoutSeconds;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreateIfNecessary:(_Bool)arg1;
- (void).cxx_destruct;
- (void)_updateOnWakeTimeoutPreference;
- (void)_updateDisableOnWakePreference;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (void)removeActiveOnlyStickyViews;
- (int)onWakeTimeoutSecondsPreference;
- (_Bool)allAppsStickyPreference;
- (id)highestPriorityStickyBundleIdentifierWithBiasedBundleIdentifier:(id)arg1;
- (_Bool)isViewSticky:(id)arg1;
- (void)dealloc;
- (id)init;

@end

