//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CSLWorkspaceActionPolicy : NSObject
{
}

- (id)badSignatureActionGroupForMainUpdateAction:(id)arg1;
- (id)_actionGroupsForDismissingOverlaysForRequest:(id)arg1 mainUIUpdateAction:(id)arg2;
- (_Bool)shouldDismissOverlaysForUpdateAction:(id)arg1;
- (id)actionsForTransitionRequest:(id)arg1;

@end

