//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HKHealthStore, NPSDomainAccessor, NSObject<OS_dispatch_queue>, NSString;

@interface CSLWorkoutActiveManager : NSObject
{
    int _workoutNotifyToken;
    NSObject<OS_dispatch_queue> *_queue;
    HKHealthStore *_healthStore;
    NPSDomainAccessor *_domainAccessor;
    _Bool _workoutActive;
    NSString *_activeWorkoutApplicationIdentifier;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) NSString *activeWorkoutApplicationIdentifier; // @synthesize activeWorkoutApplicationIdentifier=_activeWorkoutApplicationIdentifier;
@property(readonly, nonatomic) _Bool workoutActive; // @synthesize workoutActive=_workoutActive;
- (void).cxx_destruct;
- (void)_updateWorkoutActive;
- (_Bool)medicalIDEnabledPreference;
- (id)init;

@end

