//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSError, NSHashTable, NSObject<OS_dispatch_queue>;

@interface CSLWatchKitProcessMonitor : NSObject
{
    NSHashTable *_observers;
    NSObject<OS_dispatch_queue> *_queue;
    NSDictionary *_wkAppInfos;
    NSError *_error;
}

+ (id)sharedWatchKitProcessMonitor;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSDictionary *wkAppInfos; // @synthesize wkAppInfos=_wkAppInfos;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
- (void).cxx_destruct;
- (void)_queue_notifyObserversOfApplicationStateInfo:(id)arg1 error:(id)arg2;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)init;

@end

