//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IOSSHLTransaction.h"

@class CSLClockAssertion, CSLWorkspaceTransitionRequest;

@interface CSLWorkspaceTransitionTransaction : IOSSHLTransaction
{
    CSLClockAssertion *_appActivationAssertion;
    CSLWorkspaceTransitionRequest *_request;
}

@property(readonly, nonatomic) CSLWorkspaceTransitionRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (id)_customizedDescriptionProperties;
- (_Bool)needsClockPauseAssertion;
- (_Bool)isChangingTopmostApplication;
- (void)_prepareStoreDemoForTransactionBegin;
- (void)_didComplete;
- (void)_willBegin;
- (void)_didInterruptWithReason:(id)arg1;
- (id)initWithTransitionRequest:(id)arg1;

@end

