//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CUISActivateUIApplicationView, CUISLaunchApplicationContextData, NSString, NSURL, PUICApplicationStatusBarItem, PUICStatusBarGlobalContextProperties, PUICStatusImageView, UIImage, UIView, UIView<CUISActivateUIApplicationViewAnimatingDelegate>;

@protocol CUISActivateUIApplicationViewProviderDelegate <NSObject>
- (UIImage *)activateUIApplicationViewProvider:(id <CUISActivateUIApplicationViewProvider>)arg1 imageForBundleID:(NSString *)arg2 withName:(NSString *)arg3;
- (UIImage *)activateUIApplicationViewProvider:(id <CUISActivateUIApplicationViewProvider>)arg1 imageForBundleID:(NSString *)arg2 withName:(NSString *)arg3 withURL:(NSURL *)arg4 forOrientation:(int)arg5;
- (UIView *)activateUIApplicationViewProvider:(id <CUISActivateUIApplicationViewProvider>)arg1 activateImageForContextData:(CUISLaunchApplicationContextData *)arg2;
- (NSURL *)activateUIApplicationViewProvider:(id <CUISActivateUIApplicationViewProvider>)arg1 activatingURLForBundle:(NSString *)arg2;
- (NSString *)activateUIApplicationViewProvider:(id <CUISActivateUIApplicationViewProvider>)arg1 displayNameForBundle:(NSString *)arg2;
- (PUICStatusBarGlobalContextProperties *)activateUIApplicationViewProvider:(id <CUISActivateUIApplicationViewProvider>)arg1 statusBarGlobalContextPropertiesForAppContextData:(CUISLaunchApplicationContextData *)arg2;
- (PUICApplicationStatusBarItem *)activateUIApplicationViewProvider:(id <CUISActivateUIApplicationViewProvider>)arg1 statusBarItemForAppContextData:(CUISLaunchApplicationContextData *)arg2;

@optional
- (void)activateUIApplicationViewProvider:(id <CUISActivateUIApplicationViewProvider>)arg1 didCompleteUpdatesForAppContextData:(CUISLaunchApplicationContextData *)arg2 view:(CUISActivateUIApplicationView *)arg3;
- (void)activateUIApplicationViewProvider:(id <CUISActivateUIApplicationViewProvider>)arg1 willBeginUpdatesForAppContextData:(CUISLaunchApplicationContextData *)arg2 view:(CUISActivateUIApplicationView *)arg3;
- (_Bool)activateUIApplicationViewProvider:(id <CUISActivateUIApplicationViewProvider>)arg1 shouldDisplayStatusBarForContextData:(CUISLaunchApplicationContextData *)arg2;
- (UIView<CUISActivateUIApplicationViewAnimatingDelegate> *)applicationSwitcherSpinnerViewForContextData:(CUISLaunchApplicationContextData *)arg1;
- (PUICStatusImageView *)activateUIApplicationViewProvider:(id <CUISActivateUIApplicationViewProvider>)arg1 statusImageViewForBundleID:(NSString *)arg2;
@end

