//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol CUISActivateUIApplicationViewAnimatingDelegate <NSObject>
- (void)resetView;
- (void)pauseAnimations;
- (void)showDimmer;
- (void)animateSpinnerIn;
- (void)animationPercentageChanged:(float)arg1 isIcon:(_Bool)arg2;
@end

