//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BBBulletin, NSArray;

@protocol CUISNotificationCenterCellFactoryDelegate <NSObject>
- (void)cellFactory:(id <CUISNotificationCenterCellFactory>)arg1 requestReloadCellsForBulletins:(NSSet * (^)(NSSet *))arg2;
- (void)cellFactory:(id <CUISNotificationCenterCellFactory>)arg1 requestDismissBulletin:(BBBulletin *)arg2;
- (void)cellFactory:(id <CUISNotificationCenterCellFactory>)arg1 didUpdateSupportedSectionIDs:(NSArray *)arg2;
@end

