//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BKSProcessAssertion, NSString;

@interface IOSSHLBackgroundFetchTask : NSObject
{
    _Bool _finished;
    BKSProcessAssertion *_assertion;
    CDUnknownBlockType _completionHandler;
    NSString *_bundleID;
    int _sequenceNumber;
}

@property(readonly) _Bool finished; // @synthesize finished=_finished;
@property(readonly) int sequenceNumber; // @synthesize sequenceNumber=_sequenceNumber;
@property(readonly, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(retain, nonatomic) BKSProcessAssertion *assertion; // @synthesize assertion=_assertion;
- (void).cxx_destruct;
- (id)description;
- (void)dealloc;
- (void)_fireCompletionHandlerWithResult:(unsigned int)arg1;
- (void)finishWithResult:(unsigned int)arg1;
- (id)initForApplication:(id)arg1 sequenceNumber:(int)arg2 withCompletion:(CDUnknownBlockType)arg3;

@end

