//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IOSSHLActivationSettings.h"
#import "IOSSHLStateSettings.h"
#import "NSObject.h"

@class IOSSHLActivationSettings, IOSSHLStateSettings, NSString;

@protocol IOSSHLPresentationContext <NSObject, IOSSHLActivationSettings, IOSSHLStateSettings>
@property(copy, nonatomic) IOSSHLStateSettings *stateSettings;
@property(copy, nonatomic) IOSSHLActivationSettings *activationSettings;
@property(readonly, nonatomic) NSString *presentationName;
@property(readonly, nonatomic) NSString *presentationIdentifier;
- (void)clearActivationSettings;
- (void)clearStateSettings;
@end

