//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AWDServerConnection, NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface IOSSHLWirelessDiagnosticLog : NSObject
{
    _Bool _isDevelopmentDevice;
    NSObject<OS_dispatch_queue> *_queue;
    AWDServerConnection *_connection;
    NSMutableDictionary *_appEventData;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)_eventDataForApp:(id)arg1;
- (id)_dumpPreviousExitFromData:(id)arg1 atCurrentTime:(unsigned long long)arg2;
- (id)_dumpPreviousForegroundFromData:(id)arg1 atCurrentTime:(unsigned long long)arg2;
- (id)_dumpPreviousBackgroundsFromData:(id)arg1 atCurrentTime:(unsigned long long)arg2;
- (void)logExitForAppWithBundleID:(id)arg1 withReason:(unsigned int)arg2;
- (void)logBackgroundActivationForAppWithBundleID:(id)arg1 withReason:(unsigned int)arg2;
- (void)logForegroundActivationForAppWithBundleID:(id)arg1 withReason:(unsigned int)arg2;
- (id)init;

@end

