//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface IOSSHLBackgroundMultitaskingManager : NSObject
{
    NSMutableDictionary *_appToBackgroundTasks;
    NSMutableDictionary *_backgroundFetchTaskValueToWatchdoggableCompletion;
    NSObject<OS_dispatch_queue> *_queue;
    double _watchdogTimeout;
}

+ (id)sharedInstance;
@property(nonatomic) double watchdogTimeout; // @synthesize watchdogTimeout=_watchdogTimeout;
- (void).cxx_destruct;
- (void)queue_fireWatchdoggableCompletionForBackgroundFetchTaskValue:(id)arg1;
- (void)queue_backgroundTaskFinished:(id)arg1 forApplication:(id)arg2;
- (void)queue_startBackgroundFetchTaskForApplication:(id)arg1 sequenceNumber:(int)arg2 withWatchdoggableCompletion:(CDUnknownBlockType)arg3;
- (void)queue_appFinishedBackgroundUpdating:(id)arg1 sequenceNumber:(int)arg2 result:(unsigned int)arg3;
- (void)queue_invalidateBackgroundTasksForApplication:(id)arg1;
- (void)_watchdogCompletionForBackgroundFetchTaskValue:(id)arg1;
- (void)_backgroundTaskFinished:(id)arg1 forApplication:(id)arg2;
- (void)_startBackgroundFetchTaskForApplication:(id)arg1 sequenceNumber:(int)arg2 withWatchdoggableCompletion:(CDUnknownBlockType)arg3;
- (void)_appFinishedBackgroundUpdating:(id)arg1 sequenceNumber:(int)arg2 result:(unsigned int)arg3;
- (void)_invalidateBackgroundTasksForApplication:(id)arg1;
- (void)_appStateDidChange:(id)arg1;
- (int)nextSequenceNumber;
- (id)init;

@end

