//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BSTransaction, CSLActivateApplicationRequest, CSLWorkspaceTransitionRequest, IOSSHLApplication, IOSSHLWorkspace;

@protocol IOSSHLWorkspaceUIDelegate <NSObject>
- (void)workspace:(IOSSHLWorkspace *)arg1 willActivateSystemApplicationWithTransaction:(BSTransaction *)arg2;
- (void)workspace:(IOSSHLWorkspace *)arg1 willActivateApplication:(IOSSHLApplication *)arg2 withTransaction:(BSTransaction *)arg3 suspended:(_Bool)arg4;
- (CSLWorkspaceTransitionRequest *)transitionRequestForExitedApplication:(IOSSHLApplication *)arg1;
- (CSLWorkspaceTransitionRequest *)transitionRequestForApplicationActivationRequest:(CSLActivateApplicationRequest *)arg1 withTransitionReason:(unsigned int)arg2;
- (CSLWorkspaceTransitionRequest *)transitionRequestForActivatingShell;
@end

