//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IOSSHLActivationSettings, IOSSHLApplication, NSDictionary, NSString, NSURL;

@protocol IOSSHLUIDelegate <NSObject>
- (void)applicationOpenURL:(NSURL *)arg1 withApplication:(IOSSHLApplication *)arg2 sender:(IOSSHLApplication *)arg3 publicURLsOnly:(_Bool)arg4 animating:(_Bool)arg5 activationSettings:(IOSSHLActivationSettings *)arg6 withResult:(void (^)(int))arg7;
- (void)failedTest:(NSString *)arg1 withResults:(NSDictionary *)arg2;
- (void)resetIdleTimerAndUndim:(_Bool)arg1;
- (void)noteInterfaceOrientationChanged:(int)arg1 duration:(float)arg2;
- (int)activeInterfaceOrientation;
- (_Bool)systemAppWantsOrientationEvents;
- (NSString *)systemAppBundleIdentifier;
- (short)powerLogClientID;
@end

