//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IOSSHLApplicationActivationRecord, IOSSHLApplicationExitRecord, NSMutableDictionary;

@interface IOSSHLAppRecentEventData : NSObject
{
    NSMutableDictionary *_backgroundActivations;
    IOSSHLApplicationActivationRecord *_foregroundRecord;
    IOSSHLApplicationExitRecord *_exitRecord;
}

@property(retain, nonatomic) IOSSHLApplicationExitRecord *exitRecord; // @synthesize exitRecord=_exitRecord;
@property(retain, nonatomic) IOSSHLApplicationActivationRecord *foregroundRecord; // @synthesize foregroundRecord=_foregroundRecord;
@property(retain, nonatomic) NSMutableDictionary *backgroundActivations; // @synthesize backgroundActivations=_backgroundActivations;
- (void).cxx_destruct;
- (id)init;

@end

