//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IOSSHLPlatform : NSObject
{
    NSString *_currentConfigurationName;
    NSString *_localizedDeviceName;
    _Bool _hasGasGauge;
    _Bool _supportsOpenGLES2;
    _Bool _carrierInstall;
}

+ (id)uniqueDeviceIdentifier;
+ (id)deviceClass;
+ (id)productType;
+ (id)hardwareModel;
+ (id)systemBuildVersion;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (_Bool)isCarrierInstall;
- (_Bool)supportsOpenGLES2;
- (_Bool)hasGasGauge;
- (id)localizedPlatformName;
- (id)init;

@end

