//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSTransactionObserver.h"
#import "CSLStuckTransactionDialogDelegate.h"

@class CSLStuckTransactionContext, CSLStuckTransactionDialog, NSObject<OS_dispatch_queue>, NSString;

@interface IOSSHLTransactionWatchdogHandler : NSObject <BSTransactionObserver, CSLStuckTransactionDialogDelegate>
{
    NSObject<OS_dispatch_queue> *_rootQueue;
    NSObject<OS_dispatch_queue> *_stackshotQueue;
    _Bool _stackshotComplete;
    CSLStuckTransactionContext *_context;
    CSLStuckTransactionDialog *_dialog;
}

@property(retain, nonatomic) CSLStuckTransactionDialog *dialog; // @synthesize dialog=_dialog;
@property(retain, nonatomic) CSLStuckTransactionContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (void)stuckTransactionDialogDidSelectCrash:(id)arg1;
- (void)stuckTransactionDialogDidDismiss:(id)arg1;
- (void)transactionDidComplete:(id)arg1;
- (void)raiseExceptionForContext:(id)arg1;
- (_Bool)engineeringRequestsLiveDebuggingForContext:(id)arg1;
- (_Bool)shouldBluescreenForContext:(id)arg1;
- (void)_logSingleTransaction:(id)arg1;
- (void)logContext:(id)arg1;
- (void)_writeStackshotForContext:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)watchdogFiredForContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

