//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IOSSHLSystem : NSObject
{
}

+ (short)powerLogClientID;
+ (void)anotherApplicationFinishedLaunching:(id)arg1;
+ (void)quitTopApplication:(id)arg1;
+ (void)_topDisplayWantsOrientationEvents:(_Bool *)arg1 bundleIdentifier:(id *)arg2 hasEntitlement:(_Bool *)arg3;
+ (void)updateOrientationDetectionSettings;
+ (id)delegate;
+ (void)setDelegate:(id)arg1;
+ (void)primeSingletons;

@end

