//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBApplicationUpdateScenesTransaction.h"

@class IOSSHLApplication, NSSet, NSString;

@interface IOSSHLApplicationUpdateScenesTransaction : FBApplicationUpdateScenesTransaction
{
    _Bool _activateSuspended;
    IOSSHLApplication *_application;
    NSSet *_actions;
    NSString *_sceneIdentifier;
}

+ (id)sceneParametersForApplication:(id)arg1 settingsConfiguration:(CDUnknownBlockType)arg2;
+ (id)switcherTransactionWithApplication:(id)arg1;
+ (id)standardTransactionWithApplication:(id)arg1 actions:(id)arg2;
@property(retain, nonatomic) NSString *sceneIdentifier; // @synthesize sceneIdentifier=_sceneIdentifier;
@property(retain, nonatomic) NSSet *actions; // @synthesize actions=_actions;
@property(nonatomic) _Bool activateSuspended; // @synthesize activateSuspended=_activateSuspended;
@property(readonly, nonatomic) IOSSHLApplication *application; // @synthesize application=_application;
- (void).cxx_destruct;
- (id)_customizedDescriptionProperties;
- (void)_didComplete;
- (void)_willBegin;
- (id)initWithApplication:(id)arg1;

@end

