//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

@interface UIResponder (FirstResponderAdditions)
- (void)CSL_logResponderSelector:(SEL)arg1 withResult:(int)arg2 logType:(unsigned char)arg3;
- (void)CSL_becomeFirstResponderIfNotAlreadyInResponderChain;
@end

